RedHatInsights/curiosity-frontend

.env
CONTRIBUTING.md
README.md
package.json
public/index.html
public/locales/en.json
src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
src/components/pageLayout/pageLayout.js
src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap
src/components/rhelGraphCard/rhelGraphCard.js
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/router.js
src/styles/_app.scss
src/styles/index.scss

- fix(app name): issues/14 codify app name
...
closes #14

fix(app name): issues/14 codify app name

---

package.json
src/components/rhelGraphCard/rhelGraphCard.js
tests/__snapshots__/i18n.test.js.snap
tests/i18n.test.js
yarn.lock

- fix(rhelCard): issues/5 graphCard i18n ref
* rhelCard, minor key reference
* testing checks for locale keys
- implemented a developer set of checks to make sure if/when we implement locale string refs we're aware that keys should probably also be updated. If not, we acknowledge it, and update the snapshot with the variation.
1. `$ yarn test:integration`
...
#5

fix(rhelCard): issues/5 graphCard i18n ref

---

package.json
tests/__snapshots__/dist.test.js.snap
tests/dist.test.js
tests/version.test.js

- feat(integration tests): issues/24 build testing
* distribution, build checks
* version output check
1. `$ yarn test:integration`
...
#24

feat(integration tests): issues/24 build testing

---

tests/__snapshots__/html.test.js.snap
tests/html.test.js

- feat(integration tests): issues/24 build html output test
The tests around "integration" require a built output in order to function.
...
closes #24

feat(integration tests): issues/24 build html output test

---

tests/__snapshots__/html.test.js.snap
tests/html.test.js

- fix(integration tests): issues/24 build html output test
* missing chars from check
* remove script contents
- in addition to the regex fix for testing, added adjustment for random script contents
...
#24

fix(integration tests): issues/24 build html output test

---

package.json
yarn.lock

- chore(build): npm updates
Ongoing build package updates

chore(build): npm updates

---

.codecov.yml
package.json
yarn.lock

- chore(build): test coverage, npm updates
* test coverage, raise min, match codecov
* npm updates
Ongoing build updates

chore(build): test coverage, npm updates

---

.env
.env.production
scripts/pre.sh
src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap
src/components/router/routerTypes.js
tests/__snapshots__/html.test.js.snap

- fix(build): issues/34 correct deployment path prefix
* build, deployment path prefix
* routerTypes, update route, use acronym
1. next open up the build directory that was created, you should be able to find these paths with the `esi` includes... 
- `<esi:include src="/apps/chrome/snippets/head.html" />`
- `<esi:include src="/apps/chrome/snippets/body.html" />`
1. you can test check what's produced during a beta branch build, by exporting a "fake" branch value...
- `$ export BRANCH=ci-beta; yarn build`
1. next open up the build directory that was created, you should be able to find these paths with the `esi` …

fix(build): issues/34 correct deployment path prefix (#49)

---

.env.proxy

- fix(build): issues/34 custom dotenv, rhsm path added back
- corrects the path for rhsm during proxy run. the load order for custom dotenv files gets a little out of wack
updates #34

fix(build): issues/34 custom dotenv, rhsm path added back

---

src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap
src/components/rhelGraphCard/rhelGraphCard.js
src/styles/_usage-graph.scss
tests/__snapshots__/i18n.test.js.snap

Pretty  explanatory here, just temporarily disabling the Dropdown for the Label.
closes #53

feat(rhelGraphCard): use label instead of dropdown for phase 1

---

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap
src/components/router/routerTypes.js

- fix(routerTypes): root path added (#65)
...
#34

fix(routerTypes): root path added (#65)

---

.travis/custom_release.sh
CONTRIBUTING.md

- feat(build): issues/97 branching and qe integration
* master branch equates production
* ci branch equates ci and qa related beta branches
* contributing updates for branches, PRs, and releases
Updates #97

feat(build): issues/97 custom branches for qe integration

---

.eslintrc
src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/__tests__/chartArea.test.js
src/components/chartArea/chartArea.js
src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap

- fix(chartArea): custom tooltips, remove unused properties
* update dataSets with custom tooltips
* tick formatting, stacked dataSets included in max y domain
* remove unused y axis props
* move container component into method
- This is a incremental update while the GUI is converted towards displaying the Hypervisor aspect of the RHSM API properties.
1. No visual changes should be detectable. And no console errors should be present
1. No visual changes should be detectable. And no console errors should be present
...
Relates to #79

fix(chartArea): custom tooltips, remove unused properties

---

src/common/__tests__/__snapshots__/dateHelpers.test.js.snap
src/common/__tests__/__snapshots__/graphHelpers.test.js.snap
src/common/__tests__/graphHelpers.test.js
src/common/dateHelpers.js
src/common/graphHelpers.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCardHelpers.test.js.snap
src/components/rhelGraphCard/__tests__/rhelGraphCardHelpers.test.js
src/components/rhelGraphCard/rhelGraphCard.js
src/components/rhelGraphCard/rhelGraphCardHelpers.js

- fix(graphHelpers,rhelGraphCardHelpers): restructured helpers
* graphHelpers, converted towards rhelGraphCardHelpers
* dateHelpers, timestamp formats
* tests, restructured towards rhelGraphCardHelpers
- This is a incremental update while the GUI is converted towards displaying the Hypervisor aspect of the RHSM API properties.
1. No visual changes should be detectable. And no console errors should be present
1. No visual changes should be detectable. And no console errors should be present
...
Related to #79

fix(graphHelpers,rhelGraphCardHelpers): restructured helpers

---

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(tourView): learn more href update
- fix(tourView,rhelView): issues/133 copy updates
* tourView, title updates, timing for locale string replacement
* rhelView, title update to remain consistent with tourView
- the rhelView update is a behind the scenes update and is not directly observable
1. Navigate towards `/beta/subscriptions/soon` to confirm the copy and "learn more" link. You should see something similar to the below screenshot
updates #133

Tour view updates, issues/133

---

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap
src/components/rhelGraphCard/__tests__/rhelGraphCard.test.js
src/components/rhelGraphCard/rhelGraphCard.js
src/components/rhelView/rhelView.js
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap
src/components/router/__tests__/router.test.js
src/components/router/router.js
src/components/router/routerTypes.js
src/redux/middleware/index.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/graphCardSelectors.js

- fix(rhelGraphCard,redux): issues/133 add tour redirect
* redux, disable global toasts on error, set individually
* rhelGraphCard, embed redirect, 403, 500 checks
* rhelView, pass errorRoute
* router, routerTypes, pass errorRoute to route components
* graphCardSelectors, pass error and errorStatus
* i18n testing snapshot
1. you'll need to log in with an entitled account to confirm the redirect does **NOT** happen, after you confirm then
1. you'll need to log in with a non-entitled account to confirm the redirect **DOES** happen
...
Close #133

fix(rhelGraphCard,redux): issues/133 add tour redirect

---

src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/chartArea.js

- fix(chartArea): issues/142 update interpolation default
1. the area chart should now display with more exacting lines and curves
closes #142

fix(chartArea): issues/142 update interpolation default

---

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(tourView): revert learn more link rel attribute
- Minor `rel` attribute revert for multi login scenarios
...
Relates to #150

fix(tourView): revert learn more link rel attribute

---

CHANGELOG.md
package.json
public/locales/en-US.json
src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/chartArea.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap
src/components/rhelGraphCard/__tests__/rhelGraphCard.test.js
src/components/rhelGraphCard/rhelGraphCard.js
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap
src/components/router/__tests__/router.test.js
src/components/router/router.js
src/components/router/routerTypes.js
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js
src/redux/actions/rhelActions.js
src/redux/middleware/index.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/graphCardSelectors.js

* **chartArea:** issues/142 update interpolation default ([#149](https://github.com/RedHatInsights/curiosity-frontend/issues/149)) ([57af67a](https://github.com/RedHatInsights/curiosity-frontend/commit/57af67a))
* **i18n:** issues/146 update system label copy ([eb7a394](https://github.com/RedHatInsights/curiosity-frontend/commit/eb7a394))
* **rhelActions:** issues/133 disable toasts ([#150](https://github.com/RedHatInsights/curiosity-frontend/issues/150)) ([ba18bbf](https://github.com/RedHatInsights/curiosity-frontend/commit/ba18bbf))
* **rhelGraphCard:** issues/148 subtle color adjustment ([219f3d2](https://github.com/RedHatInsights/curiosity-frontend/commit/219f3d2))
* **rhelGraphCard,redux:** issues/133 add tour redirect ([#145](https://github.com/RedHatInsights/curiosity-frontend/issue …

Production Increment 0.1.7

---

public/locales/en-US.json
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(tourView): issues/153 additional copy and contact us link
1. navigate to the path `/soon` to view the updates similar to the below example
updates #153

fix(tourView): issues/153 additional copy and contact us link

---

CONTRIBUTING.md
src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/chartArea.js

- fix(chartArea): issues/133 add a css className and ID
* add css classNames and ID for external tooling access, modal display
- there are no visual changes with this update
- adds 2 classes and 1 ID to the chartArea element. The chartArea element is only displayed in the event the API is not `pending` but `loaded`
- ID = `curiosity-chartarea`
- Class name = `uxui-curiosity__modal`
- Class name = `uxui-curiosity__modal--loading`
1. right click to inspect the chartArea element, you may have to search for the related ID or class names.
- ID = `curiosity-chartarea`
- Class name = `uxui-curiosity__modal`
- Class name = `uxui-curiosity__modal--loading`
...
Related to #133 
@jeperry @bclarhk

fix(chartArea): issues/133 add a css className and ID

---

CHANGELOG.md
CONTRIBUTING.md
package.json
public/locales/en-US.json
src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/chartArea.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

* **chartArea:** issues/133 add a css className and ID ([c097c9c](https://github.com/RedHatInsights/curiosity-frontend/commit/c097c9c)) ->([cbdafcd](https://github.com/RedHatInsights/curiosity-frontend/commit/cbdafcd ))
* **tourView:** issues/153 additional copy and contact us link ([12cfc27](https://github.com/RedHatInsights/curiosity-frontend/commit/12cfc27))

Production Increment 0.1.8 

---

src/components/graphCard/graphCardHelpers.js
src/services/__tests__/__snapshots__/userServices.test.js.snap
src/services/__tests__/config.test.js
src/services/__tests__/rhsmServices.test.js
src/services/__tests__/userServices.test.js
src/services/config.js
src/services/rhsmServices.js
src/services/userServices.js

- fix(graphCardHelpers): consistency clean up
- fix(services): issues/167 login, update platform getUser 
* services config, pass through for applying platform getUser
* userServices, authorizeUser restructured, get api version relocated
* rhsmServices, apply pass through getUser, get api version method
- ~fix(authentication): issues/159 redirect on malformed user~ 
- This is an initial attempt to align with the other platform GUIs. The intention isn't to solve the platform login issue, but the refresh issue associated with multiple logins
- This is a behind the scenes update there will be no visual differences applied to the GUI
- These changes should help set the groundwork resolution for issue #159 
1. make sure Docker is running, plus on …

fix(services): issues/167 login, update platform getUser

---

src/components/app.js
src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/authentication/__tests__/authentication.test.js
src/components/authentication/authentication.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap
src/components/messageView/__tests__/messageView.test.js
src/components/messageView/messageView.js
src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap
src/components/openshiftView/openshiftView.js
src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
src/components/pageLayout/pageLayout.js
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/router/__tests__/__snapshots__/redirect.test.js.snap
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap
src/components/router/__tests__/redirect.test.js
src/components/router/__tests__/routerHelpers.test.js
src/components/router/redirect.js
src/components/router/router.js
src/components/router/routerHelpers.js
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(pageLayout,messageView): restructure view layout 
* app, remove pageLayout
* authentication, apply messageView, remove emptyState and layout
* messageView, view for generic messaging and title
* openshiftView, rhelView, tourView, apply pageLayout
* pageLayout, apply div and CSS class from router
* router, remove div and CSS class
- fix(router,redirect): issues/176 restructure redirect
* authentication, redirect restructure
* redirect, removed router redirect in favor of route
* router, expanded routerHelpers
* routerHelpers, expand to expose route detail and navigation
These are behind the scenes updates meant to resolve what comes across as a race condition using the previous redirect. The end result manifested itself in one of two outcomes
- The redirect worked and forwarded the …

fix(router,redirect): issues/176 restructure redirect

---

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap
src/components/messageView/messageView.js
src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap
src/components/openshiftView/openshiftView.js
src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap
src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
src/components/pageLayout/__tests__/__snapshots__/pageSection.test.js.snap
src/components/pageLayout/__tests__/pageHeader.test.js
src/components/pageLayout/__tests__/pageLayout.test.js
src/components/pageLayout/__tests__/pageSection.test.js
src/components/pageLayout/pageHeader.js
src/components/pageLayout/pageLayout.js
src/components/pageLayout/pageSection.js
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(pageLayout): restructure view layout
* pageHeader, pageSection pass through components added
* pageLayout, continued convert from pf to platform components
* openshift, rhel, message, and tour views page layout adjusted
* messageView, remove redundant proptypes
* authorization, i18n test updates
- Fix for pageLayout
- Appears the restructure re-exposed a potential PF component bug related to a resize event on unmounted "Page". We're guessing this may be part of the issue, [PF 4 Page Component](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Page/Page.tsx#L140-L141). We're no longer using this component.
- We continued the conversion over toward platform components in place of PF components directly
- Avoided use of the …

CI/Dev fixes for issues/176 redirect, and page restructure

---

src/redux/reducers/__tests__/__snapshots__/userReducer.test.js.snap
src/redux/reducers/userReducer.js
src/services/platformServices.js

- fix(platformServices): issues/43 apply dev mode
* platformServices, allow dev mode
* userReducer, remove unused username
1. confirm the GUI loads past the authenticating state messaging
...
#43

fix(platformServices): issues/43 apply dev mode

---

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap
src/components/tourView/tourView.js

- fix(tourView): issues/192 update learn more link
* tourView, learn more link
* authentication, test snapshot
1. After everything has loaded, manually enter the path `http://localhost:3000/tour` in your browser, and confirm the link is valid by clicking the `Learn more` link in the middle
...
Close #192 
Relates to https://github.com/RedHatInsights/insights-chrome/pull/600

fix(tourView): issues/192 update learn more link

---

package.json
yarn.lock

- chore(build): npm component updates
* chart and i18n packages
ongoing

chore(build): npm component updates

---

src/redux/actions/__tests__/rhsmActions.test.js
src/redux/actions/rhsmActions.js
src/redux/reducers/__tests__/__snapshots__/graphReducer.test.js.snap
src/redux/reducers/__tests__/__snapshots__/userReducer.test.js.snap
src/redux/reducers/__tests__/graphReducer.test.js
src/redux/reducers/__tests__/userReducer.test.js
src/redux/reducers/graphReducer.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/__tests__/graphCardSelectors.test.js
src/services/__tests__/__snapshots__/platformServices.test.js.snap
src/services/__tests__/platformServices.test.js

- fix(graphReducer,rhsmActions): clean up unused actions
* graphReducer, remove unused action types
* rhsmActions, remove unused actions
- fix(graphCardSelectors,redux,services): expand unit testing
* userReducer, snapshot 4XX http status
* graphCardSelectors, snapshot against null value
* platformServices, confirm thrown errors
- Minor code clean up, unused actions and types within the Redux setup
- Expanded unit testing
- Dependent on PR #215 
...
Ongoing

Clean up and expand unit testing

---

src/components/select/__tests__/__snapshots__/select.test.js.snap
src/components/select/__tests__/select.test.js
src/components/select/select.js

- fix(select): correct single variant check
* fixes single variant check
* expands component update check
* expands provided mock target data, aligns “checked” to pf result
* expands selected values check to include both title and value
- These changes expand the select to work in scenarios presented by the SLA toolbar filter
- This is a behind the scenes update. Unit tests and snapshots have been expanded to confirm both 
- the ability to match selected options against title and value, and
- the ability to select multiple options with the checkbox variant
...
Related to #76

fix(select): correct variant check, expand formatting options

---

src/components/graphCard/graphCard.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap
src/components/openshiftView/openshiftView.js
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap
src/components/toolbar/toolbar.js
src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap
src/redux/reducers/__tests__/viewReducer.test.js
src/redux/reducers/viewReducer.js
src/redux/selectors/viewSelectors.js

- feat(rhelView): issues/234 display SLA toolbar
* graphCard, update store towards using RHSM granularity query type
* openshiftView, viewId adjustment, apply store graphQuery to toolbar
* rhelView, viewId adjustment, add & apply store graphQuery to toolbar
* toolbar, remove internal state in favor of redux
* viewReducer, apply viewId to graphQuery
* viewSelectors, apply viewId to graphQuery
1. Next, interact with the RHEL SLA filter. To confirm the filter is active you'll need to pull up the browser developer console and compare the XHR network tab calls for the SLA query parameter.
#234 
@rblackbu

feat(rhelView): issues/234 display SLA toolbar

---

public/locales/en-US.json
src/components/graphCard/graphCard.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap
src/components/openshiftView/openshiftView.js
src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap
src/components/rhelView/rhelView.js
src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap
src/components/toolbar/toolbar.js
src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap
src/redux/reducers/__tests__/viewReducer.test.js
src/redux/reducers/viewReducer.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/viewSelectors.js
src/services/rhsmServices.js
src/types/__tests__/__snapshots__/rhsmApiTypes.test.js.snap
src/types/rhsmApiTypes.js

* **build:** issues/231 code documentation, linting ([#232](https://github.com/RedHatInsights/curiosity-frontend/issues/232)) ([bb46552](https://github.com/RedHatInsights/curiosity-frontend/commit/bb46552e23f38fb26fb08c8ee0e29318883d489f))
* **rhelView:** issues/234 display SLA toolbar ([#236](https://github.com/RedHatInsights/curiosity-frontend/issues/236)) ([226c390](https://github.com/RedHatInsights/curiosity-frontend/commit/226c390eb9f3f42899fb6d2c8c663e67f2f6983c))
* **build:** issues/234 enable toolbar with SLA filter ([#235](https://github.com/RedHatInsights/curiosity-frontend/issues/235)) ([17a2fab](https://github.com/RedHatInsights/curiosity-frontend/commit/17a2fab1e275d730c46cef29569e0d381730b618))
* **routerHelpers:** issues/218 dynamic base name tests …

CI to QA - Branch Sync

---

src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap
src/components/optinView/__tests__/optinView.test.js

- fix(optinView): issues/240 expand unit tests
- Expand unit tests for baseline
...
#240

fix(optinView): issues/240 expand unit tests

---

scripts/dev.chrome.sh
scripts/proxy.api.sh
src/common/__tests__/__snapshots__/helpers.test.js.snap
src/common/__tests__/helpers.test.js
src/common/helpers.js

- chore(build): dev, proxy run terminal output
* chrome, minor copy update
* proxy run, output format, expire for repo
- fix(helpers): access to an app specific window object
- Minor build formatting updates
- Corrects the helpers behavior, too strict, relaxes it back to behavior prior #256 
...
Ongoing

chore(build): dev, proxy run terminal output

---

.gitignore
src/components/authentication/authentication.js

- fix(authentication): issues/262 await authorizeUser
* authentication, quick fix, give routing race condition lead time
- this is a quick fix, a more permanent solution should be investigated
- per the platform team, there appears to be a race condition present, one where the platform beta environments behave slower than stable environments.
- the race condition presents itself in the GUI trying to reroute after it has initialized the "platform chrome". Initializing it loads the source of truth config which in turn reads the pre-rerouted/route you first landed on then makes a comparison throwing the "[this isn't a platform app]" name error.
- we get around this race condition by simply giving the router time to redirect while we "authorize" the user
- the platform team recommended we …

fix(authentication): issues/262 await authorizeUser

---

.gitignore
src/components/authentication/authentication.js

* **authentication:** issues/262 await authorizeUser ([#264](https://github.com/RedHatInsights/curiosity-frontend/issues/264)) ([ed50f27](https://github.com/RedHatInsights/curiosity-frontend/commit/ed50f272b045bc8b77c83f62ada781d6e40e7ff8))

Draft 0.1.15

---

.travis.yml
CONTRIBUTING.md
README.md
tests/dist.test.js

- chore(build,docs): nodejs 12 for CI
* docs, update install, git structure, and process directions
* travis, add nodejs 12 to environments
- fix(testing): minor regex, for scenarios testing platform config
- Primarily documentation updates
...
Ongoing

Update to NodeJS 12+

---

src/components/authentication/authentication.js
src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap
src/components/router/__tests__/router.test.js
src/components/router/__tests__/routerHelpers.test.js
src/components/router/router.js
src/components/router/routerHelpers.js

- feat(router,routerHelpers): issues/283 location.search
* authentication, routeHref a combined path, search and hash
* router, apply parsed location.search prop to routed components
* routerHelpers, allow location search and hash parameters
- adds in query-string parameter parsing to routed components
- allows the passing of search/query-string and hash parameters
1. **BEFORE** syncing with this PR
1. once the browser is open within the url field add any query-string to the end of the path, i.e. `?random=value`
1. hit enter and refresh the browser
1. the expected result is... the browser should remove the query-string
1. **AFTER** syncing with this PR
1. repeat the same …

feat(router,routerHelpers): issues/283 location.search

---

public/locales/en-US.json
src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap
src/components/chartArea/__tests__/chartArea.test.js
src/components/chartArea/chartArea.js
src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap
src/components/graphCard/__tests__/graphCardChartLegend.test.js
src/components/graphCard/graphCard.js
src/components/graphCard/graphCardChartLegend.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/styles/_usage-graph.scss

- feat(chartArea,graphCard): issues/283 custom legends
* chartArea, add chartLegend component for custom legend
* graphCard, switch to graphCardChartLegend component
* graphCardChartLegend, custom component legend
* i18n, key fallback for missing legend labels
* styling, minor legend styles added
1. hover over the legends to confirm tooltip behavior, switch granularity, product and/or architecture to observe disabled legend items
#283 
#158 
relates #181

feat(chartArea,graphCard): issues/283 custom legends

---

tests/commit.test.js

- fix(build,test): issues/321 commit lint, rebase
* build, commit lint checks adjusted for rebase
- this check needs to be converted to a Github action, update this, or create a new issue.
- this check runs after the build
1. no errors, unless a malformed commit is present, should happen
...
#321

fix(build): issues/321 commit lint, rebase

---

src/components/graphCard/graphCard.js
src/redux/actions/__tests__/rhsmActions.test.js
src/redux/common/reduxHelpers.js
src/redux/reducers/__tests__/__snapshots__/inventoryReducer.test.js.snap
src/redux/reducers/inventoryReducer.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/__tests__/__snapshots__/guestListSelectors.test.js.snap
src/redux/selectors/__tests__/__snapshots__/inventoryListSelectors.test.js.snap
src/redux/selectors/__tests__/graphCardSelectors.test.js
src/redux/selectors/__tests__/guestListSelectors.test.js
src/redux/selectors/__tests__/inventoryListSelectors.test.js
src/redux/selectors/graphCardSelectors.js
src/redux/selectors/guestsListSelectors.js
src/redux/selectors/index.js
src/redux/selectors/inventoryListSelectors.js
src/redux/selectors/userSelectors.js
src/redux/selectors/viewSelectors.js
src/services/rhsmServices.js

- fix(graphCard,selectors): issues/10 generic selectors 
* graphCard, selector sequence consistency
* selectors, user, view, graphCard, code and test consistency
- fix(inventoryListSelectors): issues/10 selectors , state
* inventoryReducer, hostsGuests rename, test snapshot
* inventoryListSelectors, initial selector, memoize/cache
* guestListSelectors, initial selector,  memoize/cache
* reduxHelpers, annotation
* rhsmActions, hostsGuests test
* rhsmServices, mock data, delay, annotations
- Incremental behind the scenes state management updates for hosts and guests inventory displays
1. confirm the GUI functions without error
...
updates #10

fix(inventoryListSelectors): issues/10 selectors , state

---

public/locales/en-US.json
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/loader/__tests__/__snapshots__/loader.test.js.snap
src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap
src/components/table/tableSkeleton.js

fix(tableSkeleton): issues/10 locale, borders prop
* tableSkeleton, fix mismatched borders prop
* locale, i18n, tableSkeleton ariaLabel
- Behind the scenes update
- Expanded Locale string for aria-label
...
#10

fix(tableSkeleton): issues/10 locale, borders prop

---

public/locales/en-US.json
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/loader/__tests__/__snapshots__/loader.test.js.snap
src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap
src/components/table/tableSkeleton.js
tests/__snapshots__/code.test.js.snap
tests/code.test.js

1. **tableSkeleton** issues/10 locale, borders prop (#350) (4d05ed6)
1. **testing** add general code tests, lost console methods (#351) (ddba601)

Environment Sync, Dev to Test

---

.codecov.yml
package.json

- chore(build): issues/333 update min test coverage
- update branch and function minimum coverage from 65 to 80
- update line and statement minimum coverage from 65 to 90
- update codecov.yml minimum coverage from 65 to 80
Updates #333

chore(build): issues/333 update min test coverage

---

README.md
package.json

- chore(build): update Node 10 references to Node 12
- update Node 10 reference in README.md
- update Node 10 requirement in package.json
Updates #335

chore(build): update Node 10 references to Node 12

---

package.json

- chore(build): expand changelog displayed commits
- we added a commit that originally didn't expose its type on the changelog, "styles"
- this affects the CHANGELOG.md file only
1. sync tags and commits to Curiosity and the CI branch
1. `$ yarn release --dry-run`
1. console message should show the commit type "styles", now
...
Ongoing

chore(build): expand changelog displayed commits

---

.github/PULL_REQUEST_TEMPLATE.md

- chore(build): issues/418 PR template review notes
- build related, behind the scenes, commented out copy when opening a PR
...
#418

chore(build): issues/418 PR template review notes

---

CONTRIBUTING.md
config/README.md

- chore(docs): issues/406 spandx config notes
- Minor documentation regarding the interested parties in our spandx.config
...
#406

chore(docs): issues/406 spandx config notes

---

src/components/chartArea/__tests__/chartArea.test.js
src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap
src/components/inventoryList/inventoryList.js
src/components/minHeight/__tests__/minHeight.test.js
src/components/minHeight/minHeight.js
src/styles/_inventory-list.scss
src/styles/index.scss

- fix(inventoryList): issues/403 minHeight update on perpage
- fix(minHeight): issues/403 resize events reset height
- fix(inventoryList): activate paging for smaller screen sizes
- fix(chartArea): resize observer test addition
- Corrects min-height issue when both changing "per page" on paging and adjusting the browser size
- @ntkathole 
- Re-activates the paging display CSS for smaller screens. This also appears to affect the primary inventory, and appears Patternfly related, https://www.patternfly.org/v4/components/pagination
- Expand chartArea unit test
1. choose an account with a large inventory and select "100" entries per-page
1. then navigate to the next page with …

fix(inventoryList): issues/403 minHeight update on perpage

---

public/locales/en-US.json

- fix(locale): issues/481 add cloud provider string
- Adds the Alibaba provider string
- Retaining the IBM Cloud string for the short term, they're contextually based on the API response, there are no concerns they'll display unexpectedly.
- Because of the way our strings are setup, using context, if one doesn't exist it should simply pass through in all lowercase
1. log in with credentials that have access to the `Alibaba` cloud provider
1. confirm the `Alibaba` string displays
updates #481

fix(locale): issues/481 add cloud provider string

---

src/components/table/table.js

- fix(table): issues/494 title prop is defined check
- Condition update to avoid "truthy" check, instead we now use "is defined". Upcoming changes to allow for column table "cellTransform" highlighted a potential error where `[object Object]` would display. There was an instance of zero being passed during testing, this updated check avoids that future scenario even though there should never technically be "zero" sockets/cores displayed
1. confirm the tests pass
#494

fix(table): issues/494 title prop is defined check

---

.github/workflows/commit_lint.yml
.github/workflows/pull_request.yml

- chore(build): nodejs 14 for CI
- Initial updates for CI in prep for migrating to the current Node LTS
- Running the 14 checks in addition to the 12 checks is not long term, the plan is to remove the 12 checks after testing
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
...
Ongoing, #514

chore(build): nodejs 14 for CI

---

.github/workflows/commit_lint.yml
.github/workflows/pull_request.yml
.travis.yml
README.md
package.json

- chore(build): issues/514 update nodejs 12 references to 14
- activates nodejs 14
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
...
Relates to #515 
Closes #514

chore(build): issues/514 update nodejs 12 references to 14

---

public/locales/en-US.json

- fix(build): issues/502 banner message spelling
- @jlprevatt @ntkathole 
1. log in with a related account, one with mismatched data
1. confirm the word "recommended" is spelled correctly
...
#502

fix(build): issues/502 banner message spelling

---

src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap
src/components/inventoryList/__tests__/inventoryList.test.js
src/components/inventoryList/inventoryList.js
src/components/inventorySubscriptions/__tests__/__snapshots__/inventorySubscriptions.test.js.snap
src/components/inventorySubscriptions/__tests__/inventorySubscriptions.test.js
src/components/inventorySubscriptions/inventorySubscriptions.js
src/components/pagination/__tests__/__snapshots__/pagination.test.js.snap
src/components/pagination/__tests__/__snapshots__/paginationHelpers.test.js.snap
src/components/pagination/__tests__/pagination.test.js
src/components/pagination/__tests__/paginationHelpers.test.js
src/components/pagination/pagination.js
src/components/pagination/paginationHelpers.js

- fix(pagination): issues/491 missing limit, offset query
* pagination, pass missing query from inventory
* inventoryList, inventorySubs, pass query to pagination
- perf(pagination): move redux on page into inventory * pagination, restructure, remove redux
* paginationHelpers, page to offset, offset to page
* inventoryList, inventorySubs, apply onPage events
- There was an oversight on passing the specific/unique queries for limit and offset from the parent inventory components. 
- ~The query parameter is now required for pagination, in the future code checks should catch the query if it fails to pass.~ To avoid "prop-drilling", and overly-complicated type props used for updating Redux state, we now handle paging in the inventory components, this avoids the entire original issue. Unit …

fix(pagination): issues/491 missing limit, offset query

---

src/components/inventoryList/inventoryList.js
src/components/inventorySubscriptions/inventorySubscriptions.js

- fix(inventoryList): issues/403 minHeight update on error
- corrects an issue where the inventory display will not adjust it's minheight when an error occurs
...
Relates #403

fix(inventoryList): issues/403 minHeight update on error

---

CONTRIBUTING.md
scripts/actions.commit.js

- chore(build): issues/543 jira for commits
* commit lint, allow jira issues
* contributing, commit format
- as this PR is going in [we've activated to "auto-link" references](https://docs.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources) 
- one that redirects `issues/<num>` to GitHub issues, and
- one that redirects `ent-<num>` to Jira issues
- auto-link does NOT appear to retroactively go back on existing docs, maybe it will eventually ¯\_(ツ)_/¯
- behind the scenes update that affects general issues, PRs, commit messages, and hopefully the changelog
...
#543

chore(build): issues/543 jira for commits

---

scripts/actions.commit.js

- chore(build): rollback for commit lint
- We'll have to merge this commit lint update POST release
...
relates #543

chore(build): rollback for commit lint

---

src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap
src/components/toolbar/toolbarFieldDisplayName.js
src/redux/common/__tests__/__snapshots__/reduxHelpers.test.js.snap
src/redux/common/__tests__/reduxHelpers.test.js
src/redux/common/reduxHelpers.js

Environment sync
1. **reduxHelpers** response message status range (#570) (b3abd2e)
1. **toolbarFieldDisplayName** issues/569 maxlength char limit (#570) (aa285e3)
This PR is a set of updates based on review of the 1.4.0 release

Draft release 1.4.0, Sync Test to Stage - Update

---

src/components/toolbar/__tests__/toolbarFieldDisplayName.test.js
src/components/toolbar/toolbarFieldDisplayName.js
src/styles/_form.scss
src/styles/_toolbar.scss

- fix(toolbarFieldDisplayName): issues/476 delay, style override
- appears there is a style override happening in environment around the search icon, this aims to correct that
- unfortunately this is one of those PRs that need to be merged to be confirmed since the environment seems to have a overriding CSS difference
...
#476 aka ent-3197

fix(toolbarFieldDisplayName): issues/476 delay, style override

---

.github/workflows/push_request.yml
.travis/custom_release.sh

WIP Build ghaction push testing

---

package.json
src/components/chartArea/chartArea.js
src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap
yarn.lock

- fix(build): npm updates
1. confirm integration tests complete
...
Ongoing

fix(build): npm updates

---

src/components/pageLayout/__tests__/__snapshots__/pageColumns.test.js.snap
src/components/pageLayout/pageColumns.js
src/styles/_page-layout.scss
src/styles/_toolbar.scss

- fix(pageColumns): apply column spacer on multicolumn views
Ongoing

fix(pageColumns): apply column spacer on multicolumn views

---

.github/dependabot.yml

- chore(build): activate dependabot
- activates dependabot for npm packages and github actions
n/a
...
Ongoing

chore(build): activate dependabot

---

.travis.yml

- chore(build): travis dependabot check
- prevents travis from running its checks on pushed branches, ie. like those created by dependabot
...
Ongoing

chore(build): travis dependabot check

---

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap
src/components/productView/__tests__/__snapshots__/productViewOpenShiftDedicated.test.js.snap
src/components/productView/__tests__/productViewOpenShiftContainer.test.js
src/components/productView/__tests__/productViewOpenShiftDedicated.test.js
src/components/productView/productViewOpenShiftContainer.js
src/components/productView/productViewOpenShiftDedicated.js
src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
src/redux/selectors/__tests__/graphCardSelectors.test.js
src/redux/selectors/graphCardSelectors.js
src/services/rhsmServices.js

- fix(graphCardSelectors): ent-3816 graph display floats
* graphCardSelectors, display float, limit for tooltip display
* rhsmServices, adjust mocks
- fix(productView): fix display for core hours below 1000
- Inadvertently partially corrects/narrows some of the total gap highlighted in issue ent-3816 around the `core hours used` total display
- includes a fix for the "core hours used" where numbers below 1000 would display as `0.9K` for 900, etc
1. confirm the core hours used total is slightly more accurate
1. confirm the core hours displayed in the graph tooltip now displays up to 2 decimal places for core hours
1. make sure …

fix(graphCardSelectors): ent-3816 graph display floats

---

src/components/form/select.js
src/styles/index.scss

fix(select): attempt loading styles directly

---

.eslintrc
package.json
src/components/i18n/__tests__/i18n.test.js
src/components/productView/__tests__/productViewMissing.test.js
src/components/router/__tests__/routerHelpers.test.js
src/setupTests.js
tests/__snapshots__/code.test.js.snap
yarn.lock

- fix(testing): outside src import, unit test locale
* build, package apply locale as dev dependency
* i18n, import locale
- fix(testing): mock window location, components with hooks
* i18n remove load hook comp
* tests, mock window location
1. confirm all tests pass
...
ongoing

fix(testing): mock window location, components with hooks

---

src/components/router/__tests__/__snapshots__/router.test.js.snap
src/components/router/__tests__/router.test.js
src/components/router/router.js
src/setupTests.js
tests/__snapshots__/code.test.js.snap

- refactor(router): ent-2745 function, hook convert
1. login and confirm all views are still able to be accessed
...
ent-2745

refactor(router): ent-2745 function, hook convert

---

public/locales/en-US.json

- fix(locale): ent-4045 threshold graph legend strings
- this commit will be squashed with PRs #731 and #728
- this adds in an updated requested via CCS, @jlprevatt @mirekdlugosz 
1. confirm the string update appears for both Sockets and Cores under OpenShift Container
ent-4045
related #731 #728

fix(locale): ent-4045 threshold graph legend strings

---

.github/dependabot.yml

- chore(build): update dependabot
- ignore build packages that generally require a visual review
...
ongoing

chore(build): update dependabot

---

CONTRIBUTING.md
README.md

- chore(docs): ent-4107 update markdown with console
1. confirm the markdown files correctly point to `console.redhat.com` instead of `cloud.redhat.com`
...
ent-4107

chore(docs): ent-4107 update markdown with console

---

.github/workflows/pull_request.yml

- chore(deps): actions/setup-node yarn cache
...
ongoing

chore(deps): actions/setup-node yarn cache

---

.github/workflows/commit_lint.yml
.github/workflows/pull_request.yml

- chore(build): nodejs 16 pr checks
...
ongoing

chore(build): nodejs 16 pr checks

---

public/locales/en-US.json

- fix(locales): thresholdSockets legend string for Satellite
- appears we missed a keyword in the key for the fallback string on thresholds, this corrects it
- related code is here in [graphCardChartLegend](https://github.com/RedHatInsights/curiosity-frontend/blob/ci/src/components/graphCard/graphCardChartLegend.js#L83)
- @mirekdlugosz @ntkathole 
1. navigate to Satellite... at any Subscriptions path change the route to be `satellite`, i.e. `/openshift/subscriptions/satellite`
1. hover over the threshold graph legend and confirm the copy is updated
ongoing

fix(locales): thresholdSockets legend string for Satellite

---

.env.development
.env.proxy
config/webpack.dev.config.js
config/webpack.proxy.config.js

- build(proxy): ent-4581 default towards stage-beta, stable
- updates the default for local development towards stage domain
- there will be additional updates in 2022 around
- `ci` branch will be become `dev`
- `qa` branch may become `test`, still determining
- repo level docs updated to reflect environment and git updates
1. Confirm additional staging access with the proxy
1. confirm you can log in and review the default `stage-beta` environment
1. next quit/ctrl-c the `$ yarn start:proxy` terminal command 
1. create a dotenv local file, `.env.local`
- Add the line DEV_BRANCH=stage-stable
1. confirm you can log in and review the `stage-stable` …

build(proxy): ent-4581 default towards stage-beta, stable

---

src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap
src/components/optinView/__tests__/optinView.test.js
src/components/optinView/optinView.js

- refactor(optin): ent-4572 convert class component
- there should be no visual or behavioral changes associated with this update
1. confirm existing unit tests for optinView pass
- _* original unit tests and snapshots were used as the baseline for behavior_
...
ent-4572

refactor(optinView): ent-4572 convert class component

---

src/config/product.openshiftContainer.js
src/config/product.rhel.js
src/config/product.rhosak.js

- fix(config): ent-4777 next_event_date display format
- currently alters the date form from `...DD-MM` towards `...MM-DD`
1. login and observe a product with subscription inventory (RHEL et all, OpenShift Container, RHOSAK) and confirm the date format has been corrected
...
ent-4777

fix(config): ent-4777 next_event_date display format

---

src/components/authentication/__tests__/authenticationContext.test.js
src/components/authentication/authenticationContext.js

- fix(authenticationContext): ent-4669 pass errorStatus correctly
- Optional chaining was masking the fail, in turn this incorrectly pulled the error status code passing `null`, this in turn caused the OptIn form button to incorrectly display the activate button at multiple points
- @mirekdlugosz @diegomaranhao we probably still need to review what happens after OptIn is submitted
1. Confirm a user needs to be Opted in, a 403 should be generated by any RHSM API endpoint
- Step through the Optin process, the button should be active
- Next click the OptIn button to activate
- A toast notification should appear in the upper right along with disabling the button
- Hitting …

fix(authenticationContext): ent-4669 pass errorStatus correctly

---

.github/dependabot.yml
.travis.yml
.travis/custom_release.sh
CONTRIBUTING.md
package.json

- build(branching):  sw-450 restructure, rename
* CONTRIBUTING, document branching, tags, release
* custom_release, align release branching for travis
* dependabot
- @diegomaranhao
- On QE approval the process will be as follows
- `ci` branch will be renamed `dev` branch
- `main` branch will stay the same
- `stage` branch will be deleted
- `qa` branch will be deleted
- this PR will be merged into the `main` branch ~new `prod` branch (we've already created it)~ and the commit rebased ~across all remaining branches~ down to dev
- and that will leave us with 2 branches, `dev` and `main`
- @mirekdlugosz does default branch for this new process matter? we're considering making the new `dev` branch the default
...
sw-450

build(branching): sw-450 restructure, rename

---

src/services/rhsm/rhsmTransformers.js

- fix(rhsmTransformers): sw-43 patch, isFutureDate, isCurrentDate
- apparently we were attempting a date diff off of a string... whoops
...
sw-43

fix(rhsmTransformers): sw-43 patch isFutureDate, isCurrentDate

---

src/services/rhsm/rhsmTransformers.js

Environment sync, beta to stage stable
1. **rhsmTransformers** sw-43 patch isFutureDate, isCurrentDate (#963) (7581c2a)

Environment Sync, Beta to Stable

---

src/components/i18n/__tests__/__snapshots__/i18nHelpers.test.js.snap
src/components/i18n/__tests__/i18nHelpers.test.js
src/components/i18n/i18nHelpers.js
src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingProvider.test.js.snap
src/components/toolbar/__tests__/__snapshots__/toolbarFieldSelectCategory.test.js.snap
src/config/__tests__/__snapshots__/product.openshiftContainer.test.js.snap
src/config/__tests__/__snapshots__/product.rhacs.test.js.snap
src/config/__tests__/__snapshots__/product.rhel.test.js.snap
src/config/__tests__/__snapshots__/product.rhods.test.js.snap
src/config/__tests__/__snapshots__/product.rhosak.test.js.snap

- fix(i18nHelpers): nested context strings
1. navigate through products and confirm strings display correctly
...
ongoing

fix(i18nHelpers): nested context strings

---

src/components/graphCard/graphCardContext.js

- fix(graphCardContext): sw-690 duplicate api calls
- we noticed duplicate api calls happening while navigating between RHEL architectures that had, at minimum already been navigated towards at least once, during testing for the CSS inventory height issue @mirekdlugosz 
- this is a non-blocking bug since we implemented a fallback at the service level way back when for another scenario... the fallback cancels duplicate api calls when they happen in quick sequence
1. navigate between all RHEL architectures
- wait 10 seconds for the expanding cache to bust
- re-navigate between RHEL architectures and confirm that subsequent API calls fall below an average of `8`... the …

fix(graphCardContext): sw-690 duplicate api calls

---

src/config/product.rhel.js

- refactor(config): sw-106 rhel, enable category sort
- api corrected/allows category sort now, reactivate. #1038 we disabled it due to an incorrect/partial api response
1. confirm sorting for category in RHEL instances inventory active, and works on UI (API response to be tested)
...
sw-106
sw-235
related #1038

refactor(config): sw-106 rhel, enable category sort

---

src/config/product.rhel.js

- refactor(config): sw-820 rhel, enable sockets sort
1. navigate towards RHEL product view and
- confirm sorting for Instances inventory is active (and works) for the Sockets column
...
sw-820
relates sw-106

refactor(config): sw-820 rhel, enable sockets sort

---

.travis.yml

sw-625 temp build mod

---

package.json

chore(build): relax fallback check

---

src/components/router/router.js

- fix(router): sw-625 consistent keys
...
sw-625
#1052

fix(router): sw-625 consistent keys

---

.travis/custom_release.sh

- chore(prod): routing patch
- routing patch
- See PR #1085 for steps
...
sw-625
related #1085 1085

chore(prod): routing patch

---

README.md

- chore(build): build status badge
- travis altered their badge path, sure it'll change again
- look at the README, is the build status badge working or not =)
...
ongoing

chore(build): build status badge

---

src/components/chart/__tests__/__snapshots__/chart.test.js.snap
src/components/chart/chart.js
src/hooks/__tests__/useWindow.test.js
src/hooks/useWindow.js

- fix(chart,useWindow): conflicting ids, timing
- updating NPM packages for the build updates revealed this issue, #1100 
- removes an old issue with conflicting ids from charts, now that charts can be displayed multiple times, also helps with the resize observer
- minor dom render/timing issue corrected. the blend of the resize observer and react state can lead to funky behavior, the old skool settimeout is aimed at the blend of js and async react
1. confirm the graph display renders as expected
1. confirm the graph display renders as expected
...
ongoing
blocks #1103

1 of 3 - fix(chart,useWindow): conflicting ids, timing

---

src/common/README.md
src/common/__tests__/helpers.test.js
src/common/helpers.js
src/components/graphCard/graphCardMetricTotals.js
src/styles/_usage-graph.scss

- refactor(graphCard): sw-922 flex styling for metric cards
- refactor(graphCardMetricTotals): sw-922 meta-data for callbacks
- base for RHEL/Satellite and OpenShift Container metric card displays, partially falls under sw-747 and sw-748
- allows up to 4 cards to the left of a product graph, row one has 1 card, row two can have up to 3 cards
- prep for passing even more data to the metric card config callbacks in prep for "remaining capacity" 
related #1120 
related sw-747, sw-748
sw-922

refactor(graphCard): sw-922 flex styling for metric cards

---

CONTRIBUTING.md
README.md
config/cspell.config.json

- docs(readme,contributing): sw-817 process and workflow
- Process, maintenance, and development workflows
1. confirm spelling checks pass
...
sw-817

docs(readme,contributing): sw-817 process and workflow

---

.github/workflows/pull_request.yml
src/config/__tests__/__snapshots__/product.openshiftDedicated.test.js.snap
src/config/__tests__/__snapshots__/product.openshiftMetrics.test.js.snap
src/config/product.openshiftDedicated.js
src/config/product.openshiftMetrics.js

* **deps** codecov/codecov-action from 3.1.3 to 3.1.4  ([#1130](https://github.com/RedHatInsights/curiosity-frontend/pull/1130)) ([b2db304](https://github.com/RedHatInsights/curiosity-frontend/commit/b2db30446d4d0dc859bb4d4d7061e5d61876e4fc))
* **config** sw-1335 openshift on-demand inventory links  ([#1131](https://github.com/RedHatInsights/curiosity-frontend/pull/1131)) ([88b9a6c](https://github.com/RedHatInsights/curiosity-frontend/commit/88b9a6cc4f807cadad48e5f42e2a14da22021213))

Environment sync, beta/preview to stable

---

src/components/README.md
src/components/graphCard/__tests__/__snapshots__/graphCardHelpers.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardMetricTotals.test.js.snap
src/components/graphCard/__tests__/graphCardHelpers.test.js
src/components/graphCard/graphCardHelpers.js
src/components/graphCard/graphCardMetricTotals.js
src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
src/config/__tests__/product.openshiftDedicated.test.js
src/config/__tests__/product.openshiftMetrics.test.js
src/config/__tests__/product.rhacs.test.js
src/config/__tests__/product.rhods.test.js
src/config/__tests__/product.rhosak.test.js
src/config/product.openshiftDedicated.js
src/config/product.openshiftMetrics.js
src/config/product.rhacs.js
src/config/product.rhods.js
src/config/product.rhosak.js
src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap
src/services/rhsm/rhsmConstants.js

- feat(graphCardHelpers): sw-922 capacity, overage helpers
- moves the remaining metric card hard coded displays for daily/monthly totals into a set of helpers, along with newer overage and capacity helpers.
- there should be no visual changes associated with this update
- this affects ALL metric card displays
- RHODS
- RHACS
- OpenShift metrics
- OpenShift Dedicated metrics
- and the deprecated RHOSAK display
1. confirm the metric card displays for all related products behave as intended
- RHODS
- RHACS
- OpenShift metrics
- OpenShift Dedicated metrics
- and the deprecated RHOSAK display
1. make sure …

feat(graphCardHelpers): sw-922 capacity, overage helpers

---

Jenkinsfile

Adding a POC for a frontend's pr check for ephemeral testing, building, and deploying.

build(release): checking env vars

---

config/webpack.dev.config.js
config/webpack.proxy.config.js

part of [RHCLOUD-25607](https://issues.redhat.com/browse/RHCLOUD-25607) . Need to change AppUrl in each of the subscriptions apps to be /subscriptions/ instead of /insights/subscriptions/

add url for new subs bundle

---

config/webpack.prod.config.js
scripts/pre.sh

* **build** sw-1647 deployment env variable  ([#1180](https://github.com/cdcabrera/curiosity-frontend/pull/1180)) ([89d98aa](https://github.com/cdcabrera/curiosity-frontend/commit/89d98aa22b52955dfca16680c4f9620233ba9900))

Environment sync, preview to stable

---

CONTRIBUTING.md
config/cspell.config.json

- docs(contributing): sw-1792 update release steps
1. confirm the release steps reflect the addition of adding a hash to the `clowder` configuration
...
sw-1792

docs(contributing): sw-1792 update release steps

---

scripts/actions.commit.js
scripts/readme.docs.js
src/config/README.md
src/config/product.openshiftContainer.js
src/config/product.openshiftDedicated.js
src/config/product.openshiftMetrics.js
src/config/product.rhacs.js
src/config/product.rhel.js
src/config/product.rhods.js
src/config/product.rosa.js
src/config/product.satellite.js
src/config/products.js
src/config/routes.js
tests/__snapshots__/code.test.js.snap

- docs(config): allow generated readme
- exposes the generated documentation for product configuration
...
ongoing

docs(config): allow generated readme

---

src/styles/standalone.scss

- fix(styling): sw-1689 local run mock layout
- local development nice to have
1. confirm the styling for the mock header is the related patternfly v5 color
...
related sw-1689

fix(styling): sw-1689 local run mock layout

---

package.json

- build(eslint): add lintfix script
- convenience script for editors that may not have access to eslint
- it's also possible to run `$  yarn test:lint --fix` and achieve the same result
1. alter some level of code that is normally linted, like code comment line lengths, or line lengths in general
1. `$ yarn test:lintfix`
1. confirm the comment/code is reformatted to the previous format
...
ongoing

build(eslint): add lintfix script

---

.eslintrc
src/components/inventoryCard/inventoryCardHelpers.js
src/components/inventoryGuests/inventoryGuests.js
src/services/README.md
src/services/common/__tests__/serviceConfig.test.js
src/services/rhsm/rhsmServices.js

- build(eslint): multiline comment style
- there is 1 expected warning as a result of this update... it's why we made this eslint rule a warning instead of an error. There are times when linting shouldn't prevent the build from compiling (actually quite a few)... comments are one of those. We'll continue to investigate better implementations of this rule
...
ongoing

build(eslint): multiline comment style

---

scripts/actions.commit.js

- build(actions): commit syntax update
- applies an updated version of the commit messaging github action
- partially pulled from our work on https://github.com/quipucords/quipucords-ui/blob/main/scripts/actions.commit.js
...
ongoing

build(actions): commit syntax update

---

package.json

- build(webpack): sw-1781 switch to custom preloader
- local run patch, apparently missed 
1. confirm local run starts up and can be navigated, filtered
...
sw-1781

build(webpack): sw-1781 switch to custom preloader

---

src/styles/_table.scss

- fix(table): sw-2322 allow selectable links
- minor styling adjustment to override pf and "button link" "user-select:none"
1. navigate towards a product instances inventory display under subs ui
- attempt to select the link copy under the "name" column. if you can select it, it's working
sw-2322

fix(table): sw-2322 allow selectable links

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
deploy/build_deploy.sh
deploy/pr_check.sh
scripts/proxy.api.sh

- docs: clean up unused image, container references
- to avoid confusion, false positives, removing unused image, container terminology and scripting
- "[like using coke, cola, or pop to describe all soda...]" 
1. confirm the local proxy run continues to behave has expected
...
ongoing

docs: clean up unused image, container references

---

src/config/__tests__/__snapshots__/product.config.test.js.snap
src/config/product.rhacs.js
src/config/product.rhods.js
src/config/product.rosa.js

- fix(config): sw-2480 activate rosa instance_id
- previous work reverted #1313 this work activates the link for ROSA
...
related sw-2480

fix(config): sw-2480 activate rosa instance_id

---

scripts/actions.commit.js
src/redux/actions/__tests__/platformActions.test.js
src/redux/actions/__tests__/rhsmActions.test.js
src/redux/actions/__tests__/userActions.test.js
src/redux/middleware/index.js

- test: consistent redux createStore import
- minor adjustment to commit linting and issue numbers
...
ongoing, sw-2353

test: consistent redux createStore import

---

src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
src/components/toolbar/toolbarFieldExportContext.js
src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap
src/services/common/__tests__/serviceConfig.test.js
src/services/common/serviceConfig.js
tests/__snapshots__/code.test.js.snap

- refactor(serviceConfig): sw-2353 unified status response
- ~activates csv exports~
- ~minor refactors to help display csv loading status~
- minor incremental update
- minor refactors to simplify service config status
1. navigate to a product variant
- confirm export behaves as intended with JSON exports
- ~attempt to export a CSV file~
- ~wait for the pending and success toast notifications, your file should download~
- ~confirm the download is a zipped CSV file~
...
sw-2769 …

refactor(serviceConfig): sw-2353 unified status response

---

.github/workflows/integration.yml
CONTRIBUTING.md
scripts/pre.sh
src/common/README.md
src/common/helpers.js
src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap
src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap
src/components/toolbar/__tests__/toolbarFieldExportContext.test.js
src/components/toolbar/toolbarFieldExport.js
src/components/toolbar/toolbarFieldExportContext.js
src/redux/reducers/appReducer.js
src/services/platform/__tests__/__snapshots__/platformConstants.test.js.snap
src/services/platform/__tests__/__snapshots__/platformTransformers.test.js.snap
src/services/platform/__tests__/platformTransformers.test.js
src/services/platform/platformConstants.js
src/services/platform/platformTransformers.js

* **toolbarFieldExport** sw-2769 activate csv export ([#1373](https://github.com/RedHatInsights/curiosity-frontend/pull/1373)) ([1c75b07](https://github.com/RedHatInsights/curiosity-frontend/commit/1c75b07cea7a59a3e864adb1ce23cc51d5749f27))
*  sw-2778 deprecate, remove, clean preview-beta refs ([#1376](https://github.com/RedHatInsights/curiosity-frontend/pull/1376)) ([a8a82b7](https://github.com/RedHatInsights/curiosity-frontend/commit/a8a82b7df0e282a2e8eb6ed8c355325f13e1e34d))
* **platformTransformers** sw-2769 add format to export filename ([#1375](https://github.com/RedHatInsights/curiosity-frontend/pull/1375)) ([d65965f](https://github.com/RedHatInsights/curiosity-frontend/commit/d65965fa5f28058b1ab28a5925c416af1af1b586))

Release prep

---

.github/workflows/commit_lint.yml
.github/workflows/documentation_lint.yml
.github/workflows/integration.yml
README.md
package-lock.json
package.json

- build: nodejs 18 to 20
- move engine check to nodejs 20
- compare/contrast to last year when we moved from nodejs 16 to 18. (for when we go to adjust in march/may and aug/sept of 2025)
- this time around...
- there are more NPM packages that appear to be regulating their min engine version
- a few packages are automatically adjusting nodejs 18 towards whatever the most recent patch is
- a few packages are opting to completely forgo 18 support   
- no 2 packages seem to adhere to any type of regular update schedule unless they happen to be part of mono-repos. this creates a "constant monitoring" aspect that is frustrating
- quite a few packages are following "proper" semver releases when dropping/moving/adjusting nodejs support
- the constant adjusting of min nodejs engine adjustments, …

build: nodejs 18 to 20

---

.github/CODEOWNERS

- build: add codeowners, pr reviews
- more and more bots... more PRs and minor to zero observance of style guides
...
ongoing

build: add codeowners, pr reviews

---

.github/renovate.json

Add a renovate config per https://docs.renovatebot.com/configuration-templates/ & https://docs.renovatebot.com/configuration-options/ to allow for customization of the konflux automated dependency & other PRs

build: Add renovate config

---

.github/renovate.json

- build: renovate requests and commits
...
ongoing

build: renovate requests and commits

---

src/components/README.md
src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardChart.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardMetricTotals.test.js.snap
src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap
src/components/inventoryGuests/__tests__/__snapshots__/inventoryGuests.test.js.snap
src/components/loader/loader.js
src/components/messageView/messageView.js

- refactor(loader,messageView): sw-2707 remove deprecated react
- removes default props and types
...
sw-2707

refactor(loader,messageView): sw-2707 remove deprecated react

---

src/components/README.md
src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardChart.test.js.snap
src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap
src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap
src/components/minHeight/minHeight.js
src/components/optinView/optinView.js

- refactor(minHeight,optinView): sw-2707 remove deprecated react
- removes default props and types
sw-2707

refactor(minHeight,optinView): sw-2707 remove deprecated react

---

src/components/README.md
src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap
src/components/inventoryGuests/__tests__/__snapshots__/inventoryGuests.test.js.snap
src/components/table/__tests__/__snapshots__/table.test.js.snap
src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap
src/components/table/table.js

- refactor(table): sw-2707 remove deprecated react
1. next...
...
sw-2707

refactor(table): sw-2707 remove deprecated react

---

src/components/README.md
src/components/loader/__tests__/__snapshots__/loader.test.js.snap
src/components/table/__tests__/__snapshots__/tableEmpty.test.js.snap
src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap
src/components/table/tableEmpty.js
src/components/table/tableSkeleton.js

- refactor(tableEmpty,skeleton): sw-2707 remove deprecated react
...
sw-2707

refactor(tableEmpty,skeleton): sw-2707 remove deprecated react

---

src/AppEntry.js
src/README.md
src/app.js

- refactor(app): sw-2707 remove deprecated react
...
sw-2707

refactor(app): sw-2707 remove deprecated react

---

src/components/README.md
src/components/form/__tests__/__snapshots__/checkbox.test.js.snap
src/components/form/checkbox.js

- refactor(checkbox): sw-2707 remove deprecated react
...
sw-2707

refactor(checkbox): sw-2707 remove deprecated react

---

src/components/README.md
src/components/productView/__tests__/__snapshots__/productView.test.js.snap
src/components/toolbar/toolbar.js

- refactor(toolbar): sw-2707 remove deprecated react
- remove prop types and replace default props
...
sw-2707

refactor(toolbar): sw-2707 remove deprecated react

---

src/components/README.md
src/components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap
src/components/tooltip/tooltip.js
src/config/__tests__/__snapshots__/product.config.test.js.snap

- refactor(tooltip): sw-2707 remove deprecated react
- remove proptypes and replace default props
...
sw-2707

refactor(tooltip): sw-2707 remove deprecated react

---

src/components/README.md
src/components/inventoryTabs/__tests__/__snapshots__/inventoryTabs.test.js.snap
src/components/tabs/__tests__/__snapshots__/tabs.test.js.snap
src/components/tabs/tabs.js

- refactor(tabs): sw-2707 remove deprecated react
- remove proptypes, replace default props
...
sw-2707

refactor(tabs): sw-2707 remove deprecated react

---

src/components/README.md
src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardChart.test.js.snap
src/components/graphCard/__tests__/__snapshots__/graphCardChartTooltip.test.js.snap
src/components/graphCard/graphCard.js
src/components/graphCard/graphCardChart.js
src/components/graphCard/graphCardChartLegend.js
src/components/graphCard/graphCardChartTitleTooltip.js
src/components/graphCard/graphCardChartTooltip.js
src/components/graphCard/graphCardMetricTotals.js
src/components/productView/__tests__/__snapshots__/productView.test.js.snap

- refactor(graphCard): sw-2707 remove deprecated react
- remove proptypes, replace default props
...
sw-2707

refactor(graphCard): sw-2707 remove deprecated react

---

.github/dependabot.yml

- build(deps): dependabot frequency, ignored deps, group names
adjust dependabot 
- frequency
- ignored dependency list
- adjust/shorten group names to avoid cluttering the commit message
...
ongoing

build(deps): dependabot frequency, ignored deps, group names

---

CHANGELOG.md
package-lock.json
package.json

- chore(release): 4.14.2
...
ongoing

Release commit

---

config/jest.setupTests.js
package-lock.json
package.json
src/components/chart/chartAxisLabel.js

- build(deps): sw-2707 remove unused prop-types
- clean up package ref
...
related sw-2707

build(deps): sw-2707 remove unused prop-types

---

CHANGELOG.md
package-lock.json
package.json

- chore(release): 4.14.3
- confirm changelog commits align with `stable` branch
ongoing

chore(release): 4.14.3

---

CHANGELOG.md
package-lock.json
package.json

- chore(release): 4.14.4
- confirm changelog commits align with `stable` branch
ongoing

chore(release): 4.14.4

---

src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap
src/components/graphCard/graphCardChartLegend.js
src/components/toolbar/__tests__/__snapshots__/toolbarFieldCategory.test.js.snap
src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap
src/components/toolbar/__tests__/toolbarFieldBillingProvider.test.js
src/components/toolbar/__tests__/toolbarFieldDisplayName.test.js
src/components/toolbar/__tests__/toolbarFieldGranularity.test.js
src/components/toolbar/__tests__/toolbarFieldRangedMonthly.test.js
src/components/toolbar/__tests__/toolbarFieldSelectCategory.test.js
src/components/toolbar/__tests__/toolbarFieldSla.test.js
src/components/toolbar/__tests__/toolbarFieldUsage.test.js
src/components/toolbar/toolbarFieldBillingProvider.js
src/components/toolbar/toolbarFieldCategory.js
src/components/toolbar/toolbarFieldDisplayName.js
src/components/toolbar/toolbarFieldGranularity.js
src/components/toolbar/toolbarFieldGroupVariant.js
src/components/toolbar/toolbarFieldRangedMonthly.js
src/components/toolbar/toolbarFieldSelectCategory.js
src/components/toolbar/toolbarFieldSla.js
src/components/toolbar/toolbarFieldUsage.js
src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap
src/redux/reducers/__tests__/viewReducer.test.js
src/redux/reducers/viewReducer.js

- fix(toolbarFields): sw-3443 state refs from view to productId
- move the state refs from broad group identifiers to the specific variant/product identifier. this helps remove the indirect state updates that cause group related variants from re-firing their API calls
1. select either RHEL or OpenShit product displays (we tested with OpenShift AI and RHACS)
- select a toolbar filter that generates a toolbar token
- wait 20 seconds
- select a different variant
- confirm that API calls only reference the current product variant and NOT the previous variant
1. select either RHEL or OpenShit product displays (we tested …

fix(toolbarFields): sw-3443 state refs from view to productId

---

src/components/README.md
src/components/productView/productViewContext.js
src/components/toolbar/toolbarFieldCategory.js
src/components/toolbar/toolbarFieldExport.js
src/components/toolbar/toolbarFieldGroupVariant.js

- docs(productView,toolbarFields): sw-95 consistent annotations
- refactor(toolbarFieldCategory): options hook, move to useMemo
- minor annotations
- minor useMemo adjustment to field category filter generally found in RHEL product displays
1. navigate to the RHEL product view
- select the category type filter
- select one of the available options and confirm the graph and inventory displays reload with the category type filter
1. navigate to the RHEL product view
- select the category type filter
- select one of the …

docs(productView,toolbarFields): sw-95 consistent annotations

---

CHANGELOG.md
package-lock.json
package.json

- chore(release): 4.15.0
- confirm commit hashes align in changelog
...
ongoing

chore(release): 4.15.0

---

CHANGELOG.md
package-lock.json
package.json

- chore(release): 4.16.0
ongoing

chore(release): 4.16.0

---

deploy/pr_check.sh

swatch-3764 - ci.int.devshift.net pipelines
- update deploy components to get a more consistent bonfire deploy.
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1262
- fixes the ephemeral tests
...

ci: sw-3764 fix ci.int.devshift.net
