RedHatInsights/curiosity-frontend

.gitignore, package.json, scripts/openapi.docs.js, yarn.lock
- feat(api docs): issues/17 local run open api spec
* local run api documentation
* minor fix for standalone npm script
This test currently only works if you directly create the open api spec from RHSM. If/when it does function the test...
1. `$ yarn api:docs`
...
updates #17
=> feat(api docs): issues/17 local run open api spec

package.json, scripts/proxy.api.sh
- fix(build): issues/16 separate out hosts update
* minor tweak for first time users and host setup
- this script is targeted at first time users, typically associated with our design side
1. open a terminal instance, then
1. `$ yarn api:proxy-hosts` or `$ yarn start:proxy`
If you've already set everything you should see terminal output that contains
> ...
> Checking https://github.com/RedHatInsights/insights-proxy.git ...SUCCESS
>Hosts already up-to-date
> [api:dev  ] $ ...
If this is your first time running everything you should see terminal output that contains the below, you may be prompted to allow access to the `hosts` file
> ...
> Checking https://github.com/RedHatInsights/insights-proxy.git ...SUCCESS
> Updating hosts... you may need to "allow write access"...
> Adding …
=> fix(build): issues/16 separate out hosts update

public/locales/en.json, src/common/__tests__/__snapshots__/dateHelpers.test.js.snap, src/common/__tests__/__snapshots__/graphHelpers.test.js.snap, src/common/__tests__/dateHelpers.test.js, src/common/__tests__/graphHelpers.test.js, src/common/dateHelpers.js, src/common/graphHelpers.js, src/common/index.js, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/__tests__/rhelGraphCard.test.js, src/components/rhelGraphCard/rhelGraphCard.js, src/services/rhelServices.js, src/styles/_usage-graph.scss, tests/__snapshots__/i18n.test.js.snap
* parse the Redux date and sockets inputs and generate chart data and
tooltips
* add error state and zeroed array
* loading state
Outstanding question - should a max-y value be set for non error state?
Loading desktop:
Loading mobile:
Loading complete:
Error state (zeroed array), max-y set to 100, toast notification to come in future PR... : 
Closes #18
=> feat(chartGraph): convert graph data, add error/loading states

public/locales/en.json, src/common/__tests__/__snapshots__/graphHelpers.test.js.snap, src/common/__tests__/graphHelpers.test.js, src/common/graphHelpers.js, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/rhelGraphCard.js, tests/__snapshots__/i18n.test.js.snap
* provide a custom y domain if the data array is missing
* fill missing or partial data arrays with zero values
* refactor convertGraphUsageData to return chartDomain
* update tests accordingly
Related Victory issues for y-domain problem:
https://github.com/FormidableLabs/victory/issues/883
https://github.com/FormidableLabs/victory-docs/pull/559/files
Open question and potential edge case - what should the y-domain max be set to if all y values are the same? This poses the problem noted in Victory above. We currently set the y max value to 100 if we are in the error state and passing a zeroed array, however the same exact display issue can happen if all y values are the same (ex. : { x: 'Jun 1' y: 0 } , { x: 'Jun 2' y: 0 } , { x: 'Jun 3' y: 0 }, ... } )
Zeroed array (and no data) will now …
=> feat(rhelGraphCard): partial data and empty array domain

.eslintrc, src/common/__tests__/__snapshots__/graphHelpers.test.js.snap, src/common/__tests__/graphHelpers.test.js, src/common/graphHelpers.js, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap
Set the y-domain according the max y value in the input data...
Related Victory issues:
FormidableLabs/victory#883
https://github.com/FormidableLabs/victory-docs/pull/559/files
Targets a current edge case where all y values are the same causing the issue noted in Victory charts.
Example data which found this edge case:
```
{
"data":[
{
"date":"2019-07-25T18:00:09.56Z",
"instance_count":0,
"cores":0,
"sockets":0
},
{
"date":"2019-07-26T00:00:00.696Z",
"instance_count":0,
"cores":0,
"sockets":0
}
],
"links":{
"first":"/api/rhsm-subscriptions/v1/tally/products/RHEL?granularity=daily&beginning=2019-06-26T00:00:00.000Z&ending=2019-07-26T23:59:59.999Z&offset=0",
"last":"/api/rhsm-subscriptions/v1/tally/products/RHEL?granularity=daily&beginning=2019-06-26T00:00:00.000Z&ending=2019-07-26T23:59:59. …
```
=> fix(chart): set y domain appropriately

src/components/router/__tests__/__snapshots__/router.test.js.snap, src/components/router/router.js, src/services/__tests__/config.test.js, src/services/config.js
- fix(services, router): remove unused auth header func 
* services config, clean up
* router, redirect route adjust
...
Updates #34
=> Service config clean up, Minor Routing update

CONTRIBUTING.md, src/common/dateHelpers.js
- feat(build): issues/52 default date time override
* build, dotenv default date time override
- this is a convenience debugging update related to design and demo
1. create a `.env.local` file in the root of the project, place this line in there, or whatever date you want
```
REACT_APP_DEBUG_DEFAULT_DATETIME=20190625
```
2. run `$ yarn start`, the date should override the default starting date display for the graph
3. stop everything, now run `$ yarn test`, no unit test snapshots should require updating, unit tests are hardcoded to use the date `20190720`.
4. after running the tests check the proxy run `$ yarn start:proxy`. the default date should be the current date and the graph should display accordingly
Updates #52
=> feat(build): issues/52 default date time override

.env, public/index.html, src/common/__tests__/__snapshots__/helpers.test.js.snap, src/common/helpers.js, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/router/__tests__/__snapshots__/router.test.js.snap, src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap, src/components/router/__tests__/routerTypes.test.js, src/components/router/routerTypes.js, tests/__snapshots__/html.test.js.snap
- fix(build, routerTypes): issues/34 dynamic routing baseName
* build, dotenv path prefix
* build, html template add in lang attribute from dotenv
* routerTypes, create a dynamic routing baseName
- it looks like we were missing the "dynamic baseName" implementation that shifts the routing. it was causing the GUI/app to redirect towards the original baseName
1. confirm the route is coming through and being redirected towards a `rhel` route
1. to check the dynamic functionality add additional path names and confirm they're still being directed to a final `rhel` path
- `http://localhost:3000/lorem/ipsum/dolor/sit` …
=> fix(build, routerTypes): issues/34 dynamic routing baseName

src/common/__tests__/__snapshots__/graphHelpers.test.js.snap, src/common/graphHelpers.js, src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/chartArea.js, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/rhelGraphCard.js, src/styles/_app.scss, src/styles/_common.scss, src/styles/_usage-graph.scss, src/styles/index.scss, tests/__snapshots__/i18n.test.js.snap
- fix(graphHelpers,chartArea): quarters granularity display
* graphHelpers, quarters granularity in moment
* chartArea, added label overlap
* rhelGraphCard, label overlap
* styling, min-width for main view around graph displays
- after the "thirdlies" incident, actually show quarters =)
1. select the "quarters" granularity selection from the GUI dropdown, it should render like the below examples
fixes #6 and #88
=> fix(graphHelpers,chartArea): quarters granularity display

public/locales/en-US.json, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/rhelGraphCard.js, tests/__snapshots__/i18n.test.js.snap
- fix(rhelGraphCard): issues/93 remove the word daily
1. you should be able to visually confirm the removal of the word "daily"
Closes #93
=> fix(rhelGraphCard): issues/93 remove the word daily

config/spandx.config.js
- fix(build): issues/95 proxy domain updated
1. GUI and resources should display as normal. Any errors would be an indication the path update has failed
...
closes #95
=> fix(build): issues/95 proxy domain updated

src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/__tests__/chartArea.test.js, src/components/chartArea/chartArea.js
- fix(chartArea): issues/103 y axis domain minimum
1.  next the graph should display with a y axis minimum range of 10 instead of the current/older display of `1,1,2,2`. For comparison logging into CI/Dev or QA can be used, where said environments should render the current/older display.
closes #103
=> fix(chartArea): issues/103 y axis domain minimum

package.json, src/index.js, src/redux/actions/rhelActions.js, src/redux/middleware/index.js, src/redux/reducers/index.js, src/styles/index.scss, yarn.lock
- feat(notifications): issues/11 activate toast notifications
* build, platform notifications package
* index, add notifications component
* rhelActions, notifications metadata
* middleware, notifications options-settings
* redux reducers, notifications reducer
* scss, notifications stylesheet
- @bclarhk added as related to the UX of when and how notifications display
- toast notifications are currently only activated around RHSM/Tally API failures, and anything additional the platform component may, or may not, add. If there are additional notification areas desired we can activate them as necessary
As of 20191002 COB the RHSM API response is throwing errors, if this is happening at the time of review a proxy run can be used to confirm results
1. …
=> feat(notifications): issues/11 activate toast notifications

src/components/chartArea/__tests__/chartArea.test.js, src/components/chartArea/chartArea.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/rhelGraphCard.js
- fix(chartArea): issues/79 streamline on multiple data facets
* chartArea, allow multiple data facets as prep for hypervisor
* rhelGraphCard, update towards chartArea props update
* tests, chartArea, i18n and rhelGraphCard tweak
- This is a incremental update while the GUI is converted towards displaying the Hypervisor aspect of the RHSM API properties.
1. No visual changes should be detectable. And no console errors should be present
1. No visual changes should be detectable. And no console errors should be present
...
Updates #79
=> fix(chartArea): issues/79 streamline on multiple data facets

src/components/rhelGraphCard/rhelGraphCard.js, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/redux/selectors/__tests__/graphCardSelectors.test.js, src/redux/selectors/graphCardSelectors.js
- fix(graphCardSelectors): confirm granularity loaded correctly
* additional check to avoid loading prior cache
* tests, expand and update selector
- Appears as a caching issue, where the cache is a step behind the granularity dropdown selection. Initial loads are fine. This adds an additional check to confirm the granularity has been updated, and now runs all Redux for the graph card through Reselect.
1. Select `Monthly` granularity from the dropdown, then reselect `Daily` granularity, then reselect `Monthly`. Monthly should update the x axis ticks as a confirmation the data has loaded correctly and not the previous cached chart data.
...
Relates to #79
=> fix(graphCardSelectors): confirm granularity loaded correctly

src/common/__tests__/__snapshots__/dateHelpers.test.js.snap, src/common/dateHelpers.js, src/redux/reducers/__tests__/__snapshots__/rhelGraphReducer.test.js.snap, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap
- fix(dateHelpers): end of day adjustment for display
1. once you log in and are able to see data you should no longer see a "data dive" before the largest x axis value, see below screenshots
ongoing
=> fix(dateHelpers): end of day adjustment for display

public/locales/en-US.json, src/components/rhelGraphCard/__tests__/__snapshots__/rhelGraphCard.test.js.snap, src/components/rhelGraphCard/rhelGraphCard.js
- fix(i18n): issues/146 update system label copy
- fix(rhelGraphCard): issues/148 subtle color adjustment
- The color adjustment only affects the `400` level color to `300`. Keeping `100` on the fill. Adjusting fill opacity wasn't accounted for in favor of preset color themes from Patternfly React Tokens
1. view the graph/chart and associated labels
1. view the graph/chart and associated labels
closes #146 #148
=> Copy and design updates

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap, src/components/tourView/tourView.js, src/redux/actions/rhelActions.js
- fix(rhelActions,tourView): issues/133 disable toast notifications
* rhelActions, disable toasts until API provides auth endpoint
* tourView, anchor tag ref attribute
- This change disables all error toast notifications from appearing for the `tally` and `capacity` endpoints. The notifications partially interfere with the display and general intent of "redirecting" the user to the guided tour/learn more view.
- This notification change can be reverted if/when the API provides an `auth` endpoint the GUI can access **before** trying to load the `tally` and `capacity` endpoints.
Updates #133
=> fix(rhelActions,tourView): issues/133 disable toast notifications

src/components/tourView/__tests__/__snapshots__/tourView.test.js.snap, src/components/tourView/tourView.js
- fix(tourView): issues/133 generic learn more link
- The current link is not incorrect, this is a simple adjustment that aligns the left nav "Documentation" link and "Learn more" links by using the same generic documentation redirect.
- https://github.com/RedHatInsights/insights-chrome/commit/06d0349cf7351fd53fbb5f292bae882b5f7ae558
1. navigate towards the route `/soon` and click the "Learn more" link. It should now redirect towards `https://access.redhat.com/documentation/Subscription_Central/`
...
Relates to #133 #153 
@rblackbu
=> fix(tourView): issues/133 generic learn more link

src/components/i18n/__tests__/i18n.test.js, src/components/i18n/i18n.js
- fix(i18n): correct locale load sequence
* minor race condition apparent after package updates
- The issue is exposed as a warning on local and proxy level development prior to this update.
- A side effect of this update is `locale` should be one of the very first things that you'll see in the Redux state layer.
Before you update your local create a branch based of of `upstream/ci`  and run through a `$ yarn start` with the  browser console open, the React warning should be displayed. Once you see that then...
1. `$ yarn start` make sure the browser dev console is open
1. And confirm the warning is no longer present. 
-->
#159
=> fix(i18n): issues/159 correct locale load sequence

.eslintrc, src/redux/actions/__tests__/__snapshots__/platformActions.test.js.snap, src/redux/actions/__tests__/platformActions.test.js, src/redux/actions/__tests__/rhsmActions.test.js, src/redux/actions/platformActions.js, src/services/__tests__/__snapshots__/platformServices.test.js.snap, src/services/__tests__/__snapshots__/userServices.test.js.snap, src/services/__tests__/platformServices.test.js, src/services/__tests__/rhsmServices.test.js, src/services/__tests__/userServices.test.js, src/services/config.js, src/services/platformServices.js, src/services/userServices.js, src/setupTests.js
- fix(platformServices,userServices): issues/43 centralize globals
* build, lint promise reject errors
* build, setupTests, apply platform global mock
* platformServices, restructure getUser, navigation methods
* userServices, restructure authorizeUser
* config, use platformService instead of emulated response
* platformActions, allow nav methods to return unlistener responses
- Updates issue #43 based on CI/dev testing
- Applies state broadcasts within Redux for platform global method calls
- Corrects how the `setNavigation` and `onNavigation` wrappers pass `un-listeners` back
- Aligns more closely with the platform's ask regarding calling `getUser` on every API call. Part of the goal was to help avoid some of the sensitivity around the modal redirect. 
- @jeperry per discussion
1. …
=> fix(platformServices,userServices): issues/43 centralize globals

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap, src/components/router/__tests__/routerHelpers.test.js, src/components/router/__tests__/routerTypes.test.js, src/components/router/router.js, src/components/router/routerHelpers.js, src/components/router/routerTypes.js
- fix(platformServices): issues/179 platform app name
* authentication, appName, history push event, use routerHelpers
* router, refine to get specific navigation details
* routerHelpers, expand to accept navigation ID
* routerTypes, add appName type
- This is a two part fix.
1. The first part is this PR. Merging the GUI half first should not create/generate issues and is a behind the scenes update.
1. The second part involves updating the "source of truth" platform config. The specific change is making sure the `group: subscriptions` setting is applied to the `subscriptions` sub-apps
1. Confirm that no additional console errors, beyond the missing app name and minified …
=> fix(platformServices): issues/179 platform app name

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/redux/selectors/__tests__/graphCardSelectors.test.js, src/redux/selectors/graphCardSelectors.js
- fix(graphCardSelectors): issues/176 graph error blur
* graphCardSelectors, granularity check against api response times
* graphCard, apply key to aid reload, i18n snapshot
- Appears a selector check and API response times fill out the other part of #176 
- Prior to this fix the error blur would appear when making the granularity switch quickly. We tried a resolution around certain redirect/authentication scenarios (#184 ) but this currently has the appearance of playing a minor part.
- The fallback check for catching said error is still in place. The condition check for applying granularity from multiple sources has been updated to make more of an allowance for variation in API response times and focus on helping push the cached version of the response out instead of an immediate error …
=> fix(graphCardSelectors): issues/176 graph error blur

src/components/chartArea/chartArea.js, src/components/graphCard/__tests__/__snapshots__/graphCardHelpers.test.js.snap, src/components/graphCard/graphCard.js, src/components/graphCard/graphCardHelpers.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/redux/selectors/graphCardSelectors.js
- fix(graphCardSelectors): issues/185 apply response schemas
* chartArea, allow null values to bypass y-axis prop isRequired
* graphCard, threshold locale id check
* graphCardHelpers, threshold locale check
* graphCardSelectors, apply schemas to generate graph data
* openshiftView, thresholdCores filterGraphData
* rhelView, thresholdSockets filterGraphData
- No visual updates, behind the scenes
- Applies a basic API schema map, of expected properties, to the Tally/Reporting and Capacity responses.
- Relaxed the "isRequired" prop check on the Chart component y-axis. Should allow null values to pass without generating an error
1. confirm...
- no errors are generated beyond …
=> fix(graphCardSelectors): issues/185 apply response schemas

public/locales/en-US.json, src/components/graphCard/graphCard.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js
- feat(openshiftView): issues/185 add cores sockets selector
* locales, add generic cardHeading string
* graphCard, allow children to populate card actions
* openshiftView, add cores sockets select list for graph filtering
* rhelView, code style consistency against openshiftView
1. log in with a user that has related data
1. navigate to the Openshift path and confirm the select list filters the displayed graph data
...
Close #185
=> feat(openshiftView): issues/185 add cores sockets selector

src/services/__tests__/__snapshots__/userServices.test.js.snap, src/services/__tests__/userServices.test.js, src/services/userServices.js
- fix(userServices): issues/43 catch empty response objects
* expand generic auth response check, object and has keys
- Catches a scenario where the original user data response check would pass a valid empty object.
1. Log into CI/QA with a malformed user that returns an empty object response (typically associated with a lacking account number)
1. Navigate to the Subscription Watch app
1. You should be redirected towards the "Tour View"
...
Updates #43
=> fix(userServices): issues/43 catch empty response objects

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/__tests__/graphCard.test.js, src/components/graphCard/graphCard.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap, src/redux/reducers/__tests__/__snapshots__/graphReducer.test.js.snap, src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap, src/redux/reducers/__tests__/graphReducer.test.js, src/redux/reducers/__tests__/viewReducer.test.js, src/redux/reducers/graphReducer.js, src/redux/reducers/viewReducer.js, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/redux/selectors/__tests__/graphCardSelectors.test.js, src/redux/selectors/graphCardSelectors.js
- fix(graphCardSelectors): improve sync for multiple api calls
* graphCard, require graphGranularity, relocate granularity to parent
* graphCardSelectors, improve sync for multi api calls, aggregation
* graphReducer, viewReducer, relocate granularity
* i18n, test update
* openShiftView, rhelView, relocate granularity
* routerHelpers, routerTypes, test updates
- Improves the sync graph display behavior when handling aggregated API calls. There is currently a scenario when one API call is significantly slower it can delay loading in various ways, such as causing the graph to display empty, then load after the fact. This set of updates aims to remove that, and reverts to the cached graph display more easily
1. Currently their is a 2 …
=> fix(graphCardSelectors): improve sync for multiple api calls

.travis/custom_release.sh, CONTRIBUTING.md, config/spandx.config.js, scripts/pre.sh, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/routerHelpers.test.js, tests/__snapshots__/platform.test.js.snap
- fix(routerHelpers): issues/218 dynamic base name tests
* in addition to beta path, include root path checks
- chore(build): issues/218 apply stable deploy paths
* pre script, minor local variable rename to avoid confusion
* proxy run, stable path additions for spandx config, local run
* custom release, beta and stable branches for ci, qa, prod
- After this change merges, **AND ANY OTHER EXISTING PR MERGES**, the following git level actions need to take place i.e. #221 
- It should be noted that a `prod-stable` update will not happen until these changes are merged into `master` branch
...
Updates #218
=> chore(build): issues/218 apply stable deploy paths

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/services/rhsmServices.js, src/types/__tests__/__snapshots__/rhsmApiTypes.test.js.snap, src/types/rhsmApiTypes.js
- feat(rhelView): issues/226 display cloud metering data
* i18, public cloud string
* rhelView, filter for cloud meter sockets
* rhsmServices, mock for cloud meter properties
* rhsmApiTypes, add cloud meter types
Confirmation is needed on:
- `chart_color_purple_100`
- `chart_color_purple_300`
- `cloud_sockets`
- CONFIRMED
- CONFIRMED
- MOSTLY confirmed
1. You should see something similar to the attached screenshot below.
Updates #226 
@rblackbu
=> feat(rhelView): issues/226 display cloud metering data

CONTRIBUTING.md, public/locales/en-US.json, src/common/helpers.js, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/i18n/i18n.js, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/messageView/messageView.js, src/services/platformServices.js
- fix(platformServices): issue/240 admin API debugging behavior
- fix(authentication,messageView): auth empty state 
* authentication, update auth empty state
* messageView, add pageTitle prop
- feat(i18n): issues/240 expose translating a node 
* helpers, noopTranslate
* i18n, add node translate, annotations
- Support additions for #240 
#240
=> Issues/240 - Platform services debugging, auth empty state, and translate a node

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/__tests__/authentication.test.js, src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/optinView/__tests__/optinView.test.js
- fix(authentication,optinView): issues/240 expand unit tests
- Baseline opt-in tests
- Expanded to include authenticaton
...
#240
=> fix(authentication,optinView): issues/240 expand unit tests

public/locales/en-US.json, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/__tests__/authentication.test.js, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/optinView/__tests__/optinView.test.js, src/components/optinView/optinView.js
- fix(authentication,optinView): issues/240 optin for all users 
* authentication, remove admin session checks
* optinView, remove admin session checks
* locale, strings updated
- Removes the org-admin checks. All users should now see the same thing
- A 403 from the RHSM API should trigger the "opt-in"
- A 401 from the RHSM API will trigger an unauthenticated view/message
- PR #247 Gives the original logic breakdown
1. navigate towards http://localhost:3000/optin
1. next, submit the form a confirmation screen similar to the below screenshot should appear
#240
=> fix(authentication,optinView): issues/240 optin for all users

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/__snapshots__/routerTypes.test.js.snap, src/components/router/routerTypes.js
- fix(authentication, routerTypes): revert nav clean up
* authentication, restore part of #245 setNavigation clean up
* routerTypes, restore navigation titles for setNavigation
- Reverts parts of the clean up for navigation from #245 
1. once the browser is loaded open a blank tab/window and enter the following url, `https://cloud.redhat.com/beta/subscriptions/` upon navigating the browser should redirect to `https://cloud.redhat.com/beta/subscriptions/rhel-sw/all` and the left nav should expand
- this behavior will apply to the stable path once deployed
...
updates #262
=> fix(authentication, routerTypes): revert nav clean up

src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/optinView/__tests__/optinView.test.js, src/components/optinView/optinView.js
fix(optinView): issues/240 assume opt-in is activated
* optinView, simplify check for 403 status
- minor logic simplify
- missing state ref
...
Relates #240
=> fix(optinView): issues/240 assume opt-in is activated

package.json, scripts/proxy.api.sh
- fix(build): issues/274 squash browsersync console messages
* build, proxy run port updated
- This commit should be squashed with the prior PR #276 
- Appears the spandx port needed to be updated as well, this squashes the browsersync messages that appear in dev console
1. **BEFORE YOU START** do NOT sync with this PR, sync with the upstream CI branch
- update the NPM packages with `$ yarn`
- run `$ yarn start:proxy`
- Confirm the above screenshot matches the browser dev console messaging you're seeing
1. next, stop the proxy
1. **NOW SYNC** with this PR,
- update the NPM packages with `$ yarn`
- `$ yarn start:proxy`
- Confirm the console messaging for browsersync no longer clutters the browser dev console
...
- Relates to PR #276 
- …
=> fix(build): issues/274 squash browsersync console messages

src/components/graphCard/__tests__/__snapshots__/graphCardHelpers.test.js.snap, src/components/graphCard/graphCardHelpers.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
- fix(graphCardHelpers): issues/273 tooltip date ranges
* graphCardHelpers, tooltip date ranges for week, quarter granularity
1. select the weekly or quarterly granularity, then hover over the graph to view the date ranges
#273 
@rblackbu
=> fix(graphCardHelpers): issues/273 tooltip date ranges

scripts/dev.chrome.sh
- chore(build): local run dev chrome, hide broken nav icon
Hides broken left nav icon
Ongoing
=> chore(build): local run dev chrome, hide broken nav icon

.eslintrc, package.json, public/locales/en-US.json, src/components/c3Chart/__tests__/__snapshots__/c3Chart.test.js.snap, src/components/c3Chart/__tests__/c3Chart.test.js, src/components/c3Chart/c3Chart.js, src/components/c3GraphCard/c3GraphCard.js, src/components/c3GraphCard/c3GraphCardHelpers.js, src/components/c3GraphCard/c3GraphCardLegendItem.js, src/components/c3GraphCard/tests/__snapshots__/c3GraphCard.test.js.snap, src/components/c3GraphCard/tests/__snapshots__/c3GraphCardHelpers.test.js.snap, src/components/c3GraphCard/tests/__snapshots__/c3GraphCardLegendItem.test.js.snap, src/components/c3GraphCard/tests/c3GraphCard.test.js, src/components/c3GraphCard/tests/c3GraphCardHelpers.test.js, src/components/c3GraphCard/tests/c3GraphCardLegendItem.test.js, src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/__tests__/graphCard.test.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/__tests__/openshiftView.test.js, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/__tests__/rhelView.test.js, src/components/rhelView/rhelView.js, src/services/rhsmServices.js, src/setupTests.js, src/styles/_common.scss, src/styles/_usage-graph.scss, yarn.lock
- fix(graphCard): issues/283 expand unit tests
- feat(c3Chart): issues/283 add base c3 component 
* c3Chart, adds a c3 wrapper component, initial tests
- feat(c3GraphCard): issues/283 add card, display data 
* c3GraphCard, add card wrapper for c3, display api data
* c3GraphCardHelpers, c3 config generator, maintain prior card helpers
* c3GraphCardLegendItem, custom chart legend item
* i18n, placeholder legend tooltip strings
* rhsmServices, update API mocks for local dev, random response
* styling, adjustments to match pf victory charts styling
- feat(rhelView,openshiftView): issues/283 activate c3
* rhelView, c3 charting, tooltip enhancements via query-string
* openshiftView, c3 charting, tooltip enhancements via query-string
- The goal is performance and feature related testing within …
=> feat(c3Chart): issues/283 add base c3 component 

src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/__tests__/chartArea.test.js, src/components/chartArea/chartArea.js, src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/graphCard/__tests__/graphCardChartLegend.test.js, src/components/graphCard/graphCard.js, src/components/graphCard/graphCardChartLegend.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/redux/reducers/__tests__/__snapshots__/graphReducer.test.js.snap, src/redux/reducers/__tests__/graphReducer.test.js, src/redux/reducers/graphReducer.js, src/redux/types/__tests__/__snapshots__/index.test.js.snap, src/redux/types/graphTypes.js, src/redux/types/index.js, src/styles/_usage-graph.scss
- feat(chartArea,graphCard): issues/283 interactive legend
* chartArea, expose chart methods for interactivity, redraw
* graphCard, pass chart methods to legend
* graphCardChartLegend, apply redux state, add button click
* graphReducer, apply legend toggle state
* reduxTypes, graphTypes, set legend type
* styling, allow button color
- Gives the ability for a user to turn legend data facets on/off while updating the y axis domain.
- Adds the ability to maintain the legend data facet toggles while switching granularity, this can also be added to the proof of concept c3 work.
- The custom legend works around Victory as started in #298 and utilizes JS callback structure to redraw the graph instead of trying to utilize Victory's event structure. 
- The drawback to this appears to be a limit on …
=> feat(chartArea,graphCard): issues/283 interactive legend

src/redux/selectors/__tests__/__snapshots__/userSelectors.test.js.snap, src/redux/selectors/__tests__/userSelectors.test.js, src/redux/selectors/userSelectors.js
- fix(userSelectors): issues/307 missing error check
* userSelectors, missing error check, check for global errors
- The issue appears as a sequence of events, originally the global error check was last and able to override the sequence. Moving the reducer check for authorization to last broke this sequence. This fix aims to allow either sequence to work by applying a consistent "error" check to authorization.
- Unit test snapshot has been applied to avoid this issue in the future
1. login with the standard environment user
1. delete the optin via the browser console by typing:
- `curiosity.userServices.deleteAccountOptIn()`
- hit enter
- refresh the page, the user should …
=> fix(userSelectors): issues/307 missing error check

package.json, src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/__tests__/chartArea.test.js, src/components/chartArea/chartArea.js, yarn.lock
- fix(build,chartArea): npm update for victory charts
* chartArea, label attribute fix, note
- behind the scenes update, there should be no change in functionality
1. confirm tests pass
1. confirm the GUI loads
1. confirm the GUI loads
1. confirm output compiles and tests pass
...
Ongoing, #296
=> fix(build,chartArea): npm update for victory charts

src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/chartArea.js
- fix(chartArea): issues/318 inaccurate voronoi x coords
* chartArea, large resized graph widths throw inaccurate voronoi x coords
- The issue only manifests when the graph is extended beyond a certain width. User display sizes as noted in #318 are a factor, the exact cause remains unknown due to time constraints and scope creep.
- This patch affects, slightly, the positioning associated with the tooltip following the graph cursor position
1. select the "weekly" granularity, or **select another granularity other than "daily"**
- hover over slowly along the graph horizontally noting that each tooltip represents the corresponding x axis tick
Updates #318
=> fix(chartArea): issues/318 inaccurate voronoi x coords

src/components/loader/loader.js, src/components/router/redirect.js
- fix(redirect): issues/328 lazy load routing 
- redirect, apply suspense for lazy loaded redirect route
- fix(loader): issues/328 loading component 
- loader, resource path consistency
- These commits will be squashed into the commits from PR #337 once QE approves
1. login with credentials
1. delete the users/account optin
1. refresh the page, it should render the optin view accordingly
...
Closes #328 
Updates #342
=> fix(redirect): issues/328 lazy load routing

tests/__snapshots__/code.test.js.snap, tests/code.test.js
- fix(testing): add general code tests, lost console methods
- Behind the scenes, no visual aspect beyond CI logging
- This test opens up applying general global code checks
- We've relaxed the linter checks around console.log. This re-applies a global level check for console methods. 
1. Dist level tests should complete
...
Ongoing
=> fix(testing): add general code tests, lost console methods

public/locales/en-US.json, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/__tests__/pageHeader.test.js, src/components/pageLayout/pageHeader.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js
- feat(rhelView, openshiftView): issues/305 add sub heading
- add applicable subheading to rhelView
- add applicable subheading to openshiftView
PageHeader was refactored to accept an explicit title prop and/or a block of content to include below the title.  Other views using this component should all have been updated if needed.
1. Visit `/openshift-sw` and confirm subheading text is correct and associated link works
1. Visit `/rhel-sw/all` and confirm subheading text is correct and associated link works
https://github.com/RedHatInsights/curiosity-frontend/issues/305
=> feat(rhelView, openshiftView): issues/305 add sub heading

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/authentication.js, src/components/c3GraphCard/c3GraphCard.js, src/components/graphCard/graphCard.js, src/components/graphCard/graphCardChartLegend.js, src/components/graphCard/graphCardChartTooltip.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/i18n/i18n.js, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/optinView/optinView.js, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/pageHeader.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap, src/components/table/table.js, src/components/table/tableSkeleton.js, src/components/toolbar/toolbar.js, src/redux/index.js
- fix(i18n,translate): issues/354 remove withTranslation
* i18n, replace withTranslation new HOC, use direct translate function
* redux, remove withTranslation convenience HOCs
- Behind the scenes updates, there should be no visual difference regarding copy
- This converts the use of the "t" function to now include the ability to replace tokens giving us the ability to use components in them. This makes use of existing functionality, gives consistency in behavior by reorganizing and cleaning up how the "t" function functions
- Updates the "translateComponent" method to be a replacement for "withTranslation" in the event we need a Higher Order Component in the future
1. make sure Docker is …
=> fix(i18n,translate): issues/354 remove withTranslation

tests/commit.test.js
- fix(testing): commit message length
- apply an arbitrary/adjustable commit message length check, currently 65 char
- this test only runs in CI
...
Ongoing
=> fix(testing): commit message length

src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/__tests__/toolbar.test.js, src/components/toolbar/toolbar.js
fix(toolbar): issues/10 default usage filter category
* toolbar, default filter category, soft filter reset
- Toolbar filters start the initial view with the "usage" category selected
- "Clearing all" filters leaves the last selected category visually active
- The default category can be easily updated in the future
@rblackbu 
1. observe the initial starting filter category is usage, see attached screenshot
Updates #10
=> fix(toolbar): issues/10 default usage filter category

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/pageLayout/pageHeader.js
- fix(pageHeader): update subheading external link icon
- pageHeader, update external link icon from ExternalLinkSquareAltIcon to ExternalLinkAltIcon
1. visit `/rhel-sw/all` and confirm the link icon in the header is correct
Updates #367
=> fix(pageHeader): update subheading external link icon

src/styles/_tour.scss, src/styles/index.scss
- chore(tourView): issues/359 remove vestigial tour stylesheet
- tourView, remove associated stylesheet for previously removed component
1. click around app to confirm nothing looks off
Updates #359
=> chore(tourView): issues/359 remove vestigial tour stylesheet

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/pageHeader.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/table/__tests__/__snapshots__/table.test.js.snap, src/components/table/table.js
- fix(pageHeader): issues/305 apply locale product context
* locale, i18n, appName, product context strings
* openshiftView, rhelView, apply appName, product context
* pageHeader, appName param, product context
* table, apply appName clean up
- behind the scenes optimization
...
updates #305
updates #10
=> fix(pageHeader): issues/305 apply locale product context

src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/__tests__/chartArea.test.js, src/components/chartArea/chartArea.js, src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js
- fix(graphCard,chartArea): issues/365 increase stroke width
Instead of updating colors, I've increased the stroke width.  I updated the primary stroke width from 1 (default) to 2.  I also updated the dashed line stroke width from 2.5 to 3, so that it would still be visibly thicker than the other lines.
Updates #365
=> fix(graphCard,chartArea): issues/365 increase stroke width

src/components/pagination/__tests__/__snapshots__/pagination.test.js.snap, src/components/pagination/__tests__/pagination.test.js, src/components/pagination/pagination.js, src/services/rhsmServices.js
- fix(pagination): issues/400 page reset on limit update
- chore(rhsmServices): expand system inventory mock
- expanded mocks, update mock dates for rhsm subscription endpoints. 
- **DEVELOPMENT** - if you utilize a local run "date override" within a `.env.local` file it would be good to verify that date falls within the months of July/August/Sept 2020 or later/future. Otherwise even more "odd" displays may appear. Code will still function
Steps to reproduce bug, an error should be throw and the GUI displays an error state
1. Locate an account with over 10 inventory listings
1. navigate to the last offset/page with the paging controls
1. select to increase the paging display limit
1. `$ yarn …
=> fix(pagination): issues/400 page reset on limit update

src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/pagination/__tests__/__snapshots__/pagination.test.js.snap, src/components/pagination/pagination.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/__tests__/toolbar.test.js, src/components/toolbar/toolbar.js
- fix(toolbar): issues/400 page reset on filter update
* openshiftView, rhelView, pass productId to toolbar
* toolbar, reset page on filter selection and clear
- Reset the paging offset when a user updates the primary toolbar filters, includes clearing them
Steps to reproduce bug, an error should be throw and the GUI displays an error state
1. Locate an account with over 10 inventory listings
1. navigate to the last offset/page with the paging controls
1. select a filter from the primary toolbar that will reduce the inventory results
1. perform the same steps as the Env check, confirm no error is thrown
...
#400
=> fix(toolbar): issues/400 page reset on filter update

package.json, yarn.lock
- chore(build): npm update for react scripts
- As noted in the React Scripts changelog this is an "audit" only update. Dependabot, in our case, doesn't make a distinction around "devDependencies" vs "dependencies", or even the compiled end-result
...
Ongoing
=> chore(build): npm update for react scripts

.github/workflows/pull_request.yml, .travis/custom_release.sh
- chore(build): activate GitHub workflow for PRs
- Once this is merged it is important that we disable the "pull request" Travis checks. If we need to back this workflow out we can simply reactivate the Travis "pull request" check and remove the workflow
- Possible, appears we may need to leave the "pull request" Travis check running until this change is merged all the way up. However, we can make Travis "NOT required" on any branch where the GitHub workflow is. Travis will run, just as an add on until it can be worked completely out.
Running unit tests in Travis seems to be getting increasingly slower with each new test. This is an attempt to remove Pull Requests from Travis and move those confirmations into GitHub. 
We will still be using the same Travis scripts to compile the GUI, and …
=> chore(build): activate GitHub workflow for PRs

.github/workflows/pull_request.yml
- ~chore(build): commit depth for GitHub workflow PRs~
- chore(build): full error annotations for GitHub workflow PRs
- ~Expands the number of commits available for the commit lint test currently embedded in the integration tests.~ This appears to be a non-issue if #432 is merged.
- Exposes the error annotations so the logs do not have to be opened. It appears `stderr` for test output is limited... not useful unless it's also combined with the output from `stdout`
- Once tested this will be squashed into the commit from  #427
Once this is merged
1. rebase your PR against the CI branch
1. open a PR against CI, there should be a "checks" tab on GitHub PRs
1. the new workflow should be visible as "Pull request"
...
Ongoing, #275 #427
=> chore(build): full error annotations for GitHub workflow PRs

.github/workflows/pull_request.yml
- chore(build): cache for GitHub workflow PRs
- This will be squashed into #434 #427
- ~This only caches the yarn cache, NOT the node_modules directory which would contain the `bin` and hence aliases. As a future update we can look at caching the node_modules, For now we've gained an additional `25 sec` averaged reduction in CI runtime~
- A slight modification to the `path: ${{ steps.yarn-cache-dir.outputs.CACHE_DIR }}` towards `path: ${{ github.workspace }}/node_modules ` may work
- This reduces the average runtime by over a minute...
Once this is merged
1. rebase your PR against the CI branch
1. open a PR against CI, there should be a "checks" tab on GitHub PRs
1. the new workflow should be visible as "Pull request"
...
Ongoing, #275 #427 #434
=> chore(build): cache for GitHub workflow PRs

.github/workflows/pull_request.yml
- chore(build): expanded cache for GitHub workflow PRs
- This will be squashed into #434 #427 #435
- This type of caching appears to help with running multiple node versions
Once this is merged
1. rebase your PR against the CI branch
1. open a PR against CI, there should be a "checks" tab on GitHub PRs
1. the new workflow should be visible as "Pull request"
...
Ongoing, #275 #427 #434 #435
=> chore(build): expanded cache for GitHub workflow PRs

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/inventoryList.js, src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap, src/components/minHeight/__tests__/minHeight.test.js, src/components/minHeight/minHeight.js, src/styles/_usage-graph.scss
- feat(minHeight): issues/403 set min-height, avoid page jumps
- fix(inventoryList,graphCard): issues/403 set minheight on update
- Applies a minHeight component to help resolve API page load jumps
- Column shifts are a potential subsequent fix
1. login with an account that has numerous inventory items, then
1. navigate to the next page in the inventory list, the page should no longer shift in it's over all height
#403
=> fix(inventoryList,graphCard): issues/403 set minheight on update

.github/workflows/commit_lint.yml, .travis.yml
- chore(build): travis stages for specific branches
- chore(build): workflow for commits, deprecated set-env
- Coordinates CI against GitHub PR workflow. Once the GitHub workflows merge into master Travis will be limited to branch pushes only. This focuses Travis build stages to specific branches in order to avoid duplicated effort handled by GitHub workflows, and potentially unnecessary cycles since deploys are already branch specific.
- Replace deprecated env var "set" for GitHub workflow
- Confirm Travis stages have fired correctly for this PR. They should be
- Test
- Beta Deploy
...
Ongoing, #275
=> chore(build): travis stages for specific branches

.travis/custom_release.sh
- chore(build): travis limit prod release to specific message
- limit Travis prod-stable pushes to commit messages with Curiosity's standard release message `chore(release)`. This is prep for applying an automated release commit to the prod-stable based branch
- this is a first round, may be useful to also apply this to the stage branch eventually
...
Ongoing, #275
=> chore(build): travis limit prod release to specific message

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/inventoryList.js, src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap, src/components/minHeight/__tests__/minHeight.test.js, src/components/minHeight/minHeight.js
- fix(inventoryList): issues/403 adjust for expanded guestsList
* graphCard, remove default minHeight prop
* inventoryList, autoUpdate prop
* minHeight, flip autoUpdate, inner container height for reset
- re-adjusts minHeight for a "more pleasant" paging experience when expanding the guestsList inventory display. 
- Currently when a guestsList inventory is expanded that height is applied to the overall "min-height" causing subsequently paged inventory displays to maintain the expanded guestsList display height. This patch aids in a "reset" for said scenario
1. Locate an account with inventory and guests listings 
1. expand a guests lists inventory display
1. page to a …
=> fix(inventoryList): issues/403 adjust for expanded guestsList

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/inventoryList.js, src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap, src/components/minHeight/__tests__/minHeight.test.js, src/components/minHeight/minHeight.js
Environment sync
1. **inventoryList** issues/403 adjust for expanded guestsList (#460) (ab48375)
=> Environment Sync, Dev to Test

public/locales/en-US.json, src/components/openshiftView/openshiftView.js, src/components/rhelView/rhelView.js
- fix(locale): issues/389 virtual to virtualized string
- fix(openshiftView,rhelView): issues/414 inventory link path prefix
1. confirm hovered over the inventory link has the `/beta` prefix, it was missing before and caused a flip between beta and stable environments
1. confirm that the string "Virtual" is now displayed instead of the string key `curiosity-inventory.hardwareType`
#389 #414
=> Locale string update, issues/389 virtual to virtualized

public/locales/en-US.json, src/common/helpers.js, src/components/c3GraphCard/tests/__snapshots__/c3GraphCard.test.js.snap, src/components/c3GraphCard/tests/__snapshots__/c3GraphCardHelpers.test.js.snap, src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/graphCard/__tests__/__snapshots__/graphCardChartTooltips.test.js.snap, src/components/guestsList/__tests__/__snapshots__/guestsList.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/__tests__/__snapshots__/inventoryListHelpers.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/table/__tests__/__snapshots__/table.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarTypes.test.js.snap
- fix(openshiftView,rhelView): issues/468 header names
- fix(helpers,testing): noopTranslate, helpful test snapshots
- Header names, this is an iterative update aimed at expanding the helpfulness of the copy used for the headers
- `noopTranslate`, simple testing update to actually render out the JSON instead of displaying `[object Object]` in snapshots
1. Locate an account with "VMs", expand the section, the new "VM name" should display
#468 
relates #389
=> fix(openshiftView,rhelView): issues/468 header names

src/components/guestsList/__tests__/__snapshots__/guestsList.test.js.snap, src/components/guestsList/guestsList.js, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/__tests__/__snapshots__/inventoryListHelpers.test.js.snap, src/components/inventoryList/inventoryList.js, src/components/inventoryList/inventoryListHelpers.js, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/loader/loader.js, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/components/table/__tests__/__snapshots__/tableSkeleton.test.js.snap, src/components/table/__tests__/tableSkeleton.test.js, src/components/table/table.js, src/components/table/tableSkeleton.js, src/styles/_inventory-list.scss, src/styles/_table.scss
- feat(inventoryList,guestsList): issues/494 fixed column widths
- Adds the ability to set fixed inventory column widths through config
- Even though we're applying column widths there is still a potential shift in inventory paged displays that have/do not have expandable sections. The Patternfly expandable table rows add an additional table column that shift the view.
- Table skeleton should have fixed column widths applied too
- inventoryListHelpers changes are prep for #483 
1. confirm during paging of the inventory display that columns maintain their width in a consistent manner. 
#494 
relates #483
=> feat(inventoryList,guestsList): issues/494 fixed column widths

scripts/openapi.docs.js
- chore(build): issues/394 api main branch reference
1. `$ yarn api:docs`
1. the OpenApi/Swagger doc should be accessible at `http://localhost:5050/docs/api/`
...
#394
=> chore(build): issues/394 api main branch reference

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/__tests__/pageHeader.test.js, src/components/pageLayout/pageHeader.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, tests/__snapshots__/dist.test.js.snap
- feat(rhelView, openshiftView): issues/490 add "Take a tour" button
A hover effect was not possible on this type of button through Patternfly.  The text of the button has an extra "a" in it from what was shown in the mockup because I reused the text from the previously existing tour button.  Both of these details were approved by UX.
1. visit /beta/subscriptions/rhel-sw/all and /beta/subscriptions/openshift-sw
1. confirm presence of tour button on both pages
Updates #490
=> feat(rhelView, openshiftView): issues/490 add tour button

src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/__tests__/inventoryList.test.js, src/components/inventoryList/inventoryList.js, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js
- feat(inventoryList): issues/493 product disable guests setting
* inventoryList, hasGuests callback setting
* openshiftView, rhelView, apply basic inventoryList settings
- behind the scenes update, no visual changes
- applies a settings callback that replaces the `hasGuests` check in `inventoryList.js`
1. confirm that guests/VMs **are still expandable** when "guests/VMs are greater than zero" for a listing. there should be no errors present
1. if you wish to confirm the logic works, on one of the product views you can update the `initialInventorySettings` object with the following snippet, where the "greater than one" represents how many guests it takes to disable the …
=> feat(inventoryList): issues/493 product disable guests setting

public/locales/en-US.json, src/components/bannerMessages/bannerMessages.js, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/components/rhelView/rhelView.js, src/redux/selectors/__tests__/__snapshots__/appMessagesSelectors.test.js.snap, src/redux/selectors/appMessagesSelectors.js
- fix(bannerMessages): issues/511 copy update
- fix(bannerMessages): issues/511 apply query filter 
* bannerMessages, query updates for banner display
* openshiftView, rhelView, pass query to banner
* appMessageSelectors, query pass-through
- Applies the query filter to the banner. This in turn adds an additional API call that fires on filter update.
- The initial request was around the SLA filter... this should apply all graph related filters inclusive of UOM, and the exception of NO user applied granularity is set towards the banner message.
- Minor copy adjustment per UX
- @ntkathole 
1. log in with the appropriate account that has mismatched Cloud Meter data within …
=> fix(bannerMessages): issues/511 apply query filter 

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageSection.test.js.snap, src/components/pageLayout/pageSection.js, src/components/rhelView/__tests__/__snapshots__/rhelView.test.js.snap, src/styles/_page-layout.scss
- fix(tabs): issues/491 apply tabs background color
- Minor background fill. Apparently local proxy run versus the environments exposes some missing styles somewhere in our chain. It's unclear if this on the platform side or ours
1. log into the env
1. confirm the below screenshot "After Fix" matches the env display
#491
=> fix(tabs): issues/491 apply tabs background color

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/openshiftView/__tests__/__snapshots__/openshiftView.test.js.snap, src/components/openshiftView/openshiftView.js
- perf(openshiftView): issues/407 update uom field
* openshiftView, replace uom field with independent comp
- Updating towards displayName filtering highlighted optimizations around using Redux hooks and existing components. This is a set of updates in prep for displayName and a possible toolbar restructure.
1. navigate to the Openshift product
1. select the UMO options and confirm the graph and inventory update accordingly, without error
...
#407 
Relates #476
=> perf(openshiftView): issues/407 update uom field

src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/inventoryList.js, src/styles/_inventory-list.scss
- feat(inventoryList): issues/476 activate display name search
- accessibility keys are active, esc clears the search, hitting return/enter on the submit button activates the search
1. log in
1. scroll down to the hosts inventory display and perform a display name search on an existing display name, a filtered list should return and display
https://user-images.githubusercontent.com/3761375/105062188-5418f900-5a48-11eb-9cba-aa51971170a5.mp4
#476
=> feat(inventoryList): issues/476 activate display name search

src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/__tests__/inventoryList.test.js, src/components/inventoryList/inventoryList.js, src/components/inventorySubscriptions/__tests__/__snapshots__/inventorySubscriptions.test.js.snap, src/components/inventorySubscriptions/__tests__/inventorySubscriptions.test.js, src/components/inventorySubscriptions/inventorySubscriptions.js, src/components/pagination/__tests__/__snapshots__/pagination.test.js.snap, src/components/pagination/pagination.js, src/styles/_fade.scss
- fix(inventoryList): issues/476 hide field on zero results
- fix(inventoryList): consistent hide, aria-hidden attributes 
* inventoryList, subsInventoryList, consistent hide, aria-hidden
* pagination, consistent hide, aria-hidden
- minor UX adjustment, hide the display name search when there are no results
1. log in with an account known to have zero results for one of its host inventory displays
1. upon see no results confirm the display name field is hidden
#476
=> fix(inventoryList): issues/476 hide field on zero results

src/components/form/__tests__/__snapshots__/checkbox.test.js.snap, src/components/form/__tests__/__snapshots__/formHelpers.test.js.snap, src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/__tests__/formHelpers.test.js, src/components/form/checkbox.js, src/components/form/formHelpers.js, src/components/form/textInput.js, src/components/inventoryList/__tests__/__snapshots__/inventoryList.test.js.snap, src/components/inventoryList/inventoryList.js, src/components/inventorySubscriptions/__tests__/__snapshots__/inventorySubscriptions.test.js.snap, src/components/inventorySubscriptions/inventorySubscriptions.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/__tests__/toolbarFieldDisplayName.test.js, src/components/toolbar/toolbarFieldDisplayName.js
- fix(inventoryList): issues/476 show field on zero results
- fix(toolbarFieldDisplayName): issues/476 allow enter submit
- based on UX/design feedback reactivates the display name field. accounts for scenarios in which zero results normally hides "paging". the new behavior is to now display paging and the display name field when there are "zero" results
- enables a user to use the enter/return key to submit the display name field
- have a question around the paging disabled state, do we want to remove the grey disabled color? @bclarhk @rblackbu 
1. login with an account having a hosts inventory
1. navigate to a RHEL architecture and enter a display name search that …
=> fix(inventoryList): issues/476 show field on zero results

src/components/form/textInput.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/toolbarFieldDisplayName.js, src/styles/_tabs.scss
- fix(textInput,toolbarFieldDisplayName): issues/476 clean up, extra props
- fix(style): remove focus outline style for tab content
1. log in and confirm the tab focus outline is no longer visible on the hosts inventory display by
- either tabbing through the interface
- or click next to, around, the display name field
Relates to #476
=> issues/476 displayname field, remove tab content focus outline

src/components/toolbar/toolbarFieldDisplayName.js
- fix(toolbarFieldDisplayName): issues/559 remove min char check
- This fix is related to those browsers that do not implement a clear for the html input type "search". The specific instance called out was around Firefox 78+/-
- We simply removed the min-character check that was set to prevent unneeded api calls based on the concept of the "search" type.
- It was noted that we might want to consider clearing this field along with the primary toolbar "clear all filters" since we do a general paging reset  @bclarhk @rblackbu . However, since "display name" doesn't appear in the primary toolbar list of filters it is recognized that may not be the best UX
1. login in, …
=> fix(toolbarFieldDisplayName): issues/559 remove min char check

src/redux/middleware/actionRecordMiddleware.js
- fix(actionRecordMiddleware): issues/52 limit and data adjustment
- Sanitize identifying user data, generic
- Correct the output limit for reporting, variable name correction
1. update the NPM packages with $ yarn
1. login and navigate to Subscription Watch
1. Open the browser dev console and type $ curiosity.debugLog(), hit enter and a JSON debug log should download. You may have to "allow" the download action.
- You should see a file with similar output to the below screenshot
#52
=> fix(actionRecordMiddleware): issues/52 limit and data adjustment

src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/checkbox.js, src/components/form/textInput.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/toolbar.js, src/components/toolbar/toolbarFieldDisplayName.js, src/redux/selectors/inventoryListSelectors.js, src/redux/selectors/subscriptionsListSelectors.js
- fix(toolbar): issues/541 state updates for filters
* toolbar, selector update, pull query directly
* toolbarFieldDisplayName, clear value with null
* inventoryListSelectors,subsListSelectors, selector update, viewId
- fix(checkbox,textInput): consistent name, id attributes
- This issue also affects the display name field, that fix is included. 
- It has to do with turning the productView component into a function. We were (and still are'ish) drilling the query prop through subsequent child components. Now the affected components receive the query state updates initially through config, then directly from state
1. log in and navigate to the Satellite views
- …
=> fix(toolbar): issues/541 state updates for filters (allow clear filters in Satellite)

src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/productView.js, src/redux/selectors/__tests__/__snapshots__/appMessagesSelectors.test.js.snap, src/redux/selectors/appMessagesSelectors.js
- fix(bannerMessages): issues/541 state updates for filters
* appMessagesSelectors, adjust pass query, update components
* productView, var/props name consistency
- Flipping to the functional component for Satellite product views highlighted a long running issue created when #518 was implemented. The intention of #518 was to update the query based on the primary toolbar queries, which currently encompasses both `Usage` and `SLA`. The other products, RHEL and OpenShift, were able to "work around" this issue because of the component structure and prop drilling, exposing a functional Satellite component, and removing aspects of the prop drill causes the Satellite product view to not update the banner message like the other products... this PR corrects that issue.
- @ntkathole 
1. update the …
=> fix(bannerMessages): issues/541 state updates for filters

src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/toolbarFieldDisplayName.js, src/redux/common/__tests__/__snapshots__/reduxHelpers.test.js.snap, src/redux/common/__tests__/reduxHelpers.test.js, src/redux/common/reduxHelpers.js
- fix(toolbarFieldDisplayName): issues/569 maxlength char limit
- fix(reduxHelpers): response message status range 
* reduxHelpers, avoid caching large responses on emulated 304
- applies a 255 maxlength character attribute to display name
- appears that parts of the platform name search also need to have this limit implemented, environment checked, ci
- Currently there is no design associated with "field validation" on the toolbar beyond toast notifications, @bclarhk @rblackbu 
1. login, navigate to Subs Watch, attempt to enter beyond 255 characters into the display name field. The field will automatically truncate the number of characters entered
...
#569
=> fix(toolbarFieldDisplayName): issues/569 maxlength char limit

src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/__tests__/textInput.test.js, src/components/form/textInput.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/__tests__/toolbarFieldDisplayName.test.js, src/components/toolbar/toolbarFieldDisplayName.js, src/services/rhsmServices.js, src/setupTests.js, src/styles/_form.scss, tests/__snapshots__/code.test.js.snap
- fix(toolbarFieldDisplayName): issues/476 search-as-type
* testing, mock for debounce
* textInput, emulate onClear for non-search types
* toolbarFieldDisplayName, debounce on keyup, style adjustment
* rhsmServices, adjust emulated API delays to reflect environments
- fix(i18n): consistent mock emulation
- applies a "search as you type" to the display name filter
- we use a similar 800 ms delay on the input field similar to the platform's inventory search. what this means is that there is a noticeable delay after typing. we can attempt to adjust this timer, but the current adjustment makes allowances for persons typing at varying speeds
1. login, navigate to Subs Watch, …
=> fix(toolbarFieldDisplayName): issues/476 search-as-type

config/cspell.config.json, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/pageHeader.test.js
- fix(pageHeader): ent-3533 check consistent html for Pendo
- renders the html output into a snapshot for future PF and platform component update diffs. Pendo is affected by a sensitive CCS selector regardless of having a dedicated CSS class name.
1. confirm all tests pass
...
ent-3533
=> fix(pageHeader): ent-3533 check consistent html for Pendo

src/components/pageLayout/__tests__/__snapshots__/pageColumns.test.js.snap, src/components/pageLayout/__tests__/pageColumns.test.js, src/components/pageLayout/pageColumns.js, src/styles/_page-layout.scss
- feat(pageColumns): ent-3504 allow page columns
- base page layout for columns
- no visible changes
- **this PR only provides the base component, it does not activate the 2 column view in OpenShift**
1. confirm tests complete without error
ent-3504
=> feat(pageColumns): ent-3504 allow page columns

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/toolbar.js
- fix(toolbar): ent-3490 clear filters copy updated
- Updates copy for toolbar filters clearing from "Clear all filters" towards "Reset filters"
1. login, navigate to Subs Watch, select a filter from the primary toolbar. the copy should now read "Reset filters"
#573
ent-3490
=> fix(toolbar): ent-3490 clear filters copy updated

package.json, scripts/dev.chrome.sh, src/components/guestsList/__tests__/__snapshots__/guestsList.test.js.snap, src/components/guestsList/guestsList.js, src/components/table/table.js
- fix(guestsList): column widths for loader
- fix(table): additional cell content type
- chore(build): patch local dev run, without proxy 
* build, chrome2 setup melts if browserslist malformed in package.json
- Chrome 2 updates are affected by a malformed package.json "browserlist" prop. We checked in the base browserlist setup from CRA and added an error message if the Chrome 2 build fails.
- In the future the Chrome may stop working entirely with our current setup. In that event we have a fallback solution of just using placeholder code along with the base platform styles
1. confirm tests pass
1. confirm integration tests pass
...
Ongoing
=> chore(build): patch local dev run, without proxy

src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productViewOpenShiftContainer.js
- fix(productViewOpenShiftContainer): ent-3607 config date range
- Minor configuration update towards the correct date range. We double checked OpenShift dedicated as well, that config appears to be correct.
- https://github.com/RedHatInsights/curiosity-frontend/blob/ci/src/components/productView/productViewOpenShiftDedicated.js#L66-L67
1. navigate towards `/subscriptions/openshift-sw` and confirm the date range is correct for the flexible graph x axis ticks
ent-3607
=> fix(productViewOpenShiftContainer): ent-3607 config date range

package.json, src/components/chartArea/__tests__/__snapshots__/chartArea.test.js.snap, src/components/chartArea/chartArea.js, src/redux/middleware/actionRecordMiddleware.js, yarn.lock
- fix(chartArea): ent-3601 tooltip hover and clipping, x-axis
- fix(actionRecordMiddleware): optional chaining for testing
- we switched to utilizing more of the PF React wrappers for Victory. 
- There is some quirky behavior around the x coordinate positioning for the tooltip that becomes more noticeable on the dual graph displays. The quirk appears as more space between the vertical cursor line and the left aligned tooltip in the far right graph. We'll need to address this issue in the future, but for now the benefits of non-clipped tooltips takes priority
1. navigate towards the new OpenShift Container Platform layout at `/beta/subscriptions/openshift-sw` and confirm …
=> fix(chartArea): ent-3601 tooltip hover and clipping, x-axis

src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productViewOpenShiftContainer.js
- fix(productViewOpenShiftContainer): ent-3509 core hours display
- Update for the OpenShift Container view, OpenShift dedicated is already active
- Dependent on #598 #597
- There is rounding involved when we fix the floats' places
1. confirm the core hours display for OpenShift Container Platform, within the inventory display, display 2 places
ent-3509
ent-3324
=> fix(productViewOpenShiftContainer): ent-3509 core hours display

src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap, src/components/toolbar/toolbarFieldGranularity.js
- fix(toolbarFieldGranularity): ent-3644 reset inventory offset
- resets inventory paging on granularity selection
- this reset will apply to all granularity selections across all products
- initial fix, still evaluating how best to capture this test, appearing as e2e or integration would be better suited since we do technically capture the state updates for inventory in unit tests already
1. confirm the inventory paging/offset is reset to the initial offset, in this case `0`.
...
ent-3644
=> fix(toolbarFieldGranularity): ent-3644 reset inventory offset

config/spandx.config.js, package.json, src/components/router/__tests__/routerHelpers.test.js, src/components/router/routerHelpers.js, tests/__snapshots__/platform.test.js.snap
- fix(routerHelpers): ent-3541 rhcloud-12690 alt for search, hash
* build, update proxy, spandx config to account for left nav changes
* routerHelpers, alt for location.href, use search and hash directly
- Related to https://github.com/RedHatInsights/cloud-services-config/pull/456
- Corrects the dependency on window.location.href and instead directly uses `hash` and `search`. There is a race like condition that happens where sometimes window.location.href is updated before the route shift, sometimes it isn't
- This update affects all product views, OpenShift and the future views for Satellite
1. Navigate to `/beta/insights/subscriptions/rhel-arm` or any RHEL facet other …
=> fix(routerHelpers): ent-3541 rhcloud-12690 alt for search, hash

src/components/router/__tests__/__snapshots__/routerConfig.test.js.snap, src/components/router/__tests__/routerConfig.test.js, src/components/router/routerConfig.js, src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldRangedMonthly.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldUom.test.js.snap, src/components/toolbar/toolbar.js, src/components/toolbar/toolbarFieldDisplayName.js, src/components/toolbar/toolbarFieldGranularity.js, src/components/toolbar/toolbarFieldRangedMonthly.js, src/components/toolbar/toolbarFieldUom.js, src/redux/reducers/viewReducer.js
- fix(viewReducer): ent-3644 productGroups for inventory reset
* routerConfig, productGroups, productIds grouped by viewIds
* toolbar, viewId to inventory reset
* toolbarFieldDisplayName, granularity, ranged, uom, apply viewId
* viewReducer, restructure reset to apply productGroups
- It appears we discovered a flaw/bug in how we reset the inventory displays. Originally we didn't have dual column displays so we would generically reset the inventory per view, this encompassed all productIds under a viewId. The dual column display created a scenario where we can't/shouldn't generically reset all inventory states. Now **when an inventory reset needs to happen it can no longer be generic, it has to be specific**. 
- There are two solutions we've reviewed
- #604 Go with what we know works and …
=> fix(viewReducer): ent-3644 productGroups for inventory reset

src/components/productView/__tests__/__snapshots__/productViewRhel.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewSatellite.test.js.snap, src/components/productView/productViewOpenShiftContainer.js, src/components/productView/productViewRhel.js, src/components/productView/productViewSatellite.js
- fix(productViews): ent-3509 remove target blank from links
- Removes the target blank from all product views; RHEL, OpenShift, and Satellite. This change is dependent on the left navigation updates.
1. confirm the inventory links, and guest inventory links no longer open for RHEL, OpenShift, and Satellite
...
relates ent-3509 ent-3506 ent-3324
=> fix(productViews): ent-3509 remove target blank from links

src/components/form/__tests__/__snapshots__/select.test.js.snap, src/components/form/__tests__/select.test.js, src/components/form/select.js, src/components/toolbar/__tests__/__snapshots__/toolbar.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldRangedMonthly.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldUom.test.js.snap, src/components/toolbar/toolbarFieldRangedMonthly.js, src/styles/_form.scss
- fix(toolbarFieldRangedMonthly): ent-3748 apply position right
* select, expand display options, allow up down and left right
* toolbarFieldRangedMonthly, apply position right
* style, position right for select components
- PF Select doesn't appear to have a position left/right. We repurposed the CSS from PF Dropdown and it appears to work!
1. open OpenShift Container or OpenShift Dedicated and confirm the monthly ranged dropdown now has its position flush right
ent-3748
=> fix(toolbarFieldRangedMonthly): ent-3748 apply position right

src/components/pageLayout/__tests__/__snapshots__/pageColumns.test.js.snap, src/components/pageLayout/pageColumns.js, src/redux/middleware/actionRecordMiddleware.js, src/styles/_inventory-list.scss, src/styles/_page-layout.scss
- fix(pageColumns): smaller screen size column widths
- fix(actionRecordMiddleware): expand sanitizeData
- Minor styling adjustment for the columns OpenShift display at smaller screen sizes
1. navigation towards `[env path]/subscriptions/openshift-container`, scale the browser to a smaller width, confirm the columns appear like the below screenshot
Ongoing
=> fix(pageColumns): smaller screen size column widths

src/styles/_page-layout.scss
- fix(pageColumns): maintain columns on granularity change
- Minor adjustment to maintain widths during granularity (or any dropdown/select change) that causes the loaders to display for inventory. Appears the minimum widths of the inventory were partially being set by content, this makes them consistently 100%
1. navigate towards the OpenShift Container product view and select any dropdown filter (we used granularity) and confirm the loading display maintains width at smaller screen sizes (< 560px)
...
Relates #617 #615
=> fix(pageColumns): maintain columns on granularity change

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftDedicated.test.js.snap, src/components/productView/__tests__/productViewOpenShiftContainer.test.js, src/components/productView/__tests__/productViewOpenShiftDedicated.test.js, src/components/productView/productViewOpenShiftContainer.js, src/components/productView/productViewOpenShiftDedicated.js
- fix(productView): low precision display for core hours used
- use numbro standalone
- @mirekdlugosz 
1. confirm the "core hours used" displays scenarios similar with
- 0.6K == 600
- 0.9K == 900
- 0.6M == 600K
- 0.9M == 900K
...
relates ent-3816
=> fix(productView): low precision display for core hours used

config/cspell.config.json, public/locales/en-US.json, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/pageLayout.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewMissing.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/__tests__/productViewMissing.test.js, src/components/productView/productViewMissing.js, src/components/router/__tests__/__snapshots__/router.test.js.snap, src/components/router/__tests__/__snapshots__/routerConfig.test.js.snap, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/routerConfig.test.js, src/components/router/__tests__/routerHelpers.test.js, src/components/router/routerConfig.js, src/components/router/routerHelpers.js, src/styles/_inventory-list.scss, src/styles/_page-layout.scss, src/styles/_product-view.scss, src/styles/index.scss, tests/__snapshots__/dist.test.js.snap
- feat(productViewMissing): apply a missing product view
* i18n, missing product view strings, product titles
* pageLayout, allow additional classNames
* routerConfig, fallback root route, add nav filter prop, isSearchable
* routerHelpers, basePath, consistency with baseName
* styling, add product view styling for missing view, clean up
- Utilizes the Curiosity navigation and routing config to display relevant product cards based on the individual directory/path facets within `window.pathname`
- Curiosity's attempt to match a path in the form of `/beta/insights/subscriptions` or `/rhel/subscriptions` or `/random-path/openshift/subscriptions` will attempt a match on each path/dir segment, ie. for...
- `/beta/insights/subscriptions` that would be "beta" and "insights", 
- …
=> feat(productViewMissing): ent-3753 missing product view

src/components/productView/productViewMissing.js, src/styles/_product-view.scss
- fix(productViewMissing): relax proptypes
- also corrects a minor box shadow issue
1. confirm the box shadow does NOT display below the product cards
Relates #630
=> fix(productViewMissing): relax proptypes

src/redux/selectors/userSelectors.js, src/types/__tests__/__snapshots__/index.test.js.snap, src/types/platformApiTypes.js
- fix(userSelectors): ent-3825 add report read permissions
* userSelectors, add check for report read
* platformApiTypes, report const
- adds the subscriptions report read permission
1. login with a user having the permissions "subscriptions" "reports" "read" perm, confirm the interface is accessible
...
ent-3825
=> fix(userSelectors): ent-3825 add report read permissions

src/components/form/select.js
- fix(select): env styling cache issue, manually set isPlain
- it appears there's a caching issue in the lower environments around some of the PF styles, this includes the select component. 
- The styling for select is reverting towards "isPlain" when Curiosity is viewed WITHOUT browser caching disabled in dev tools. When caching IS disabled Curiosity displays the correct select styling.
- this lack of "select" styling was noted by QE, @ntkathole @mirekdlugosz . this attempts to manually apply the styling
_**This is only reproducible in environment, QA/CI/Stage beta/stable**_
1. login into your preferred environment
1. confirm the select/dropdown lists for Curiosity display with a border
...
Ongoing
=> fix(select): env styling cache issue, manually set isPlain

src/components/form/__tests__/__snapshots__/select.test.js.snap, src/components/form/__tests__/select.test.js, src/components/form/select.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldRangedMonthly.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldUom.test.js.snap, src/components/toolbar/toolbarFieldDisplayName.js, src/components/toolbar/toolbarFieldGranularity.js, src/components/toolbar/toolbarFieldRangedMonthly.js, src/components/toolbar/toolbarFieldUom.js
- fix(select,toolbarFields): ent-3879 apply test attributes
* select, allow data- attributes
* toolbarFields, apply test attributes
- @mirekdlugosz the `data-test` attributes we apply are added after-the-fact, we may need to take page load into consideration
- the test attributes are as follows
- display name search = `data-test="toolbarFieldDisplayName"`
- granularity = `data-test="toolbarFieldGranularity"`
- ranged monthly (OpenShift On-demand) = `data-test="toolbarFieldRangeGranularity"`
- uom = `data-test="toolbarFieldUom"`
1. login and inspect the various elements for the `data-test` attribute
...
ent-3879
=> fix(select,toolbarFields): ent-3879 apply test attributes

package.json, public/locales/en-US.json, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/__tests__/authentication.test.js, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/router/__tests__/__snapshots__/redirect.test.js.snap, src/components/router/__tests__/__snapshots__/routerHelpers.test.js.snap, src/components/router/__tests__/redirect.test.js, src/components/router/redirect.js, src/components/router/router.js, src/components/router/routerHelpers.js, yarn.lock
- revert(testing): outside src import, unit test locale
- fix(redirect): ent-3916 route config, dynamic loading
- fix(authentication): remove test block
- rolls back the change of including locale as a dev dependency to avoid install caching at the local level... having to run install every time you update the locales is frustrating
- dynamic routing implementation overlooked how redirects are handled
1. log in with an account that needs to "optin", confirm the optin view displays accordingly
...
relates #679 #690 
ent-3916
=> fix(redirect): ent-3916 route config, dynamic loading

src/components/graphCard/__tests__/graphCard.test.js, src/components/graphCard/graphCard.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/productView/__tests__/productViewOpenShiftContainer.test.js, src/components/productView/__tests__/productViewOpenShiftDedicated.test.js, src/components/productView/productViewOpenShiftContainer.js, src/components/productView/productViewOpenShiftDedicated.js, src/redux/selectors/__tests__/__snapshots__/graphCardSelectors.test.js.snap, src/redux/selectors/graphCardSelectors.js, src/services/rhsmServices.js, src/types/__tests__/__snapshots__/index.test.js.snap, src/types/rhsmApiTypes.js
- fix(productView): ent-3888 use meta to display total core hours
* graphCard, pass meta for setting actions callback
* graphCardSelectors, pass normalized meta
* productView, OpenShiftContainer, Dedicated, total core hours
* rhsmServices, API mock
- passing the meta object to consuming components resulted in a page load "double jump" when the graph loaded. we ended up "assigning" the values instead of replacing them under the thinking the object was causing an update. We think we've resolved it, but something to keep an eye on @mirekdlugosz 
1. confirm the total core hours display is coming through on OpenShift Container, Dedicated On Demand
...
ent-3888
=> fix(productView): ent-3888 use meta to display total core hours

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/i18n/i18n.js
- fix(i18n): allow multi-context
- minor allowance for an array/list of contexts
1. confirm tests pass
...
ongoing
=> fix(i18n): allow multi-context

src/components/chart/chart.js, src/components/chart/chartHelpers.js
- fix(chart,chartHelpers): ent-4064 correct dual axes normalize
- fixes the normalization that was supposed to happen, apparently we missed passing the multiple axes entirely
- corrects a future'ish problem where "truthy" values could fire an unintended condition
- the account used highlights a curious behavior in how normalized data can display... directly overlapped if the normalize percentages line up, @bclarhk @rblackbu @mirekdlugosz 
1. confirm the axes now align to their respective Y axis 
https://user-images.githubusercontent.com/3761375/124979089-a226b680-e000-11eb-8bb8-f1ab62738e1d.mp4
ent-4064
=> fix(chart,chartHelpers): ent-4064 correct dual axes normalize

public/locales/en-US.json, src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/graphCard/__tests__/graphCardChartLegend.test.js, src/components/graphCard/graphCard.js, src/components/graphCard/graphCardChartLegend.js, src/components/graphCard/graphCardChartTooltip.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
- fix(locales): ent-4045 threshold graph legend strings
* locale, threshold strings
* graphCard, pass productId
* graphCardChartLegend, productId context, string refs
* graphCardChartTooltip, string refs
1. confirm each product's graph legend tooltip for thresholds is displaying the corresponding string.
- Only 2 products should display specific strings for thresholds tooltips, RHEL and OpenShift Container. All other products should display a generic threshold tooltip string
ent-4045
=> fix(locales): ent-4045 threshold graph legend strings

src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/graphCard/graphCard.js, src/components/graphCard/graphCardChartLegend.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productViewOpenShiftContainer.js
- fix(locale): ent-4045 threshold graph legend strings
* graphCard, revert pass productId
* graphCardChartLegend, revert use productId context
* productViewOpenShiftContainer, productLabel to product like group
- Once this fix is confirmed by QE we'll squash it with the prior related commit @mirekdlugosz 
- Corrects the RHEL, and related architecture, tooltips falling back to the default threshold tooltip copy. This fix should still maintain OpenShift Container tooltip fixes
1. confirm the RHEL, and related architecture, tooltips reflect the correct copy
1. confirm the OpenShift Container tooltips reflect the correct copy
ent-4045
=> fix(locale): ent-4045 threshold graph legend strings

src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productViewOpenShiftContainer.js
- fix(productView): ent-4104 column views inventory reset
- it appears both products' inventory is affected, OpenShift Container and Metrics
1. on the OpenShift Container Platform dual column view a minimum of 11 or 21 or 51 or 101  entries is required to test this bug. Both product columns should be tested!
- adjust the paging to the desired per page limit
- move the inventory display to the last page
- adjust the granularity "like" dropdown, the inventory page and display should reset to the first page
ent-4104
=> fix(productView): ent-4104 column views inventory reset

src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/graphCard/graphCardChartLegend.js, src/styles/_inventory-list.scss
- fix(productView): ent-4108 column styling for inventory list overflow
- fix(graphCardChartLegend): ent-4109 tooltip for small screens
1. scale the browser width to around 1020px or less to confirm the inventory table no longer breaks out of the column for OpenShift Container
https://user-images.githubusercontent.com/3761375/125691433-79fd7215-45f1-4555-bdde-cbcc1f8ec582.mp4
ent-4108
ent-4109
=> fix(productView): ent-4108 column styling for inventory list overflow

src/components/guestsList/__tests__/__snapshots__/guestsList.test.js.snap, src/components/guestsList/guestsList.js, src/styles/_inventory-list.scss, src/styles/_usage-graph.scss
- fix(productView): ent-4108 guests toggle styling and inventory
- fix(graphCard): ent-3813 overflow styling for header total display
- the example attached is a direct string manipulation. it's important to note that this scenario is atypical. typically the number abbreviation tooling we use should attempt to trim that string down to something more readable such `333 T` or `333 B`. 
- https://numbrojs.com/try-me.html?lang=en-US and the settings we use are `{ average: true, mantissa: 2, trimMantissa: true, lowPrecision: false }`
1. confirm that large numbers/strings displayed in the graph card header for OpenShift Metrics now wraps
ent-3813
additional relates ent-4108
=> fix(graphCard): ent-3813 overflow styling for header total display

.eslintrc, src/components/form/__tests__/__snapshots__/select.test.js.snap, src/components/form/__tests__/select.test.js, src/components/form/select.js, src/setupTests.js, src/styles/_form.scss, src/styles/_usage-graph.scss, tests/__snapshots__/code.test.js.snap
- fix(graphCard): ent-3813 header styling for total display
- fix(select): focused unit testing
- ~**THERE IS AN UNINTENDED SIDE-EFFECT THAT HAPPENS WITH THIS UPDATE**. The more we attempt to fix this the worse it gets, see the below animation. PF select we use is right align, apparently it has issues in the Chrome browser due to this fix. We have to debug this accordingly, and we need to continue the push forward. The last commit on CI for ENT-3813 will be removed temporarily while this work happens.~ @mirekdlugosz 
- ~once approved/verified this will be squashed with the prior related commit~ @mirekdlugosz
- There is an issue around using the "popper" package within PF, we've added updates to compensate
- We've gone ahead and squashed the `overflow styling for header total display` …
=> fix(graphCard): ent-3813 header styling for total display

.env, .env.development, .env.proxy, .travis/custom_release.sh, CONTRIBUTING.md, config/webpack.dev.config.js, config/webpack.proxy.config.js
- build(dev,proxy): ent-3643 activate chrome2 for local run
- activates chrome2 for local run, dependent on https://github.com/RedHatInsights/cloud-services-config/pull/841
- Setting the default branches for proxy and local development towards `ci-beta`. Originally we had them set towards environments where the Curiosity Chrome 2 implementation hasn't happened yet. These can be altered at any future point.
1. confirm Subscriptions and product facets display and function
1. confirm Subscriptions and product facets display and function
...
ent-3643
#756 
#753
=> build(dev,proxy): ent-3643 activate chrome2 for local run

.travis/custom_release.sh, CONTRIBUTING.md, README.md, src/services/rhsmServices.js, src/services/userServices.js
- chore(build): default branch to main
- A rename of the default branch from `master` to `main` will take place after this merges. We may need to wait until this commit makes its way up towards prod to avoid breaking the badges... GitHub should redirect for a limited amount of time
- It should be unnecessary to update any scripts or CI, this is primarily a documentation update. The process for this transition already accounts for multiple branch names in CI. Because we limited what the "main" branch represents, in our case "production", no Curiosity developer should be actively/directly using this branch. This in turn should limit downstream issues.
1. confirm completion without errors
1. `$ …
=> chore(build): default branch to main

.env.development, config/build.plugins.js, config/spandx.config.js, package.json, yarn.lock
- build(dev,proxy): ent-3643 eslint webpack plugin
- dev workflow
1. confirm tests come back without error
1. confirm the interface starts and confirm the default local strings display
1. confirm the interface starts
...
ent-3643
=> build(dev,proxy): ent-3643 eslint webpack plugin

src/components/pageLayout/pageHeader.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewMissing.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productView.js, src/components/productView/productViewMissing.js, src/components/productView/productViewOpenShiftContainer.js
fix(productView): ent-4247 disable take a tour header button
- Issues with Pendo being applied after page load combined with a UX/design request to remove the header button means... we've disabled the "Take a tour" button from all existing products. The ability to display the button is still there and will be targeted for removal in a subsequent release.
- @mirekdlugosz 
1. confirm all products **NO longer have** the "Take a tour" button within the page view header
...
ent-4247
=> fix(productView): ent-4247 disable take a tour header button

.github/dependabot.yml, src/components/chart/__tests__/__snapshots__/chartHelpers.test.js.snap, src/components/chart/__tests__/chartHelpers.test.js, src/components/chart/chartHelpers.js
- fix(chartHelpers): ent-4135 custom x, y values, filter NaN and undefined
- chore(build): dependabot ignore victory packages
- custom x and y formatting caused a non-blocking error when returning `NaN` or `undefined`. this fix filters those values out and converts them to zero. `null` is still a valid return value
1. review the test update to make sure it's covering the scenarios for number, string, undefined, and null
1. tests should come back clean
1. navigate to OpenShift Dedicated metrics
1. confirm that viewing a "dual axis" graph under OpenShift Dedicated metrics or OpenShift metrics no longer throws a console error on graphs that have zero as there max y axis value …
=> fix(chartHelpers): ent-4135 custom x, y values, filter NaN and undefined

src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/__tests__/productView.test.js, src/components/productView/productView.js
- fix(productView): ent-3352 subs table active check
- Minor logic adjustment to make sure products such as OpenShift Dedicated on demand don't display the current subs table
1. navigate towards https://ci.foo.redhat.com/beta/openshift/subscriptions/openshift-dedicated and confirm the current subs table no longer displays
...
ent-3352 
ent-4376
=> fix(productView): ent-3352 subs table active check

src/components/graphCard/__tests__/__snapshots__/graphCardMetricTotals.test.js.snap, src/components/graphCard/graphCardMetricTotals.js
- fix(graphCardMetricTotals): ent-4366 data-test attributes
- there are no visual, or behavioral, changes associated with this update
- applies `data-test` attributes to the graph display associated with RHOSAK daily and monthly total cards @mirekdlugosz @ntkathole 
- the top/first/daily card has the attribute `data-test="graphDailyTotalCard"`
- the bottom/second/monthly card has the attribute `data-test="graphMonthlyTotalCard"`
...
ent-4366
=> fix(graphCardMetricTotals): ent-4366 data-test attributes

src/common/dateHelpers.js, src/services/rhsm/rhsmSchemas.js, src/services/rhsm/rhsmTranformers.js
- fix(rhsmSchemas): ent-4366 graph total display mismatch
* dateHelpers, utc base
* rhsmSchemas, adjust for utc date
* rhsmTransformers, month-day-year check for current date
- Appears there may be a display issue associated with the "Today's [metric total]". We came across an issue where the UTC date in the graph is not aligning correctly to the total for "Today's". This aims to correct that and align the dates based on UTC
ent-4366
=> fix(rhsmSchemas): ent-4366 graph total display mismatch

src/components/chart/__tests__/__snapshots__/chartHelpers.test.js.snap, src/components/chart/__tests__/chartHelpers.test.js, src/components/chart/chartHelpers.js
- fix(chartHelpers): ent-4366 adjust yaxis domain for small values
- Clean up PR targeted at a better UX
- Adjusts the y axis domain range for smaller values. Our cutoff for displaying small values was `0.01` we moved it to `0.1` because during testing a value came through in the graph rightttttt above `0.01` just enough to not fire the logic and just enough to look really minuscule on the graph
1. find an account that has a max Y value for the entire month above and below `0.1`... the graph should adjust accordingly. If there are any other Y values greater those will be used instead.
...
ent-4366
=> fix(chartHelpers): ent-4366 adjust yaxis domain for small values

src/components/graphCard/__tests__/__snapshots__/graphCardMetricTotals.test.js.snap, src/components/graphCard/graphCardMetricTotals.js
- fix(graphCardMetricTotals): ent-4366 expand data-test
- applies a `data-test="graphMetricTotals"` attribute to the div surrounding daily, monthly, and the graph display for individual metric displays, currently used in RHOSAK. @mirekdlugosz @ntkathole 
1. confirm the data-test attribute appears in the surrounding div
...
ent-4366
=> fix(graphCardMetricTotals): ent-4366 expand data-test

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/__tests__/product.rhosak.test.js, src/config/product.rhosak.js
- feat(rhosak): ent-4499 activate subs table
1. login and confirm the RHOSAK product display shows a subscriptions inventory tab, and subsequent table
...
ent-4499
#854
=> feat(rhosak): ent-4499 activate subs table

.env.development, config/spandx.config.js, config/webpack.dev.config.js, config/webpack.proxy.config.js
- build(dev): local run, content security policy update
- A chroming update applied a content security policy meta tag that breaks the local dev run. This compensates for it... see https://github.com/RedHatInsights/insights-chrome/pull/1733 
1. confirm the mock API setup comes through and the pages render without error
...
Related to https://github.com/RedHatInsights/insights-chrome/pull/1733 
Ongoing
=> build(dev): local run, content security policy update

src/components/inventoryCard/__tests__/__snapshots__/inventoryCardContext.test.js.snap, src/components/inventoryCard/__tests__/inventoryCardContext.test.js, src/components/inventoryCardSubscriptions/__tests__/__snapshots__/inventoryCardSubscriptionsContext.test.js.snap, src/components/inventoryCardSubscriptions/__tests__/inventoryCardSubscriptionsContext.test.js, src/components/inventoryCardSubscriptions/inventoryCardSubscriptionsContext.js
- fix(inventoryCardSubscriptionsContext): ent-4572 sort types
- **this issue/bug is currently limited to the `stage-beta` environment ONLY** see #857 
- Hosts/Instances sort types used as limiters on Subscriptions table sort... this corrects the limiting types. And applies a test type check for both hosts/instances and subscriptions inventory.
- @mirekdlugosz @ntkathole  
1. confirm the sort for Subscriptions inventory tables correctly applies column sorting queries
...
ent-4572
=> fix(inventoryCardSubscriptionsContext): ent-4572 sort types

.github/dependabot.yml
- chore(build): dependabot limit PRs
- since we do a once a month/sometimes twice a month NPM update ... limiting this to about 4ish PRs a month
... it's pfm
...
ongoing
=> chore(build): dependabot limit PRs

src/components/authentication/authentication.js, src/components/i18n/i18n.js, src/components/inventoryTabs/__tests__/__snapshots__/inventoryTab.test.js.snap, src/components/inventoryTabs/inventoryTab.js, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/product.rhosak.js
- fix(testing): clean up fragment wrappers
- squashes most, not all, of the "fragments should contain more than one child" warnings
...
ongoing
=> fix(testing): clean up fragment wrappers

src/components/inventoryCardSubscriptions/__tests__/__snapshots__/inventoryCardSubscriptionsContext.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewContext.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/router/__tests__/__snapshots__/redirect.test.js.snap, src/config/product.openshiftContainer.js, src/config/product.rhel.js, src/config/product.rhosak.js, src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap, src/services/rhsm/rhsmConstants.js, src/types/__tests__/__snapshots__/index.test.js.snap
- feat(inventoryCardSubscriptions): ent-4772 product_name sort
* config, allow sort on products, openshift, rhel, rhosak
* rhsmConstants, expand sort for product_name, total_capacity
1. navigate to a product that displays the subscriptions inventory: RHEL et all, OpenShift Container (left column), and/or RHOSAK
1. confirm column sorting is active and working for `Product -> product_name` and `Sockets/Cores -> total_capacity`
ent-4772
=> feat(inventoryCardSubscriptions): ent-4772 product_name sort

src/common/__tests__/__snapshots__/helpers.test.js.snap, src/common/__tests__/helpers.test.js, src/common/helpers.js, src/services/common/__tests__/__snapshots__/helpers.test.js.snap, src/services/common/__tests__/helpers.test.js, src/services/common/helpers.js, src/services/common/serviceConfig.js, src/services/user/__tests__/__snapshots__/userServices.test.js.snap, src/services/user/__tests__/userServices.test.js, src/services/user/userServices.js, tests/__snapshots__/code.test.js.snap
- refactor(userServices): ent-4669 locale func
- feat(serviceConfig): ent-4669 timeout for emulated call
- feat(helpers): ent-4669 aggregate error
- minor helper updates, broken out from the larger session work to provide some incremental updates
- no visual changes
1. confirm GUI loads without direct error
...
ent-4669
=> refactor(userServices): ent-4669 locale func

src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/inventoryCard/__tests__/__snapshots__/inventoryCardContext.test.js.snap, src/components/inventoryCard/__tests__/inventoryCard.test.js, src/components/inventoryCard/__tests__/inventoryCardContext.test.js, src/components/inventoryCardSubscriptions/__tests__/__snapshots__/inventoryCardSubscriptionsContext.test.js.snap, src/components/inventoryCardSubscriptions/__tests__/inventoryCardSubscriptions.test.js, src/components/inventoryCardSubscriptions/__tests__/inventoryCardSubscriptionsContext.test.js, src/components/inventoryCardSubscriptions/inventoryCardSubscriptions.js, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/__tests__/pageHeader.test.js, src/components/pageLayout/pageHeader.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewMissing.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/services/common/__tests__/__snapshots__/helpers.test.js.snap, src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap, src/services/common/__tests__/helpers.test.js, src/services/common/__tests__/serviceConfig.test.js, src/services/common/helpers.js, src/services/common/serviceConfig.js
- fix(pageHeader): clean up unused take a tour
- fix(inventoryCardSubscriptions): clean up props, inventory tests
- feat(serviceConfig,helpers): ent-4669 pass config for transformers
- minor non-visual clean up of components, tests
1. confirm products render as expected
...
ent-4669
=> Ent-4669 clean up, test updates

src/components/chart/__tests__/__snapshots__/chartIcon.test.js.snap, src/components/chart/__tests__/chartIcon.test.js, src/components/chart/chartIcon.js, src/config/__tests__/__snapshots__/product.openshiftContainer.test.js.snap, src/config/__tests__/__snapshots__/product.rhel.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/product.openshiftContainer.js, src/config/product.rhel.js, src/config/product.rhosak.js
- fix(config): ent-3230 unlimited quantity, use aria-label
- corrects the dual tooltip display, dependent on browser and os
1. confirm that infinite subscription table cells no longer display a "dual tooltip"
ent-3230
=> fix(config): ent-3230 unlimited quantity, use aria-label

build_deploy.sh, deploy/frontend.yaml, pr_check.sh
* Set `IMAGE` in `build_deploy.sh` and `pr_check.sh` scripts, see RHCLOUD-18589
* Provide `deploy/frontend.yaml` file, required by frontend-operator to deploy curiosity on ephemeral env
`IMAGE` is URL of container image. If we want to change it from rhsm-frontend to whatever we want, now would be a good time. This name must match name in app-interface, but I'll handle the PR.
`frontend.yaml` is resource template. The idea is something like that:
* bonfire will consult app-interfaces to get the list of applications and their components
* component needs resource template to be deployable
* depending on other flags, bonfire will deploy component or not
In other words: we need this file to create PR in app-interfaces adding frontend component to rhsm. And once app-interfaces PR is merged, we …
=> Ephemeral Environments onboarding step 2

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/product.rhosak.js, src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap, src/services/rhsm/rhsmConstants.js, src/types/__tests__/__snapshots__/index.test.js.snap
- feat(rhosak): ent-4689 activate billing provider
* product config rhosak, add secondary toolbar field config
- fix(toolbarFieldBillingProvider): ent-4689 tally query
* rhsmConstants, allow tally-capacity access billing provider
- Applies product configuration to RHOSAK for the visual aspect for #893 
1. confirm the RHOSAK product display applies the UX/design associated with ENT-4689
UPDATED screenshots
OUTDATED screenshots
What it looks like when the configuration for RHOSAK is applied
What inventory activation would resemble when the configuration for RHOSAK is applied
ent-4689
relates #883 #893
=> feat(rhosak): ent-4689 activate billing provider

src/config/product.rhosak.js
- fix(rhosak): ent-4982 activate sort, storage GiB months
- activates the sort for storage GiB months inventory column
1. confirm tests pass
1. confirm the "streams"/RHOSAK column for storage can now be sorted with the column header button
ent-4982
=> fix(rhosak): ent-4982 activate sort, storage GiB months

src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/__tests__/rhsmTransformers.test.js, src/services/rhsm/rhsmTransformers.js
- fix(rhsmTransformers): ent-5121 hide graph future dates
- Hides both ... future dates that `has data = false` AND the current UTC date if `has data = false`
- DOES NOT HIDE past dates that have `has data = false`
- applies unit testing behavior confirmations in the event "granularity" ever shifts from `daily`
1. confirm the graph display for RHOSAK are hiding future dates with `has data = false`, see examples below
1. confirm the graph displays for RHOSAK are hiding current dates with `has data = false`, see examples below
ent-5121
=> fix(rhsmTransformers): ent-5121 hide graph future dates

src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/__tests__/rhsmTransformers.test.js, src/services/rhsm/rhsmTransformers.js
- fix(rhsmTransformers): ent-5213 allow first dates to draw line
* rhsmTransformers, shift x axis index for first dates
- adds an additional x axis entry and tick in the event the first date with a value exists, and all subsequent dates are future dates. this allows Victory to display a line
1. In order to emulate this you have to add a GUI debugger date to the dotenv files. Add the following entry to a `.env.local` file in the root of the project
```
REACT_APP_DEBUG_DEFAULT_DATETIME=20220701
```
1. You'll also need to update the fixture associated with `Instance Hours` by updating the `./src/services/rhsm/rhsmServices.js` file, [you can find an example here](https://github.com/cdcabrera/curiosity-frontend/blob/20220705b-ent-5213/src/services/rhsm/rhsmServices.js#L1305-L1486)
1. update …
=> fix(rhsmTransformers): ent-5213 allow first dates to draw line

src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingProvider.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldSelectCategory.test.js.snap, src/services/rhsm/__tests__/__snapshots__/rhsmConstants.test.js.snap, src/services/rhsm/rhsmConstants.js
- ~fix(rhosak): ent-4689 remove none option~ fix(rhosak): sw-93 billing provider, remove none option
- removes the `none` option, behavior for #936  should be updated to reflect this
- introduces "unique" additional options for our dropdown listing components when compared with existing lists
- as silly as this seems, this update will affect generating future lists, and force unique qualities to be configured either in the API or GUI
- consistency of dropdown options vs what the API provides is the underlying issue... why is the option being provided in the first place
- ~marking this as blocked since "removing none" was posed as a solution without accounting for configuration~
1. `$ yarn …
=> fix(rhosak): ent-4689 (sw-93) billing provider, remove none option

src/common/dateHelpers.js, src/services/rhsm/rhsmTransformers.js
- fix(dateHelpers):  ent-5213 expose for testing
- exposes `dateHelpers` to the browser console for both `dateHelpers` and `rhsmTransformers`
- type `$ curiosity.dateHelpers.[method]()` or `$ curiosity.rhsmTransformers.[method]()`
...
ent-5213
SWATCH-43
=> fix(dateHelpers):  ent-5213 (sw-43) expose for testing

deploy/frontend.yaml
We changed container image name in app-interfaces repository, but we forgot to change it here.
Without this change, you need to pass few more CLI options to `bonfire` to deploy frontend to ephemeral environment.
=> fix(build): Change container image name

src/components/productView/__tests__/__snapshots__/productViewMissing.test.js.snap, src/config/product.satellite.js, src/config/routes.js
- fix(satellite): sw-20 remove graph threshold
- disables the threshold display for satellite views
1. navigate to the satellite product views, confirm threshold no longer displays for the graphs
sw-20
=> fix(satellite): sw-20 remove graph threshold

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/config/__tests__/__snapshots__/product.rhacs.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/product.rhacs.js, src/config/product.rhosak.js, src/services/rhsm/rhsmServices.js
- ~refactor(inventoryCardSubscriptions): ent-5129 camel to snake~
* ~config, products updated to use snake case~
* ~services, constants updated with subscriptions types~
- fix(rhosak,rhacs): ent-5129 billing provider for subscriptions inventory
* config, rhosak, rhacs billing provider column
* services, subscriptions mock
- ~includes refactor work to flip the subs table config to using snake case instead of camel case~ see #949 instead
- ACTIVATES the billing provider column display for RHOSAK
- notes regarding what copy displays when for billing providers, #936 
1. login and 
1. confirm all subscriptions table inventory column headers for RHEL, OpenShift console, and …
=> fix(rhosak,rhacs): ent-5129 (sw-47) billing provider for subscriptions inventory

public/locales/en-US.json
* locale, optin strings
Not tested. Issue description is self-explanatory. I am counting on CI telling me if there is anything more needed. Apparently, QE automation does not include this string, so no changes are needed there.
Implements SW-547.
=> fix(optin): sw-547 Remove on-premise from optin description

src/components/graphCard/__tests__/__snapshots__/graphCard.test.js.snap, src/components/graphCard/graphCard.js
- fix(graphCard): sw-223 generated key from settings
1. open the dev console, then
- navigate to an "on demand" product view within Subs
- hitting refresh you should NO longer see the "duplicate key" console error
...
sw-223
ent-4899
pr #927
=> fix(graphCard): sw-223 generated key from settings

CHANGELOG.md, CONTRIBUTING.md, package.json, yarn.lock
- chore(build): generated changelog
- Migrates from the now deprecated Standard Version
1. `$ yarn release --dry-run`
- confirm the terminal output generates a changelog
1. create a NEW branch and sync it with the upstream/dev 
- then run `$ yarn release`
- confirm a commit is generated with updates to `CHANGELOG.md` and `package.json`
- confirm the commits on `CHANGELOG.md` align with a potential release
- undo the generated commit, or leave it be =) 
...
ongoing
=> chore(build): generated changelog

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18nHelpers.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/i18n/__tests__/i18nHelpers.test.js, src/components/i18n/i18n.js, src/components/i18n/i18nHelpers.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOpenShiftContainer.test.js.snap, src/components/productView/productView.js, src/components/productView/productViewOpenShiftContainer.js, src/config/__tests__/__snapshots__/product.openshiftContainer.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap
- fix(i18nHelpers): update multi-context keys
- perf(i18n): breakout i18n into helpers
- this update makes it easier to apply mult-context keys
1. confirm that all strings are displaying correctly, including dropdown/select lists
...
ongoing
=> fix(i18nHelpers): update multi-context keys

src/components/inventoryCard/__tests__/__snapshots__/inventoryCardContext.test.js.snap, src/components/inventoryCard/inventoryCard.js, src/components/inventoryCard/inventoryCardContext.js, src/components/inventoryCardSubscriptions/__tests__/__snapshots__/inventoryCardSubscriptionsContext.test.js.snap, src/components/inventoryCardSubscriptions/inventoryCardSubscriptionsContext.js, tests/__snapshots__/code.test.js.snap
- fix(inventoryCard): sw-703 reset columns, rows
- quick fix to align inventory components
- Need to review using the deep comparison on these against a lighter alternative, something like data response identifiers. We use a form of ID hash caching that could be leveraged here
1. confirm that inventory displays reset and display the correct data when selecting granularity, granularity-like, and uom filters
...
sw-703
relates sw-702 sw-235 sw-690
=> fix(inventoryCard): sw-703 reset columns, rows

src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/__tests__/rhsmTransformers.test.js, src/services/rhsm/rhsmServices.js, src/services/rhsm/rhsmTransformers.js
- fix(rhsmTransformers,services): sw-726 restore capacity logic
- the capacity metric response includes a `has_data` property. we reverted using this property and restored the original y axis capacity display logic
1. confirm threshold/capacity display returns expected display results
1. confirm checks come back clean
...
sw-726
relates sw-690 sw-235
=> fix(rhsmTransformers,services): sw-726 restore capacity logic

.github/workflows/commit_lint.yml, .github/workflows/pull_request.yml, .travis.yml, README.md, package.json
- chore(build): nodejs 14 to 16
- activates nodejs 16 min, preps for nodejs 18
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
1. confirm this completes without error
...
ongoing
=> chore(build): nodejs 14 to 16

tests/__snapshots__/dist.test.js.snap, tests/dist.test.js
- chore(testing): sw-722 dist route checks for ephemeral
- simple output checks to confirm ephemeral routing config aligns with app routing expectations @mirekdlugosz 
- we missed an update that could cause future problems in #1014 this check will help prevent that in the future
1. confirm build checks pass
...
sw-722
ongoing
=> chore(testing): sw-722 dist route checks for ephemeral

src/config/__tests__/__snapshots__/product.rhel.test.js.snap, src/config/product.rhel.js, src/services/rhsm/rhsmSchemas.js
- fix(config): sw-106 disable category, metric sort
* config, rhel disable sort, metric dash display
* rhsmSchemas, lowercase response, allow empty
1. navigate to RHEL and confirm
- that the Category and metric/Sockets sorts are off
- that the metric/Sockets column displays `--` when the value doesn't exist or is zero from the API
sw-106
sw-235
sw-806
pr #1018
=> fix(config): sw-106 disable category, metric sort

src/components/inventoryTabs/__tests__/__snapshots__/inventoryTab.test.js.snap, src/components/inventoryTabs/__tests__/__snapshots__/inventoryTabs.test.js.snap, src/components/inventoryTabs/__tests__/inventoryTab.test.js, src/components/inventoryTabs/__tests__/inventoryTabs.test.js, src/components/inventoryTabs/inventoryTabs.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/productView.js, src/components/tabs/__tests__/__snapshots__/tabs.test.js.snap, src/components/tabs/__tests__/tabs.test.js
- refactor(inventoryTabs): sw-625 class to function, hooks
- no visual or behavior changes associated with this update
- prep for moving over to react router 6, removing the need for a "connected router" patch by flipping the last of our connected components over to hooks
1. confirm tabs can still be selected
1. confirm build completes successfully, tests come back clean
...
sw-625
#989
=> refactor(inventoryTabs): sw-625 class to function, hooks

src/config/__tests__/__snapshots__/product.openshiftContainer.test.js.snap, src/config/__tests__/__snapshots__/product.rhacs.test.js.snap, src/config/__tests__/__snapshots__/product.rhel.test.js.snap, src/config/__tests__/__snapshots__/product.rhods.test.js.snap, src/config/__tests__/__snapshots__/product.rhosak.test.js.snap, src/config/__tests__/__snapshots__/product.satellite.test.js.snap, src/config/__tests__/product.openshiftContainer.test.js, src/config/__tests__/product.rhacs.test.js, src/config/__tests__/product.rhel.test.js, src/config/__tests__/product.rhods.test.js, src/config/__tests__/product.rhosak.test.js, src/config/__tests__/product.satellite.test.js
- fix(config): align product filter tests
- pre-update to sw-860, aligns product config unit testing
- this only affects unit tests
...
related to sw-860
=> fix(config): align product filter tests

src/components/authentication/authenticationContext.js, src/components/router/routerContext.js
- fix(routerContext): sw-625 doc name, deprecated init
...
sw-625
#1052
=> fix(routerContext): sw-625 doc name, deprecated init

public/locales/en-US.json
- fix(locale): sw-728 rhel, satellite variant filters
- quick fix, string update Satellite products and RHEL architectures filter shifts towards `Variant`
- a more long term solution of combining the RHEL and Satellite views will have its own story
1. confirm the filters for both RHEL and Satellite toolbar display as `Variant` and `Filter by variant`, see examples below
sw-728
=> fix(locale): sw-728 rhel, satellite variant filters

src/components/productView/productViewMissing.js
- fix(productViewMissing): sw-625 local dev view, run
- non blocking local developer workflow view and run
- we ignored/disabled the local developer workflow to get the router updates out. this pr reactivates it 
- this may, or may not, throw an error in console in environment since routing is now tiered/nested with consoledot
1. confirm that the default card display appears and can be used to navigate between all available products, see example
- _note: the selected card attempts a url path closest match for product_
1. confirm routing/navigating between products remains unchanged
- confirm manually navigating …
=> fix(productViewMissing): sw-625 local dev view, run

src/components/README.md, src/components/router/__tests__/__snapshots__/routerContext.test.js.snap, src/components/router/__tests__/routerContext.test.js, src/components/router/routerContext.js
- fix(routerContext): sw-625 useNavigate state update
- another non-blocking routing update. #1071 exposed a `useNavigate` issue, this corrects it. `useNavigate` is used on the missing product view ONLY (currently). If we at some point decide to `useNavigate` outside of the missing view this issue would be exposed
- there should be no noticeable end-user behavioral changes with this update
1. confirm that navigating from the "developer" view (product missing) does not require a "browser refresh" to view the corresponding product context
...
sw-625
#1071
=> fix(routerContext): sw-625 useNavigate state update

CONTRIBUTING.md, src/common/README.md, src/common/__tests__/__snapshots__/helpers.test.js.snap, src/common/helpers.js, src/components/README.md, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18nHelpers.test.js.snap, src/components/i18n/__tests__/i18nHelpers.test.js, src/components/i18n/i18nHelpers.js
- refactor(i18nHelpers): sw-922 translate break apart
- feat(i18nHelpers): sw-922 apply testId to copy
- exposes a `testId` prop for i18next to allow either the use of the locale string key on a span with a `data-test` attribute wrapped around the immediate copy, or a custom identifier
- this does restructure aspects of our i18next implementation
...
sw-922
=> feat(i18nHelpers): sw-922 apply testId to copy

CONTRIBUTING.md, src/components/README.md, src/components/i18n/__tests__/__snapshots__/i18nHelpers.test.js.snap, src/components/i18n/__tests__/i18nHelpers.test.js, src/components/i18n/i18nHelpers.js
- fix(i18nHelpers): sw-922 i18n element wrapping
- adjust to wrap component elements, not just strings
- adds the ability to use a custom element ie. `testId: <div className="custom-class" data-test="custom-id" />`
...
sw-922 #1079
=> fix(i18nHelpers): sw-922 i18n element wrapping

src/components/router/__tests__/__snapshots__/routerContext.test.js.snap, src/components/router/__tests__/routerContext.test.js, src/components/router/routerContext.js
- fix(routerContext): sw-1089 page display titles
- when we updated routing we shifted the title format, this moves it back
1. confirm that page titles follow one of the recommend formats
- _*note we had been leveraging "the bundle" (of sorts it currently registers out as `console.redhat.com`) applied through the chrome `updateDocumentTitle` hook... we left that in place for now with the understanding we may have to apply it "manually" in a subsequent update_ **_Subs is in a unique position compared to other apps... it spans multiple bundles and has the ability to be loaded …
=> fix(routerContext): sw-1089 page display titles

config/jest.setupTests.js, src/components/router/__tests__/__snapshots__/routerContext.test.js.snap, src/components/router/routerContext.js, src/index.js
- feat(routerContext): sw-1089 enhance page titles
- exposes the new getBundleData func and related copy for doc title
- fails quietly if unavailable 
1. confirm product display view document titles in Subs display as per requirements
...
sw-1089
#1089 
https://github.com/RedHatInsights/insights-chrome/pull/2406
=> feat(routerContext): sw-1089 enhance page titles

.github/workflows/pull_request.yml, .travis.yml, README.md, package.json
- chore(build): nodejs 16 to 18
- current lts
- potential check for next lts release, nodejs 20
- this aspect is blocked by #1103 due to an eslint jsdoc NPM dep update 
1. next...
...
ongoing
blocked by #1103
=> 3 of 3, chore(build): nodejs 16 to 18

config/webpack.proxy.config.js, package.json, yarn.lock
- build(proxy): sw-917 add preview to appUrl
- package update from coincidentally a couple of days ago when we retested
1. navigate to both "beta" and "preview" paths and confirm local development is still possible
...
sw-917
=> build(proxy): sw-917 add preview to appUrl

deploy/frontend.yaml, tests/__snapshots__/dist.test.js.snap
- chore(build): sw-538 rhacs ephemeral routing
- clean up for RHACS activation, reflect in ephemeral routing config
...
sw-538
dup sw-777
=> chore(build): sw-538 rhacs ephemeral routing

config/webpack.prod.config.js, scripts/pre.sh
- build(prod,stage): sw-917 dotenv config for surface urls
- The update on prod from `beta` to `preview` on 20230426 highlighted a missing "hardcoded-like" path for multiple urls. Curiosity "shares" the `beta` prefix through dotenv files making `beta`, and now `preview` available during compile for both the build and GUI
- Curiosity uses a "path prefix" to load remote locale strings. This update moves and applies "preview" to that path instead of beta while still deploying to "beta/apps"
- Curiosity uses a link back to inventory displays, this is also affected
1. navigate towards preview staging `subscriptions`
- open the dev console and confirm `en-US.json` reflects the correct path
- confirm the …
=> build(prod,stage): sw-917 dotenv config for surface urls

src/config/__tests__/__snapshots__/product.rhacs.test.js.snap, src/config/__tests__/__snapshots__/product.rhods.test.js.snap, src/config/product.rhacs.js, src/config/product.rhods.js
- fix(config): sw-1294 rhacs, rhods inventory links
- rhacs inventory links
- rhods disabled inventory links with note
1. confirm the RHACS inventory links navigate towards `/application-services/acs/instances/instance/`
1. confirm the RHODS inventory links are no longer available
...
sw-1294
=> fix(config): sw-1294 rhacs, rhods inventory links

src/config/__tests__/__snapshots__/product.openshiftDedicated.test.js.snap, src/config/__tests__/__snapshots__/product.openshiftMetrics.test.js.snap, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js
- fix(config): sw-1335 openshift on-demand inventory links
- disables all on-demand inventory links, see sw-1209 for final resolution
1. navigate to `/subscriptions/openshift` and confirm
- OpenShift Dedicated variant inventory links no longer activate/display
- OpenShift metrics variant inventory links no longer activate/display
...
sw-1335
related sw-1209 sw-1294 #1129
=> fix(config): sw-1335 openshift on-demand inventory links

src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhacs.js, src/config/product.rhods.js, src/config/product.rhosak.js, src/config/product.rosa.js
- refactor(config): sw-1215 reduce metric card mantissa
- reduces the potential decimals displayed if a float is passed to the GUI. 
- it is understood that the API should now be passing an int with a math ceil on it 
- this GUI update does NOT prevent the display of a float, but instead reduces the number of potential decimal places.  
- this update helps retain the potential to display values such as ~`1.2K` or `1.5M` etc~ `1.23K` or `1.52M` etc
- we can perform a subsequent fix for `Number.parseIn(someValue, 10)` if the API fails to pass the correct values
- this affects the following product configurations
- OpenShift Dedicated
- OpenShift metrics
- RHACS
- RHODS
- formerly RHOSAK
- ROSA
1. …
=> refactor(config): sw-1215 reduce metric card mantissa

src/config/__tests__/__snapshots__/product.rosa.test.js.snap, src/config/__tests__/product.rosa.test.js, src/config/product.rosa.js
- refactor(config): sw-938 activate rosa subscriptions
1. confirm checks come back clean
1. confirm ROSA variant subscriptions inventory displays
1. confirm checks come back clean
=> refactor(config): sw-938 activate rosa subscriptions

src/components/README.md, src/components/graphCard/__tests__/__snapshots__/graphCardChart.test.js.snap, src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap, src/components/inventoryCard/inventoryCard.js, src/components/minHeight/__tests__/__snapshots__/minHeight.test.js.snap, src/components/minHeight/__tests__/minHeight.test.js, src/components/minHeight/minHeight.js
- refactor(minHeight): sw-1348 class to func
- 1 of 3
- moves from a class to function to improve unit tests before the migration from enzyme
1. confirm the graph display renders correctly
- the metric/on-demand card displays should NOT collapse when graph filters are selected
1. confirm the inventory display renders correctly
- the instances and subscriptions inventories should NOT collapse when paging from page to page. the inventory tab card should maintain its height consistently
...
related sw-1348
related #1148 #1144
=> 1 of 3 - refactor(minHeight): sw-1348 class to func

src/config/product.rhods.js, src/config/product.rhosak.js, tests/__snapshots__/dist.test.js.snap
- fix(config): rhods, app-services default product
- corrects the root path for "application-services/subscriptions/" towards using RHODS
1. type in `application-services/subscriptions/` into the browser url path
- confirm that the `RHODS` card highlights
...
ongoing
=> fix(config): rhods, app-services default product

config/webpack.proxy.config.js
- build(webpack): rhcloud-25607 proxy preview fix
- this will be squashed into the prior related commits
1. confirm access to the path `/preview/subscriptions/usage/[product]` correctly displays
...
rhcloud-25607
related #1163
=> build(webpack): rhcloud-25607 proxy preview fix

deploy/pr_check.sh
The main goal is to run QE tests on ephemeral environment as part of PR workflow.
Right now there's one such tests that goes to subscription table and verifies it is not displayed. Later we will figure out how to create data inside ephemeral env, and we'll work on extending suite of tests.
I've got this running when issuing commands manually from my machine. Let's see if I can get it running from PR check as well.
=> chore(build): run QE tests during PR workflow

src/services/rhsm/rhsmServices.js
- fix(services): sw-1605 mock update for deprecated ids
- affects local run only, staging and prod environments are unaffected
- the schema checks actually catch the issue and continue 
- local run mock updates, replace RHEL with RHEL for x86
1. confirm the capacity response on local run appears as intended
...
sw-1605
#1166
=> fix(services): sw-1605 mock update for deprecated ids

deploy/pr_check.sh
=> chore(build): Update pr_checks with rp and ibutsu options

.github/dependabot.yml, .github/workflows/pull_request.yml, .travis.yml, .travis/custom_release.sh, CONTRIBUTING.md
- chore(build): workflow mod, prep for branch rename
- Prep work for moving to using `main` and `stable` branches where...
- `main` is a representation of `beta`/`preview` staging
- `stable` is a representation of `stable` staging, and related Git hashes are used to do production releases
- Aligns documentation to the branching structure
- Aligns GitHub action workflows to the branching structure
- Aligns Travis temporarily to the new branch structure while behind the scenes routing shifts to the container build
- This will deactivate ROSA in the OpenShift group variant select/dropdown across all environments @diegomaranhao . ROSA will still be directly available at `[subscriptions ui]/rosa`
- AFTER this PR is merged...
- We'll confirm that Travis is still functioning and pushed related …
=> chore(build): sw-1647 workflow mod, prep for branch rename

config/webpack.prod.config.js, scripts/pre.sh
- chore(build): sw-1647 deployment env variable
- step 2 of sw-1647, allow an additional BETA env variable for container builds
- there should be no change to the current Travis deployed build
...
sw-1647 step 3
=> chore(build): sw-1647 deployment env variable

src/components/graphCard/__tests__/__snapshots__/graphCardChartLegend.test.js.snap, src/components/i18n/i18nHelpers.js
- fix(i18nHelpers): sw-1537 apply multicontext to all keys
- expands multi-context to all available keys (values) when an Array of string keys is used
1. confirm products graphs, and related tooltips display as intended
...
sw-1537
=> fix(i18nHelpers): sw-1537 apply multicontext to all keys

src/redux/README.md, src/redux/hooks/__tests__/__snapshots__/useReactRedux.test.js.snap, src/redux/hooks/useReactRedux.js, src/services/README.md, src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/__tests__/rhsmTransformers.test.js, src/services/rhsm/rhsmSchemas.js, src/services/rhsm/rhsmServices.js, src/services/rhsm/rhsmTransformers.js
- feat(rhsmTransformers): sw-1537 subs, guest responses
- standalone updates, currently not active. activation will happen with #1168 
- transformations for guests and subscriptions
- deep equal comparison for redux hooks
...
sw-1537
related #1184 #1168
=> feat(rhsmTransformers): sw-1537 subs, guest responses

package.json
Adding NPM aliases to be used in unified Jenkinsfile approach.
=> build(release): adding npm aliases for pipline

src/components/README.md, src/components/chart/chartIcon.js, src/components/table/__tests__/__snapshots__/tableEmpty.test.js.snap, src/components/table/tableEmpty.js
- fix(tableEmpty): sw-1537 aria-label attribute format
- fix(chartIcon): sw-1689 size prop type warning
- couple of fixes that popped up during the work for PF5 sw-1689
...
related #1194 sw-1689 sw-1537
=> Fixes for swatch-1537, clean up for swatch-1689 PF5 update

.env.proxy, config/webpack.proxy.config.js
- build(proxy): sw-1689 locale file paths
- not necessarily related to the PF5 migration, however it was discovered during testing. 
- solves a recent issue where our locale file during proxy run wasn't being called correctly
1. confirm proxy runs locally and
- displays locale strings
- locale strings update on browser refresh
...
#1202 #1194
sw-1689
=> 3 of 3, PF5 Migration, build(proxy): sw-1689 locale file paths

scripts/pre.sh
- fix(build): sw-1885 rollback to beta prefix
- After the container build is confirmed and pushed to environment
- Log into stage-preview/beta 
- confirm Subs UI is updated by accessing the hash under the browser developer console
- `$  curiosity.UI_VERSION`
...
sw-1885
related sw-1792
=> fix(build): sw-1885 rollback to beta prefix

package.json, scripts/pre.sh, yarn.lock
* **deps-dev** npm-check-updates from 16.14.4 to 16.14.6  ([#1215](https://github.com/RedHatInsights/curiosity-frontend/pull/1215)) ([cf6e70d](https://github.com/RedHatInsights/curiosity-frontend/commit/cf6e70d036d422f7496aab2a136e059651639880))
* **build** sw-1885 rollback to beta prefix  ([#1221](https://github.com/RedHatInsights/curiosity-frontend/pull/1221)) ([e442415](https://github.com/RedHatInsights/curiosity-frontend/commit/e442415a9ab2e17915b402d691aa7ab92e984ad3))
=> Environment sync, preview to stable

src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap, src/components/toolbar/toolbarFieldGroupVariant.js
- fix(toolbarFieldGroupVariant): sw-1889 set maxHeight
- the number of variants in the RHEL display has expanded greatly. this applies a select/dropdown max height to implement a scrolling overflow
- this scrollbar should not appear on variant listings, like OpenShift, that do not hit the height requirement
1. navigate towards RHEL `subscriptions/rhel` or some current path under [subscriptions/usage]
- confirm the dropdown/select displays a scrollbar
related sw-1889 sw-1890 sw-1891 sw-1692
=> fix(toolbarFieldGroupVariant): sw-1889 set maxHeight

src/components/chart/__tests__/__snapshots__/chart.test.js.snap, src/components/chart/__tests__/__snapshots__/chartHelpers.test.js.snap, src/components/chart/chartHelpers.js
- fix(chartHelpers): sw-1878 compensate for victory charts textsize
- we think the culprit is some aspect of victory charts helper for textsize "measureDimensionsInternal" missing a param guard for an empty string/data. Our solution confirms any data exists before attempting a label overlap
BEFORE YOU UPDATE TO THIS PATCH, confirm the issue exists
1. log out/in - THIS IS REQUIRED to see the issue
1. open the path to Subs RHEL
1. use the left nav to navigate towards Subs OpenShift
1. an error warning related to victory charts should appear
AFTER YOU'VE confirmed sync with this patch
1. log out/in - THIS IS REQUIRED to see the issue
1. open the path …
=> fix(chartHelpers): sw-1878 compensate for victory charts textsize

public/locales/en-US.json
- fix(rhods): sw-2000 data science to ai title
- minor title update
- appears we only used `Data Science` in a single location
- separate repo for left nav update
1. confirm page title displays as `Red Hat OpenShift AI`
sw-2000
=> fix(rhods): sw-2000 data science to ai title

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.openshiftContainer.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhacs.js, src/config/product.rhel.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js, src/config/product.satellite.js
- refactor(config): sw-1987 testing, numeric inventory cells
- expose all inventory numeric cell values under a `data-value` and associated `data-test=[instances|subscriptions]-cell-[field name]` attributes on a surrounding `<span />` tag
- LIMITATIONS
- currently we do not include the row count anywhere in the display
- if a value is `undefined` it will display as the string `undefined`... this shouldn't happen, ~but we planned for it~ but this is the expected result if it happens
1. open each product view and confirm that `data-test` and `data-value` appear on a `<span />` tag wrapped around numeric inventory content
1. `$ …
=> refactor(config): sw-1987 testing, numeric inventory cells

src/components/productView/productView.js
- fix(productView): key causes refresh
- ~refactor(productView): simplify, unnecessary hook~
- this commit can be found here, https://github.com/cdcabrera/curiosity-frontend/tree/20240130-productview-idealsolution
- ~simplifies the product view component by removing the no longer necessary `useCallback`~
- ~this was done because of routing overlap between `swatch` and `subscriptions inventory`~
- ~align to authentication component, consistency~
- this started as a `fix` for the `key` being used on the provider... we realized unnecessary view refreshes were happening because the key aligned to `productID` instead of `productGroup`... updating to `productGroup`  removed the refresh issue (and removing also works)... then we realized the hook itself might not be necessary...
- UPDATE, the …
=> fix(productView): key causes refresh

src/redux/hooks/__tests__/useReactRedux.test.js, src/redux/hooks/useReactRedux.js
- fix(useReactRedux): memoize callback
- test(useReactRedux): expand memoize checks
- these will be merged as a single update... 
- this issue does not appear to be currently exposed partially based on our memoized deep equality checks, and not exposed on prod since the commits are still in staging. However, the issue will be if we move over to a shallow equality check
To check this functionality we broke the unit test up into a **before-after** set of updates... you can see it for yourself in the commits. If you want to confirm the functionality roll the last `DEV update test to reflect new memoize` commit back on the unit test updates, then...
- confirm the unit tests fail
- then reactivate it to confirm they pass
...
ongoing, dependent on #1264
=> fix(useReactRedux): memoize selector callback

src/components/README.md, src/components/table/__tests__/__snapshots__/table.test.js.snap, src/components/table/__tests__/__snapshots__/tableEmpty.test.js.snap, src/components/table/tableEmpty.js
- fix(tableEmpty): correct refresh flash on empty state
- minor visual correction
BEFORE APPLYING THIS COMMIT, note the behavior
1. navigate towards an product
- attempt to switch between product variants and note the "clear filters" messaging
- apply this commit
- now note the "clear filters" messaging is absent dependent on network speed
...
ongoing
=> fix(tableEmpty): correct refresh flash on empty state

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js
- fix(config) sw-2030 openshift payg inventory links
- updates inventory links for (any additional products can be updated iteratively)
- OpenShift Metrics
- Dedicated Metrics
1. confirm inventory instances links for authorized users now navigate towards `openshift/details/[id]` for the following product ids/variants
- OpenShift Metrics
- Dedicated Metrics
1. confirm inventory instances links for authorized users now navigate towards `openshift/details/[id]` for the following product ids/variants
- …
=> fix(config) sw-2030 openshift payg inventory links

package-lock.json, package.json, src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap
- chore(build): npm update
- axios package update
...
ongoing
=> chore(build): npm update

src/components/inventoryCard/inventoryCard.js
- fix(inventoryCard): adjust load flash on empty state
- depending on network speeds the empty inventory state flashes between receiving data then displaying it... turn the condition into an `OR` instead of attempting parallel-like display
1. navigate to and between product views and confirm that after inventory loads the "empty state clear filters" display no longer flash displays
...
related #1277 
ongoing
=> fix(inventoryCard): adjust load flash on empty state

deploy/build_deploy.sh, deploy/pr_check.sh, package.json
=> chore(build): ephemeral build fix for prchecks failure

src/components/chart/__tests__/__snapshots__/chartElements.test.js.snap, src/components/chart/chartElements.js
- fix(chartElements): victory charts props alteration
- triages a victory charts bug recently exposed with package updates under #1298 
1. navigate towards Subs UI RHEL x86 graph display
- hover over either the left side, or right side of the graph
- move your cursor towards the middle of the graph... no error should cause the entire page to crash
- currently Victory Charts causes an intermittent/random'ish error that manages to take out the entire UI without this patch
ongoing
related #1298
=> fix(chartElements): victory charts props alteration

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/__tests__/product.config.test.js, src/config/product.openshiftContainer.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhel.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js, src/config/product.satellite.js, src/services/rhsm/rhsmServices.js
In [SWATCH-2144](https://issues.redhat.com/browse/SWATCH-2144), we changed the existing instance_id from inventory_id to the actual provider id. However, the UI was using this instance_id to build up the link to the inventory service. So, we need to provide the inventory_id, so the UI can continue building this url.
Related to https://github.com/RedHatInsights/rhsm-subscriptions/pull/3188.
1.- `npm start`
2.- browse to `http://localhost:3000/apps/subscriptions/openshift`
3.- when moving the cursor over any item name, the link should look like `http://localhost:3000/insights/inventory/CCCCC-b344-4778-831c-CCCCCCC/` instead of `http://localhost:3000/insights/inventory/i-4778-831cCCCCCCC/`
I've also verified that the links for ACM (here, we need to keep using `instance_id`), OpenShift …
=> fix(inventoryLinks): sw-2326 use inventory_id instead of instance_id

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.rhel.js, src/config/product.satellite.js, src/services/rhsm/rhsmServices.js
- fix(config): sw-2357 replace public cloud display copy
- minor display copy adjustment to align with sorting on "category" for instance inventory displays
- Affects product configs
- RHEL
- Satellite
1. Navigate to both the RHEL and Satellite views
- confirm the instance inventory display column for type has cells that display the cloud provider field only
1. Navigate to both the RHEL and Satellite views
- confirm the instance inventory display column for type has cells that display the cloud provider field only …
=> fix(config): sw-2357 replace public cloud display copy

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js
- fix(config): sw-2480 revert inventory_id to instance_id
- Reverts towards using instance_id for on-demand'ish products
- Expanded the annotation for RHODS/AI until linking can be enabled
1. confirm the related products now correctly navigate using "instance_id" instead of "inventory_id"
- OpenShift Dedicated metrics
- OpenShift Container metrics
- RHEL ELS PAYG
- ROSA
...
related sw-2326 sw-1209
sw-2480
=> fix(config): sw-2480 revert inventory_id to instance_id

.env.development, CONTRIBUTING.md, config/webpack.dev.config.js, package.json
- build: local dev, custom mock port @mmusil 
- allows for running a custom port when you run the local dev command
- the default proxy port is now `3030`
- confirm the API and the UI display accordingly
- shut it down
1. `$ export MOCK_PORT=5000; npm start`
- confirm the API and the UI display accordingly, or if you have issues with the port try a different custom port like `9000`
- you can also see the proxy port during startup of the command, similar to
...
ongoing
=> build: local dev, custom mock port

public/locales/en-US.json, src/common/README.md, src/common/__tests__/__snapshots__/dateHelpers.test.js.snap, src/common/dateHelpers.js, src/components/README.md, src/components/chart/__tests__/__snapshots__/chartHelpers.test.js.snap, src/components/chart/chart.js, src/components/chart/chartHelpers.js, src/components/graphCard/__tests__/__snapshots__/graphCardHelpers.test.js.snap, src/components/graphCard/__tests__/graphCardHelpers.test.js, src/components/graphCard/graphCardHelpers.js
- refactor: sw-1594 quarterly range expand to 5 years
- Due to the number of entries for quarterly views the graph x-axis ticks require an adjustment.
- We attempted a different solution where we flipped the year from being applied to the beginning months to the end months. The primary reason being, we're unable to determine which ticks victory charts dynamically hides beyond "[every other one]". However this failed to show the graph display year when the browser/display date moved within the July quarter and recreated the original scenario.
- To avoid having to do fine-grain date tick display logic now, and in the future, we're opting to stick with the solution proposed where we just show all dates for each of the x axis ticks since it bypasses the issues
1. update the NPM packages with …
=> refactor: sw-1594 quarterly range expand to 5 years

src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/__tests__/rhsmTransformers.test.js, src/services/rhsm/rhsmTransformers.js
- fix (rhsmTransformers): sw-2627 restore meta spread for subscriptions
- the work in #1305 removed the `meta` spread that allowed subsequent display of meta response properties. Specifically this affects RHEL ELS in staging since it used the `subscription_type`, but any subscription inventory display that required this property would also be affected
1. navigate to the RHEL view
- confirm RHEL x86 ELS subscriptions inventory table displays the "subscription type" inventory column with relevant data
- next, comment out the patch on [line 143 ](https://github.com/RedHatInsights/curiosity-frontend/pull/1334/files#diff-6e49829ef27c76e1510fbce257d5b141e4c323262910f8eb678f1122615937bfR143), let the page rebuild, confirm the RHEL …
=> fix (rhsmTransformers): sw-2627 restore meta spread for subscriptions

package.json, scripts/actions.commit.js
- ci: relax integration checks
- the integration checks seem to suffer from the same setback here too...
- the env setup creates build output differences which in turn creates failures in the output checks. since we're already performing these checks in multiple places lets remove/relax them here too
- Confirm the related `ci` check now passes.
- There may still be failure, you'll have to review the related console output to confirm
...
ongoing
related #1290
=> ci: relax integration checks

config/jest.setupTests.js, src/common/README.md, src/common/__tests__/__snapshots__/dateHelpers.test.js.snap, src/common/__tests__/dateHelpers.test.js, src/common/dateHelpers.js, src/common/downloadHelpers.js
- feat(dateHelpers): sw-2353 added setMillisecondsFromDate
- test: expand jest renderHook, allow rerender, updated args
- incremental support work for sw-2353
- no visual updates associated with this work
...
related sw-2353 #1328
=> feat(dateHelpers): sw-2353 added setMillisecondsFromDate

src/config/product.openshiftContainer.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhacs.js, src/config/product.rhel.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js, src/config/product.satellite.js
- feat(config): sw-2353 activate json export for products
- test: redux createStore import
- this pr activates the toolbar export field
- adjusts the original polling implementation to allow for 2 paths to attaining downloads
-  post -> poll general status for specific export until complete -> download report -> delete report for clean up
- on UI load (user return) -> poll general status for ANY remaining exports until complete -> download ALL available reports -> delete ALL remaining reports for clean up
- filenames of downloaded reports, we ended up using the internal product identifier because it was shorter
- originally we had thought to use the short product display name for in the report download since it would be easier to identify to an end-user. unfortunately because some of the …
=> feat(config): sw-2353 activate json export for products

src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap, src/components/toolbar/toolbarFieldExportContext.js
fix: [SWATCH-2729](https://issues.redhat.com/browse/SWATCH-2729) Change data-test prop for custom export notification's "No" button to be unique.
- corrections for qe test environment
- In environment
- attempt to download an export/report from any product
- navigate away from the swatch ui, this includes all variants, using the left nav or direct navigation
- wait an average of 5 seconds, variations in this time should still produce similar results
- navigate back towards the swatch ui, a toast notification should appear with yes/no confirmation buttons
- Confirm the related qe tests are able to access the new `data-test` attribute for `No`
...
sw-2729
=> SWATCH-2729: Change custom export notification's data-test for No button

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap, src/components/toolbar/__tests__/toolbarFieldExportContext.test.js, src/components/toolbar/toolbarFieldExportContext.js
- refactor: sw-2353 onmount, dispatch refinement
- optimizes the onmount call for existing downloads, there should be no change in behavior
- restructure the dispatch calls to remove redundancy
- there's a limitation on multiple dispatches and the notifications redux provided through frontend components. the first call will go through, but subsequent notification calls will throw an error in a multi-dispatch situation. the quick solution is to avoid adding multiple notification adds/removals within the same dispatch
...
sw-2353 
related #1354
=> refactor: sw-2353 onmount, dispatch refinement

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap, src/components/toolbar/toolbarFieldExportContext.js
- test(toolbarFieldConext): sw-2353 add notification testIds
- added testIds to toast notification titles
- for existing exports there are `3` notification ids available ( note: there is no error notification for existing on purpose. it's a non-blocking error. if the existing export fails the result is the "existing notification" reappears on next application mount )
- Custom status type (the confirmation buttons title) = testId, `exportNotification-existing-confirmation`
- Upon hitting `yes` the following IDs should be available
- Info type (the pending title) = testId, `exportNotification-existing-pending`
- Success type (the success title) = testId, `exportNotification-existing-completed`
- for individual exports per variant there are `3` notification ids available
- Warning type (the …
=> test(toolbarFieldContext): sw-2353 add notification testIds

Jenkinsfile
"insights" nodes have been decomissioned since they were based on CentOS 7
Fix to the Jenkins file so that pipelines are scheduled in existing nodes.
...
=> Schedule Jenkins pipelines in rhel8 nodes

babel.config.js, config/webpack.dev.config.js, package-lock.json, package.json, src/styles/_graph.scss
- build(deps-dev): bump group with 5 updates
* @babel/core from 7.24.7 to 7.24.9
* @babel/eslint-parser from 7.24.7 to 7.24.8
* @babel/preset-env removed, use weldable version
* @babel/preset-react removed, use weldable version
- minor adjustment for updated scss compiler
- minor adjustment to local run and using the ts loader
- prep for migrating to ts
...
related sw-2707
=> build(deps-dev): bump group with 5 updates

src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap, src/components/toolbar/toolbarFieldExport.js
- feat(toolbarFieldExport): sw-2768 activate instances data
- **download note** - the downloaded data ONLY makes a human readable distinction between the instances and subscriptions reports via the `meta.json` file that is included in the package
1. navigate towards the ui and select an export for JSON
- confirm the downloaded file expands and contains both Subscriptions and Instances
...
sw-2768
=> feat(toolbarFieldExport): sw-2768 activate instances data

src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap, src/components/toolbar/__tests__/toolbarFieldExportContext.test.js, src/components/toolbar/toolbarFieldExport.js, src/components/toolbar/toolbarFieldExportContext.js, src/redux/reducers/appReducer.js, src/services/platform/__tests__/__snapshots__/platformConstants.test.js.snap, src/services/platform/platformConstants.js
- feat(toolbarFieldExport): sw-2769 activate csv export
- With this update we were attempting to avoid updating state with the immediate "[the user selected this type of export]" because we populate the list from polling status callback.
This lack of a state update created an interim period between the user selecting the CSV, or JSON, from the dropdown/select list, then having all entries disabled, then having the specific entry the user selected update. This is/was awkward!
So now we've attempted to patch and avoid this behavior so the user has more timely interaction feedback, but we may have to revisit it since the required polling behavior is on a 5 sec delay \<insert opinion on polling\> and the conflicting state update vs API response can get weird fast (heh, or at least in the 5 …
=> feat(toolbarFieldExport): sw-2769 activate csv export 

.github/workflows/integration.yml, CONTRIBUTING.md, scripts/pre.sh, src/common/README.md, src/common/helpers.js
- build: sw-2778 deprecate, remove, clean preview-beta refs
- Primarily
* integration, gh actions, remove beta-preview checks
* contributing, readme, release update, deprecate params
* pre script, deprecated annotations
* src/helpers, deprecate dotenv path prefix params
- We're temporarily leaving in the dotenv params since their use expands beyond `preview`-`beta`. We just happened to utilize them for that at the start of the project. Everything has been labeled `deprecated` (for future clean up)
-
...
sw-2778
=> build: sw-2778 deprecate, remove, clean preview-beta refs

.github/renovate.json
- build: fix renovate schedule
- fix konflux updates to something more predictable
- borrowed from the [HCS repo](https://github.com/RedHatInsights/hybrid-committed-spend-ui/blob/main/renovate.json)
...
ongoing
=> build: fix renovate schedule

src/config/product.ansible.js, src/services/rhsm/rhsmServices.js
- fix(config): sw-2956 display ints for ansible inventory
- replaces the float config with int directly from API
1. navigate towards the ansible display
- confirm the inventory display shows ints instead of floats
sw-2956
related sw-2932
=> fix(config): sw-2956 display ints for ansible inventory

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.ansible.js, src/config/product.rosa.js
- fix(config): sw-2966 remove single day x-axis increments
- minor configuration tweak for x-axis
1. confirm the ROSA and Ansible graph displays no longer shows single day number format only ticks, see below examples
=> fix(config): sw-2966 remove single day x-axis increments

package-lock.json, package.json
- build(deps): sw-2981 bump group with 2 updates
* @redhat-cloud-services/frontend-components from 4.2.14 to 4.2.15
* @redhat-cloud-services/frontend-components-config from 6.2.6 to 6.2.9
- bumps platform level packages as part of issue sw-2981 review
...
sw-2981
ongoing
=> build(deps): sw-2981 bump group with 2 updates

public/locales/en-US.json, src/components/authentication/__tests__/__snapshots__/authentication.test.js.snap, src/components/authentication/__tests__/authentication.test.js, src/components/authentication/authentication.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/messageView/messageView.js
- refactor(authentication): sw-2479 consistent locale keys
* locale, auth keys
* authentication, updated auth keys, test snapshots
* messageView, allow component or func ref
- clean up exposed while updating sw-2479
- there should be no visual difference to an end user
...
related sw-2479 #1433 #1432 #1416
=> 4 of 4, fix(authentication): consistent locale keys

src/components/README.md, src/components/authentication/authentication.js, src/components/bannerMessages/bannerMessages.js, src/components/i18n/i18n.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap
- refactor(auth,banner,i18n): sw-2707 remove deprecated react
* authentication, bannerMessages, i18n remove defaultProps, propTypes
- start the process of removing deprecated react, default props and prop types. this will be a multi-pr process
...
sw-2707
=> refactor(auth,banner,i18n): sw-2707 remove deprecated react

src/components/README.md, src/components/inventoryCard/inventoryCard.js, src/components/inventoryCardInstances/__tests__/__snapshots__/inventoryCardInstances.test.js.snap, src/components/inventoryCardInstances/inventoryCardInstances.js, src/components/inventoryCardSubscriptions/__tests__/__snapshots__/inventoryCardSubscriptions.test.js.snap, src/components/inventoryCardSubscriptions/inventoryCardSubscriptions.js, src/components/inventoryGuests/inventoryGuests.js, src/components/inventoryTabs/inventoryTab.js, src/components/inventoryTabs/inventoryTabs.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap
- refactor(inventoryCards,tabs): sw-2707 remove deprecated react
- remove inventoryCards' default props and types. affects
- inventoryCard
- inventoryCardInstances
- inventoryCardSubscriptions
- inventoryGuests
...
sw-2707
=> refactor(inventoryCards,tabs): sw-2707 remove deprecated react

src/components/README.md, src/components/loader/__tests__/__snapshots__/loader.test.js.snap, src/components/messageView/__tests__/__snapshots__/messageView.test.js.snap, src/components/optinView/__tests__/__snapshots__/optinView.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageHeader.test.js.snap, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/pageColumns.js, src/components/pageLayout/pageHeader.js, src/components/pageLayout/pageLayout.js, src/components/pageLayout/pageMessages.js, src/components/pageLayout/pageSection.js, src/components/pageLayout/pageToolbar.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap
- refactor(pageLayout): sw-2707 remove deprecated react
- removes default props and types
...
sw-2707
=> refactor(pageLayout): sw-2707 remove deprecated react

src/components/README.md, src/components/inventoryCard/__tests__/__snapshots__/inventoryCard.test.js.snap, src/components/pagination/__tests__/__snapshots__/pagination.test.js.snap, src/components/pagination/pagination.js, src/components/productView/productView.js, src/components/productView/productViewMissing.js
- refactor(pagination,productView): sw-2707 remove deprecated react
- removes default props and types
...
sw-2707
=> refactor(pagination,productView): sw-2707 remove deprecated react

src/components/README.md, src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/textInput.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldDisplayName.test.js.snap
- refactor(textInput): sw-2707, class to func, deprecated react
- move from component class to function
- remove proptypes and replace default props
1. confirm the "display name" field still works as intended and submits queries accordingly
...
sw-2707
=> refactor(textInput): sw-2707, class to func, deprecated react

src/services/common/__tests__/serviceConfig.test.js
- test(serviceConfig): reduce mock response interval
- attempt 2 for squashing the test flake
...
related to #1459
=> test(serviceConfig): reduce mock response interval

src/components/README.md, src/components/form/__tests__/__snapshots__/select.test.js.snap, src/components/form/select.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingProvider.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldCategory.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldExport.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGranularity.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldRangedMonthly.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldSelectCategory.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldSla.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldUsage.test.js.snap
- refactor(select): sw-2707 remove deprecated react
- remove deprecated React
...
sw-2707
=> refactor(select): sw-2707 remove deprecated react

src/components/i18n/__tests__/i18nHelpers.test.js
- test(i18nHelpers): sw-2707 replace deprecated react
- replace default props
...
sw-2707
=> test(i18nHelpers): sw-2707 replace deprecated react

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.ansible.js, src/config/product.rosa.js
fix(config): sw-2966 consistent x-axis for all products
- This is follow up work. Due to updates in #1480 and #1478 the configuration is now "more correct" . This in turn means all remnants of the old "list-every-day-for-the-x-axis" need to be removed
1. confirm the x-axis ticks now increment the same for all products, ROSA and Ansible displays specifically
what it looks like in test/stage/local
expected results
related #1426 #1480 and #1478 and sw-2707
sw-2966
=> fix(config): sw-2966 consistent x-axis for all products

src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.ansible.js, src/config/product.openshiftContainer.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhel.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js, src/config/product.satellite.js
Removed trailing slash from inventory links
1. Go to Subscriptions Usage > RHEL > Current instances tab
2. Inventory link shouldn't have a trailing slash
1. next...
-->
[RHINENG-15664](https://issues.redhat.com/browse/RHINENG-15664)
=> fix: RHINENG-15664 inventory link

src/services/common/__tests__/__snapshots__/serviceConfig.test.js.snap, src/services/common/__tests__/serviceConfig.test.js
- test(serviceConfig): restructure for readability
- the polling config checks throw an intermittent/random-like test flake typically seen when running nodejs 20. similar tests around settimeout in other repos, with github actions and multiple nodejs versions being checked, almost always present with a lesser nodejs version failing around settimeout
- primary updates
- applying mocks with `beforeEach` and `afterEach` adjusts the polling counts in an attempt to be more accurate
- breaking the tests out into multiple describe statements is intended to improve readability
- Confirm unit test updates reflect minor adjustments to the original tests. This is a line-x-line check against the snapshot test so no shortcuts
- Confirm the unit tests still pass
...
ongoing
=> test(serviceConfig): restructure for readability

.github/dependabot.yml
- build(deps): dependabot groups, ignored dep
- restores the ignore on i18next packages, see #1528  and #1523
- strips `minor` from weekly prod updates. prep for future where `minor` and `major` updates are done monthly instead
- watching https://github.com/dependabot/dependabot-core/issues/1778
...
ongoing
=> build(deps): dependabot groups, ignored dep

package-lock.json, package.json
- build(deps-dev): bump weldable from 3.2.4 to 4.1.0
- package is related to build output and local run
1. confirm local run starts and can be used as intended
...
ongoing
=> build(deps-dev): bump weldable from 3.2.4 to 4.1.0

src/components/toolbar/toolbar.js, src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap, src/redux/reducers/viewReducer.js
- fix(toolbar): sw-3443 productId key refresh
* toolbar, productId key refresh component, align with toolbarFields
* viewReducer, simplify focused query reset to hard reset
- corrects an intermittent issue where the `Reset filters` link/button on the toolbar doesn't always hide when moving between product variants. The issue shows up on local development run more often than environment. You can attempt to recreate locally by...
- First, navigating to any product and select a toolbar filter that generates a toolbar token (we used OpenShift Container Annual with SLA "premium")
- Then navigating to a different product variant (we used RHACS) and you may see the "Reset filters" link/button still displaying
- simplifies the focused query reset with a hard reset since the previous products …
=> fix(toolbar): sw-3443 productId key refresh

src/redux/reducers/__tests__/__snapshots__/viewReducer.test.js.snap, src/redux/reducers/viewReducer.js
- revert(viewReducer): sw-3443 rollback to focused reset
- little side-tracked today... attempting a hard reset on state borks the intent of #1564 #1565
- restores the solution from #1564 
1. reconfirm that selecting a variant, then filter, waiting 20 secs, selecting a different variant doesn't re-fire the previous variants API calls
...
related #1564 #1565
sw-3443
=> revert(viewReducer): sw-3443 rollback to focused reset

src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap, src/components/toolbar/toolbarFieldGroupVariant.js, src/redux/reducers/__tests__/__snapshots__/graphReducer.test.js.snap, src/redux/reducers/__tests__/graphReducer.test.js, src/redux/reducers/graphReducer.js, src/redux/reducers/viewReducer.js, src/redux/types/__tests__/__snapshots__/index.test.js.snap, src/redux/types/index.js
- fix(toolbarFieldCategory): sw-3443 reset filter and legend links
- subsequent fix related to the category/type filter field not resetting correctly when a user navigates between variants
- this fix, now, also resets when independent legend links/buttons are clicked and a user navigates between variants
1. Select a product variant, like RHEL x86
- select a RHEL x86 category/type, like "hypervisor" to focus the graph legend
- change product variants
- change product variants back to RHEL x86, confirm the graph legend and category/type filter have reset
1. Select a product variant, like RHEL x86
- select a RHEL x86 …
=> fix(toolbarFieldCategory): sw-3443 reset filter and legend links

src/components/form/__tests__/__snapshots__/select.test.js.snap, src/components/form/__tests__/select.test.js, src/components/form/select.js
- fix(select): sw-3468 consistent multiple, single return value
- this issue only affects staging, see #1562 
- corrects an issue where the dropdown variant was returning a list instead of a single value
- adds missing unit test that would have caught the issue
1. confirm the export `dropdown` now correctly submits the value for export, `json` and/or `csv`
1. confirm the export `dropdown` now correctly submits the value for export, `json` and/or `csv`
...
related to #1562, sw-3339
sw-3468
=> fix(select): sw-3468 consistent multiple, single return value

src/components/README.md, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/productView/productView.js, src/components/router/__tests__/__snapshots__/routerContext.test.js.snap, src/components/router/__tests__/routerContext.test.js, src/components/router/routerContext.js, src/components/toolbar/toolbarFieldGroupVariant.js
- perf(productView,routerContext): sw-95 product load optimization
* productView, move to useMemo
* routerContext, switch to cached memo matching
* toolbarFieldGroupVariant, move to useMemo
- config loading optimizations exposed while working through sw-95
- retains a level of product context memoization related to how Chroming potentially loads UI code and/or handles routing. avoid unnecessary renders
1. confirm navigation between product variants behaves
- as intended
- api calls remain unchanged
1. confirm navigation …
=> perf(productView,routerContext): sw-95 product load optimization

public/locales/en-US.json, src/components/README.md, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingAccount.test.js.snap, src/components/toolbar/toolbarFieldBillingAccount.js
- fix(toolbarFieldBillingAccount): sw-3513 remove locale ref
- In scenarios where account identifiers contain underscores they can alter how the translation wrapper determines context. The fix is to avoid using the translation wrapping entirely.
1. navigate to a product display, such as OpenShift AI
- confirm the billing provider and billing account fields are displaying as intended
1. navigate to a product display, such as OpenShift AI
- confirm the billing provider and billing account fields are displaying as intended
...
sw-3513
related to sw-95 #1577
=> fix(toolbarFieldBillingAccount): sw-3513 remove locale ref

public/locales/en-US.json, src/components/toolbar/__tests__/__snapshots__/toolbarFieldBillingProvider.test.js.snap, src/components/toolbar/toolbarFieldBillingProvider.js, src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/rhsmTransformers.js
fix(rhsmTransformers): sw-95 allow id overlap per provider
- discovered during testing... "unique providers" are currently being filtered when account ids happened to overlap. 
- original logic assumed "ids are unique across provider"
- this update assumes we can't always guarantee the account ids being returned by provider are unique
- multiple providers can now have the same account ids, ie. AWS could have the same account identifier as Azure and they would be unique to the provider. This wouldn't necessarily happen in the wild but the UI code now makes an allowance for wonky identifiers
- for final clarity... `the UI does NOT make up any providers or account identifiers, it only returns what the billing account id instances and subscriptions API responses give it`
1. update the NPM …
=> fix(rhsmTransformers): sw-95 allow id overlap per provider

src/config/product.ansible.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rosa.js
- feat(config): sw-95 activate dynamic provider, accounts
- activate the dynamic billing provider and accounts for
- OpenShift Metrics and Dedicated Metrics
- ROSA
- Ansible
1. confirm new dynamic fields display and function per the corresponding product list above
1. confirm new dynamic fields display and function per the corresponding product list above
=> feat(config): sw-95 activate dynamic provider, accounts

src/components/README.md, src/components/productView/__tests__/__snapshots__/productViewContext.test.js.snap, src/components/productView/__tests__/__snapshots__/productViewOnloadContext.test.js.snap, src/components/productView/__tests__/productViewContext.test.js, src/components/productView/__tests__/productViewOnloadContext.test.js, src/components/productView/productViewContext.js, src/components/productView/productViewOnload.js, src/components/productView/productViewOnloadContext.js, tests/__snapshots__/dist.test.js.snap
- refactor(productViewOnloadContext): sw-95 component related onload hooks
* productViewContext, remove useProductOnload hook
* productViewOnloadContext, new file, apply useProductOnload
- group onload hooks slightly better (we just moved code around)
- related to upcoming banner messaging indicating there might be a "usage" issue, #1587 
...
sw-95
=> refactor(productViewOnloadContext): sw-95 component related hooks

src/services/rhsm/__tests__/__snapshots__/rhsmHelpers.test.js.snap, src/services/rhsm/__tests__/__snapshots__/rhsmTransformers.test.js.snap, src/services/rhsm/rhsmHelpers.js
- fix(rhsmHelpers): sw-3519 expose unique accounts, providers
- minor helper adjustment to expose a unique listing of account, providers for potential consumption
...
sw-3519
=> fix(rhsmHelpers): sw-3519 expose unique accounts, providers

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/productView/productViewOnloadContext.js
- fix(locale): sw-3519 unique provider names context
- minor locale context issue, adjustment
- similar to issue resolved in #1583 for sw-3513 where unique "provider names" display in "unique ways"
1. confirm the staging provider name `_ANY` displays as intended within the banner message
...
sw-3519 
related sw-3513
=> fix(locale): sw-3519 unique provider names context

public/locales/en-US.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap, src/components/tooltip/tooltip.js, src/config/__tests__/__snapshots__/product.config.test.js.snap, src/config/product.ansible.js, src/config/product.openshiftDedicated.js, src/config/product.openshiftMetrics.js, src/config/product.rhacm.js, src/config/product.rhacs.js, src/config/product.rhelElsPayg.js, src/config/product.rhods.js, src/config/product.rosa.js, src/services/rhsm/rhsmServices.js, src/styles/_tooltip.scss
- fix(config): sw-3519 instances tooltip for billing accounts
- adds a tooltip to highlight the billing account id associated with a billing provider in the instances inventory display.
- useful for scenarios when usage vs subscriptions is mismatched
1. navigate towards variant that uses the billing provider/account filtering, we leveraged OpenShift AI
- scroll down to the instances inventory display
- a tooltip next to the "Purchased through" column header should provide an explanation
- hovering over the provider column per each instance inventory row should display the associated billing account id
sw-3519
=> fix(config): sw-3519 instances tooltip for billing accounts

deploy/pr_check.sh
swatch redhat marketplace is no longer deployed.  Remove it from the ci.  This will enable the ephemeral deploy to work.
swatch-3595
...
...
sw-3595
=> ci: sw-3595 rm swatch-producer-red-hat-marketplace

src/components/README.md, src/components/pageLayout/pageColumns.js, src/components/productView/__tests__/__snapshots__/productView.test.js.snap, src/components/productView/productView.js, src/components/toolbar/__tests__/__snapshots__/toolbarFieldGroupVariant.test.js.snap, src/components/toolbar/toolbarFieldGroupVariant.js, src/styles/_banner.scss, src/styles/_card.scss, src/styles/_fade.scss, src/styles/_graph.scss, src/styles/_page-layout.scss, src/styles/_tabs.scss, src/styles/_toolbar.scss, src/styles/index.scss, src/styles/standalone.scss
- fix: sw-3639 pf6 layout adjustments
- layout adjustments, clean up
- corrects most of the spacing between major areas. 
- we retained a minimal space between the toolbar and inventory tabs components due to the lack of spacing around the inventory tabs "plain" card which inadvertently aligns the top of tabs right at the bottom of the graph displays
- internal deprecated component clean up
- modal adjustments for chrome/consoledot header
1. all styling updates except the modal adjustment can be seen in proxy run
- confirm adjustments are as intended
- modal adjustments can't be seen …
=> fix: sw-3639 pf6 layout adjustments

src/components/toolbar/__tests__/__snapshots__/toolbarFieldExportContext.test.js.snap, src/components/toolbar/toolbarFieldExportContext.js
- fix(toolbarFieldExportContext): sw-3639 notification confirmation
- bug in the bug fix for #1660 
- reapply the remove notification when the existing exports confirmation is "no"
...
sw-3639 relates #1660
=> fix(toolbarFieldExportContext): sw-3639 notification confirmation

package-lock.json, package.json
- build(deps): bump axios from 1.9.0 to 1.11.0
...
ongoing
=> build(deps): bump axios from 1.9.0 to 1.11.0
